### DISCUSSION TITLE
LDAP authentication is not working with Microsoft Active Directory

### DISCUSSION THREAD

**Discussion by senthil13** [provectus/kafka-ui#2631] [Q&A] [answered]
Everything works fine with the Kafka-UI, but when we enable the authentication for LDAP to login, it's not working and we are not getting proper errors in the logs.

Below is the docker-compose config file, I masked a couple of parameters.

```
version: '2'
services:
  kafka-ui:
    image:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXkafka-ui:master-v0.5.0
    container_name: kafka-ui
    ports:
      - "9080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=POC
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
      - KAFKA_CLUSTERS_0_READONLY=true
      - LOGGING_LEVEL_ROOT="debug"
      - AUTH_TYPE="LDAP"
      - SPRING_LDAP_URLS="ldap://ldap.corp.XXXXX.com:389"
      - SPRING_LDAP_DN_PATTERN:"cn={0},DC=corp,DC=XXX,DC=com"
      - SPRING_LDAP_USERFILTER_SEARCHBASE="OU=XXXX,OU=XXX,DC=corp,DC=XXXX,DC=com"
      - SPRING_LDAP_USERFILTER_SEARCHFILTER=(&(uid={0})(objectClass=inetOrgPerson))
```

Error logs

```
kafka-ui    | 2022-09-22 13:49:20,748 DEBUG [boundedElastic-1] o.s.s.w.s.a.AuthenticationWebFilter: Authentication failed: Invalid Credentials
kafka-ui    | 2022-09-22 13:49:20,749 DEBUG [boundedElastic-1] o.s.s.w.s.DelegatingServerAuthenticationEntryPoint: Trying to match using org.springframework.security.config.web.server.ServerHttpSecurity$HttpBasicSpec$$Lambda$926/0x0000000801116440@5791dfa1
kafka-ui    | 2022-09-22 13:49:20,750 DEBUG [boundedElastic-1] o.s.s.w.s.DelegatingServerAuthenticationEntryPoint: No match found. Using default entry point org.springframework.security.web.server.authentication.HttpBasicServerAuthenticationEntryPoint@693b4c2b
kafka-ui    | 2022-09-22 13:49:20,750 DEBUG [boundedElastic-1] o.s.w.s.a.HttpWebHandlerAdapter: [851ddcd1-4] Completed 401 UNAUTHORIZED
kafka-ui    | 2022-09-22 13:49:20,752 DEBUG [boundedElastic-1] r.n.h.s.HttpServerOperations: [851ddcd1-2, L:/172.21.0.2:8080 - R:/172.31.52.65:53198] Last HTTP response frame
kafka-ui    | 2022-09-22 13:49:20,752 DEBUG [boundedElastic-1] r.n.h.s.HttpServerOperations: [851ddcd1-2, L:/172.21.0.2:8080 - R:/172.31.52.65:53198] No sendHeaders() called before complete, sending zero-length header
kafka-ui    | 2022-09-22 13:49:20,752 DEBUG [boundedElastic-2] o.s.s.w.s.a.AuthenticationWebFilter: Authentication failed: Invalid Credentials
```

Any help will be much appriciated. 

Thanks
Senhtil
