### DISCUSSION TITLE
RBAC auth0 provider

### DISCUSSION THREAD

**Discussion by Teviwe** [provectus/kafka-ui#3343] [Q&A] [answered]
Greetings.

At version kafka-ui 0.5.0 want start used RBAC policies for clusters.
But in RBAC [manual](https://github.com/provectus/kafka-ui/wiki/RBAC-(role-based-access-control)) list of supported providers didn't contain auth0 provider.
**auth0** provider was configured as described here in issue my last [comment](https://github.com/provectus/kafka-ui/issues/3272) and works fine.

When try added section with auth0:
```
subjects:
      - provider: oauth_auth0
         type: user
         value: "username"
      - provider: oauth_auth0
         type: group
         value: "testmember"
```
In logs get trace:
`Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accessControlService': Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "com.provectus.kafka.ui.model.rbac.provider.Provider.ordinal()" because the return value of "com.provectus.kafka.ui.model.rbac.Subject.getProvider()" is null`

Question: Can RBAC works with auth0 provider?
Thanks for answer.
