### DISCUSSION TITLE
How to set up Google oauth through environment variables instead of config yaml

### DISCUSSION THREAD

**Discussion by joaoluchetti** [provectus/kafka-ui#3434] [Q&A] [answered]
Hi,

I am configuring google oauth and would like to have my clientid and clientsecret coming from a secret instead of putting it as plaintext inside the values.yaml yamlApplicationConfig section, is it possible to setup oauth through envs that read from a secret?

Thanks in advance.

**Comment by Narekmat** [comment, marked as answer]
Hello @joaoluchetti.
Yes you can. There are two ways.
1. You can create secret and specify that secret name in values.yaml "existingSecret: """  section.
2. You can specify your vars in section envs.secret with key:value in values.yaml
Here is an example.
```
envs:
  secret:
    TEST1_ENV: test1_value
    TEST2_ENV: test2_value
```

**Reply by joaoluchetti** [reply]
Hi, 

Thanks for your answer.

I see, but what should be the variables for Google Oauth? couldn't find it on the documentation

**Reply by Haarolean** [reply]
```
kafka:
  clusters:
    - name: local
      bootstrapServers: localhost:9092
    # ...

auth:
  type: OAUTH2
  oauth2:
    client:
      google:
        provider: google
        clientId: xxx.apps.googleusercontent.com
        clientSecret: GOCSPX-xxx
        user-name-attribute: email
        custom-params:
          type: google
          allowedDomain: provectus.com
```
Line breaks are replaceable with an underscore if you wish to see them in env vars format (I recommend using yaml config map with helm).
