### DISCUSSION TITLE
How to expose Kafka-UI over TLS?

### DISCUSSION THREAD

**Discussion by vascoferraz** [provectus/kafka-ui#3464] [Q&A] [answered]
Hi everyone,

Can anyone please share a template that allows Kafka-UI to be exposed over TLS?

Thank you so much.

Vasco Ferraz

**Comment by Haarolean** [comment, marked as answer]
Behind a reverse proxy: [kafka-ui-reverse-proxy.yaml](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ui-reverse-proxy.yaml)
If you really wanna make the app itself SSL secured (I recommend the reverse proxy way), take a look at [this](https://www.baeldung.com/spring-boot-https-self-signed-certificate) (3.1)

**Reply by vascoferraz** [reply]
Thanks for the guidance :)

**Comment by vascoferraz** [comment]
Hi @Haarolean.

I was trying the approach of adding the following environment variables into the values.yaml file but the kafka-ui pod keeps restarting.

```
env:
  - name: "SERVER_SSL_ENABLED"
    value: "true"
  - name: "SERVER_SSL_KEY_STORE"
    value: "/mnt/sslcerts/keystore.p12"
  - name: "SERVER_SSL_KEY_STORE_PASSWORD"
    value: "mystorepassword"
```

I believe that this was already addressed [here](https://github.com/provectus/kafka-ui/issues/2923) and apparently solved with this [PR](https://github.com/provectus/kafka-ui/pull/2924) but somehow it's not working on my side.

Can you please guide me on this?

Thank you so much.

Vasco Ferraz
