### DISCUSSION TITLE
Is there a way to add basic auth to the kafka-ui itself?

### DISCUSSION THREAD

**Discussion by ekeric13** [provectus/kafka-ui#3510] [Q&A] [answered]
I am not talking about adding basic auth so that kafka-ui can connect to kafka services that require basic auth. I am talking about needing basic auth to access kafka-ui.

Are there env variables or configuration in the application.yaml that i can specify so that the kafka-ui contents can only be accessed after specifying a username and password?

**Comment by Haarolean** [comment, marked as answer]
Hi, try this:
https://github.com/provectus/kafka-ui/blob/4d03802a5dc77f6b327485484eb63106a87152b5/documentation/compose/kafka-ui-auth-context.yaml#L17-19

**Reply by ekeric13** [reply]
Awesome that worked perfectly :)

any reason why you don't want to put that in the main readme?

Also, i am using upstash for my managed kafka broker and it just wasn't working with the environment variables.
I had to use the application.yml pattern where I define a application yaml file and i copy it into my dockerfile:
https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/resources/application-local.yml
https://docs.upstash.com/kafka/howto/monitor-with-kafkaui

How might i translate the env variables to a application file? Something along these lines (this in particular doesn't work)?
```
kafka:
  clusters:
    - name: upstash
      auth.type: LOGIN_FORM
      spring.security.user.name: admin
      spring.security.user.password: pass
```

**Reply by Haarolean** [reply]
>any reason why you don't want to put that in the main readme?

The readme is a mess, the docs are the one is well, we have docs refactoring in progress

```
auth:
  type: LOGIN_FORM
spring:
  security:
    user:
      name: admin
      password: yyy
kafka:
  clusters:
    - name: upstash
```
