### DISCUSSION TITLE
Unable to set Cognito OAuth logouturl

### DISCUSSION THREAD

**Discussion by VikramAhuja** [provectus/kafka-ui#3520] [Q&A]
Hi,

I am trying to run kafka-ui using docker. I have configured cognito for Oauth. But it does not seems to be picking up logout url.

Here is my code from docker compose file 

```
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.6.0
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - AUTH_TYPE=OAUTH2
      - AUTH_OAUTH2_CLIENT_COGNITO_CLIENT-ID=<client-id>
      - AUTH_OAUTH2_CLIENT_COGNITO_CLIENT-SECRET=<secret>
      - AUTH_OAUTH2_CLIENT_COGNITO_SCOPE=openid
      - AUTH_OAUTH2_CLIENT_COGNITO_CLIENT-NAME=kafka-ui
      - AUTH_OAUTH2_CLIENT_COGNITO_PROVIDER=cognito
      - AUTH_OAUTH2_CLIENT_COGNITO_REDIRECT-URI=http://localhost:8080/login/oauth2/code/cognito
      - AUTH_OAUTH2_CLIENT_COGNITO_AUTHORIZATION-GRANT-TYPE=authorization_code
      - AUTH_OAUTH2_CLIENT_COGNITO_ISSUER-URI=https://cognito-idp.eu-west-2.amazonaws.com/<pool-id>
      - AUTH_OAUTH2_CLIENT_COGNITO_JWK-SET-URI=https://cognito-idp.eu-west-2.amazonaws.com/<pool-id>/.well-known/jwks.json
      - AUTH_OAUTH2_CLIENT_COGNITO_USER-NAME-ATTRIBUTE=username
      - AUTH_OAUTH2_CLIENT_COGNITO_custom-params_type=cognito
      - AUTH_OAUTH2_CLIENT_COGNITO_custom-params_logoutUrl=https://<domain>.auth.eu-west-2.amazoncognito.com/logout

```

Error I get is 

```
kafka-ui              | 2023-03-20 11:12:09,270 ERROR [reactor-http-epoll-4] o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler: [7a9bf471-21]  500 Server Error for HTTP POST "/logout"
kafka-ui              | java.lang.IllegalArgumentException: Custom params should contain 'logoutUrl'
kafka-ui              |         at org.springframework.util.Assert.isTrue(Assert.java:121)
kafka-ui              |         Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
kafka-ui              | Error has been observed at the following site(s):
kafka-ui              |         *__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
kafka-ui              |         *__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
kafka-ui              |         *__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
kafka-ui              |         *__checkpoint ⇢ org.springframework.security.web.server.ui.LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
kafka-ui              |         *__checkpoint ⇢ org.springframework.security.web.server.ui.LoginPageGeneratingWebFilter [DefaultWebFilterChain]
kafka-ui              |         *__checkpoint ⇢ org.springframework.security.oauth2.client.web.server.authentication.OAuth2LoginAuthenticationWebFilter [DefaultWebFilterChain]
kafka-ui              |         *__checkpoint ⇢ org.springframework.security.oauth2.client.web.server.OAuth2AuthorizationRequestRedirectWebFilter [DefaultWebFilterChain]
kafka-ui              |         *__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
kafka-ui              |         *__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
kafka-ui              |         *__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
kafka-ui              |         *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
kafka-ui              |         *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
kafka-ui              |         *__checkpoint ⇢ HTTP POST "/logout" [ExceptionHandlingWebHandler]
kafka-ui              | Original Stack Trace:
kafka-ui              |                 at org.springframework.util.Assert.isTrue(Assert.java:121)
kafka-ui              |                 at com.provectus.kafka.ui.config.auth.logout.CognitoLogoutSuccessHandler.handle(CognitoLogoutSuccessHandler.java:49)
kafka-ui              |                 at com.provectus.kafka.ui.config.auth.logout.OAuthLogoutSuccessHandler.lambda$onLogoutSuccess$0(OAuthLogoutSuccessHandler.java:37)
kafka-ui              |                 at java.base/java.util.Optional.map(Optional.java:260)
kafka-ui              |                 at com.provectus.kafka.ui.config.auth.logout.OAuthLogoutSuccessHandler.onLogoutSuccess(OAuthLogoutSuccessHandler.java:37)
kafka-ui              |                 at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.logout(LogoutWebFilter.java:76)
kafka-ui              |                 at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.lambda$filter$2(LogoutWebFilter.java:65)
```

Can someone help me to know how to set logoutUrl in custom-params?
