### DISCUSSION TITLE
Docker Compose not connecting

### DISCUSSION THREAD

**Discussion by ThomasVaillant** [provectus/kafka-ui#3541] [Q&A]
Hey there :)

I tried building a full docker compose file with zookeeper and kafka. For some reason kafka-ui does not want to connect to my kafka on my windows machine. Do you maybe see some immediate problems here?

```
# Docker Compose for HEM Service
#
# 'docker-compose up' will run this.
version: '3.7'  # requires Docker Compose 1.13 or later

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8094:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: "lokalhorst"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: host.docker.internal:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: host.docker.internal:2181
    init: true
    networks:
      - network
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    #    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_SERVERS: "zookeeper:22888:23888"
    init: true
    networks:
      - network

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    init: true
    networks:
      - network

networks:
  # Declare our private network. We must declare one for the magic
  # Docker DNS to work, but otherwise its default settings are fine.
  network: { }
```
