### DISCUSSION TITLE
How to set loglevel to Error ?

### DISCUSSION THREAD

**Discussion by opsdevopss** [provectus/kafka-ui#3620] [Q&A] [answered]
I want to set the loglevel to Error and it should send only error logs to datadog instead of info. I have tried with different configs but still i can see info here are the entries i have. used in my values.yaml file: 

```
extraEnvs:
  - name: KAFKA_UI_LOG_LEVEL
    value: error
```

`  setValues:
  kafka-ui:
    javaOpts: "-Dlog.level=error"`
    
  ```
logging:
  loggers:
    org:
      apache:
        kafka:
          logLevel: ERROR
```
          
`rootLogger.level: ERROR`

`LOGGING_LEVEL_ROOT: ERROR`

**Comment by Haarolean** [comment, marked as answer]
Hey, it's like this:

```
logging:
  level:
    root: INFO
    com.provectus: DEBUG
    #org.springframework.http.codec.json.Jackson2JsonEncoder: DEBUG
    #org.springframework.http.codec.json.Jackson2JsonDecoder: DEBUG
    reactor.netty.http.server.AccessLog: INFO
```

You can specify these values right in the config.
