### DISCUSSION TITLE
Schema Registry

### DISCUSSION THREAD

**Discussion by abhinavgautam07** [provectus/kafka-ui#3791] [Q&A]
How to enable schema registry on the UI.

**Comment by vascoferraz** [comment]
Use this manifest to enable Schema Registry, Kafka Connect and kSQL:

```
yamlApplicationConfig:
  kafka:
    clusters:
      - name: my-kafka-cluster
        bootstrapServers: "kafka.confluent.svc.cluster.local:9092"
        properties:
          sasl.mechanism: PLAIN
          security.protocol: SASL_SSL
          sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka-secret";
          ssl.keystore.location: /mnt/sslcerts/keystore.p12
          ssl.keystore.password: mystorepassword
        kafkaConnect:
          - name: connect-cluster
            address: https://connect.confluent.svc.cluster.local:8083
            username: connect
            password: connect-secret
            keystorelocation: /mnt/sslcerts/keystore.p12
            keystorepassword: mystorepassword
        schemaRegistry: https://schemaregistry.confluent.svc.cluster.local:8081
        schemaRegistryAuth:
            username: sr
            password: sr-secret
        schemaRegistrySSL:
            keystorelocation: /mnt/sslcerts/keystore.p12
            keystorepassword: mystorepassword
        ksqlDBServer: https://ksqldb.confluent.svc.cluster.local:8088
        ksqlDBServerAuth:
            username: ksql
            password: ksql-secret
        ksqlDBServerSSL:
            keystorelocation: /mnt/sslcerts/keystore.p12
            keystorepassword: mystorepassword
        ssl:
          truststorelocation: /mnt/sslcerts/truststore.p12
          truststorepassword: mystorepassword

  auth:
    type: LOGIN_FORM
  spring:
    security:
      user:
        name: admin
        password: admin

env:
  - name: "SERVER_SSL_ENABLED"
    value: "true"
  - name: "SERVER_SSL_KEY_STORE"
    value: "/mnt/sslcerts/keystore.p12"
  - name: "SERVER_SSL_KEY_STORE_PASSWORD"
    value: "mystorepassword"

probes:
  useHttpsScheme: true

service:
  type: NodePort
  nodePort: 30901

volumeMounts:
  - mountPath: /mnt/sslcerts
    name: kafka-ui

volumes:
  - name: kafka-ui
    secret:
      secretName: kafkaui-pkcs12
```
