### DISCUSSION TITLE
How to change port num in application.yml with JAR?

### DISCUSSION THREAD

**Discussion by waitspring** [provectus/kafka-ui#3924] [Q&A] [answered]
I deployed Kafka-UI in a host by JAR, and `8080` port has been taken by another process.  
And this is my application.yml:

```yml
kafka:
  clusters:
    -
      name: local
      bootstrapServers: localhost:9092
```

When I start Kafka-UI with command `$ java -Dspring.config.additional-location=application.yml -jar kafka-ui-api-v0.7.0.jar`, Kafka-UI start up failure with `8080` port error.  
  
How can I change the port num in application.yml?
