### DISCUSSION TITLE
Why Kafka-UI send two requests to OpenLDAP when login?

### DISCUSSION THREAD

**Discussion by waitspring** [provectus/kafka-ui#3954] [Q&A] [answered]
As my title say that, when we login Kafka-UI website, the Kafka-UI server send two requests to OpenLDAP:

+ first request is bind to `dn="dc=domain,dc=com"`, and result is `tag=97 err=49 text=` because of invalid credentials;
+ second request is bind to `dn="cn=admin,dc=domain,dc=com"`, and result is `tag=97 err=0 text=`.

And I cannot login Kafka-UI website because of the first request (I think).

This is my application.yml about LDAP, please help me look for error:
```yml
auth:
  type: LDAP
spring:
  ldap:
    urls: ldap://xxx.xxx.xxx.xxx:389
    base: "dc=season,dc=com"
    admin-user: "cn=admin,dc=season,dc=com"
    admin-password: "123"
    user-filter-search-base: "dc=season,dc=com"
    user-filter-search-filter: ""
oauth2:
  ldap:
    activeDirectory: false
```
