### DISCUSSION TITLE
How to pass some config values via environment variables? helm, k8s

### DISCUSSION THREAD

**Discussion by PDVJAM** [provectus/kafka-ui#4060] [General]
Hey!
I use k8s deployment of the kafka-ui, via the official helm chart. The question is (manual is very brief and unclear) how to pass some variables (more specifically - password for SASL configuration) via k8s secrets?
I have in the config the following:
```
existingSecret: "kafka-ui-user"
envs:
  secret: {}
  config:
    KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="$(PASSWORD)";'
```

And PASSWORD is in the secret.
I can see its value in the env variables, but it can't be passed to the config.
Was someone able to do this?
Would be glad for any help.

**Comment by PDVJAM** [comment]
```
apiVersion: v1
data:
  SPRING_SECURITY_USER_NAME: ...=
  SPRING_SECURITY_USER_PASSWORD: ...=
  KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: ...=
kind: Secret
metadata:
  name: kafka-ui
type: Opaque
```

Ok, seems like this works. Just to put whole SALS into the secret.
