### DISCUSSION TITLE
Frequent authentication page presented for google oauth

### DISCUSSION THREAD

**Discussion by darkLord19** [provectus/kafka-ui#4065] [Q&A] [answered]
I have integrated google oauth with kafka-ui and it's working perfectly but one issue is that it is asking for re auth very frequently. Tried to search in existing issues and docs but didn't find anything related to this. Is there any way to avoid this?

**Comment by Haarolean** [comment]
Hi, sometimes it's related more to the OAuth provider than the app itself. Let's say with GitHub I don't have to re-auth at all but with Google -- quite frequently.
Please try setting `server.servlet.session.timeout` to something greater than the default value (30 minutes). If a duration suffix is not specified, seconds will be used.

**Reply by youribonnaffe** [reply]
Hello,

I tried setting the `server.servlet.session.timeout` property for a setup using LOGIN_FORM authentication but without success.

Here is an extract of the used configuration:
```
yamlApplicationConfig:
  auth:
    type: LOGIN_FORM

  spring:
    security:
      user:
        name: XXX
        password: XXX

  server:
    servlet:
      session:
        timeout: 28800
```

Is it supposed to be working with LOGIN_FORM authentication too or am I missing something here?

Thanks
