### DISCUSSION TITLE
How can i login with my azure ad user?

### DISCUSSION THREAD

**Discussion by vSivarajah93** [provectus/kafka-ui#4104] [Q&A] [answered]
Hi! 

I'd like to setup kafka-ui where it is possible to configure it with an azure ad backend. So configure it in a way where any user that is part of ad-group: "X" can login into the UI.

Is that possible? if yes, can i get a guide on how to.

**Comment by Haarolean** [comment, marked as answer]
[OAuth authentication](https://docs.kafka-ui.provectus.io/configuration/authentication/oauth2)
[LDAP/AD authentication](https://docs.kafka-ui.provectus.io/configuration/authentication/ldap-active-directory)

**Comment by waitspring** [comment]
```yaml
auth:
  type: "ldap"
spring:
  ldap:
    urls: "ldap://ldap.season.com:389"
    base: "dc=xxxxxx,dc=xxxxxx"
    admin-user: "cn=admin,dc=xxxxxx,dc=xxxxxx"
    admin-password: "xxxxxx"
    user-filter-search-base: "dc=xxxxxx,dc=xxxxxx"
    user-filter-search-filter: "(cn={0})"
```
