### DISCUSSION TITLE
Trouble matching Topics to Schema

### DISCUSSION THREAD

**Discussion by PabloLec** [provectus/kafka-ui#4113] [Q&A] [answered]
Hello,

I'm following up on a previously closed discussion, as I still haven't been able to resolve my issue.

I'm encountering an issue with Serde, which I believe is tied to the naming conventions of my Schema Registry. I've ensured that my schema registry is correctly configured within Kafka UI. It's visible on the left sidebar and is also listed under "Value Serde" on the topic screen. 
However, it's not functioning as expected. When I hover over it, I get a tooltip stating "Fallback serde was used", but there's no accompanying error message in the console.

It's worth noting that my topics don't utilize the TopicRecordNameStrategy, and changing this setup is not an option for me. 
To give a practical example, I have the topic "contract" paired with the subject "avrocontractevent". The naming convention I employ is "avro[TOPIC]event". I can confirm that my schemas are accurate and are actively utilized by various applications.

Here's my current configuration. I've tried setting the schemaNameTemplate at both the cluster and serde levels, but without any success:

```
kafka:
  clusters:
    -
      name: local
      bootstrapServers: kafka-broker:9092
      schemaRegistry: http://kafka-schema-registry:8081
      schemaRegistryKeySchemaNameTemplate: "avro%sevent"
      schemaRegistrySchemaNameTemplate: "avro%sevent"
      serde:
        -
          name: SchemaRegistry
          keySchemaNameTemplate: "avro%sevent"
          schemaNameTemplate: "avro%sevent"
```

Do you spot any missing configuration or have suggestions on what might be causing this issue? 
Is there perhaps a way to explicitly set the schema for individual topics? Since I manage a limited number of schemas and topics, this could be a feasible solution for me.

Thank you in advance for your help.

P.S. I've tested this on both the 'latest' and 'master' Docker images.
