### DISCUSSION TITLE
Login with OAuth 2.0 Invalid credential

### DISCUSSION THREAD

**Discussion by majma24** [provectus/kafka-ui#4118] [Q&A] [answered]
Hi all,
I try config oauth2 in kafka-ui using provider google. But when I try to login , I got error invalid credential
![image](https://github.com/provectus/kafka-ui/assets/53938061/3fe85a90-ec08-472d-9133-48fe551975c0)

this is my config
```
yamlApplicationConfig: 
      kafka:
        clusters:
          - name: shared-kafka-stg
            bootstrapServers: shared-kafka-gcp.preprod.blabla-internal.com:9092
      auth:
        type: OAUTH2
        oauth2:
          client:
            google:
              provider: google
              scope: openid
              clientId: xxxx.apps.googleusercontent.com
              clientSecret: xxxx
              redirect-uri: https://kafka-ui.preprod.blabla-internal.com/login/oauth2/code/google
              issuer-uri: https://accounts.google.com
              user-name-attribute: email
              custom-params:
                type: google
                allowedDomain: blabla.com # for RBAC
      management:
        health:
          ldap:
            enabled: false
```
Did I  miss configuration?

Thank you

**Comment by Haarolean** [comment]
Hi, since you're running in k8s, I recommend doing this:
https://docs.kafka-ui.provectus.io/faq/common-problems#urls-are-invalid-contain-ports-when-behind-a-reverse-proxy

If it doesn't help -- most likely something is misconfigured on google cloud dev console side.

**Reply by majma24** [reply]
where is this property added? in auth or kafka.cluster?

**Reply by Haarolean** [reply, marked as answer]
@majma24 neither: that's a top-level property.

```
server:
  forward-headers-strategy: FRAMEWORK

kafka:
  clusters:
     # ...
```
