### DISCUSSION TITLE
How to add configuration for SSL_TRUSTSTORE_LOCATION in Config.yml

### DISCUSSION THREAD

**Discussion by mvassli** [provectus/kafka-ui#4193] [Q&A] [answered]
I am trying to migrate all my env variables in docker-compose to a separate config.yml file. For the most part i am successfull with the exception of env KAFKA_CLUSTERS_0_SSL_TRUSTSTORE_LOCATION / PASSWORD

On startup AdminClientConfig logs both as null
```
ssl.truststore.location = null
ssl.truststore.password = null
```

**Docker compose:**
```
---
version: '2'
services:

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    network_mode: host
    ports:
      - 8080:8080
    environment:
      SPRING_CONFIG_ADDITIONAL-LOCATION: /config.yml
    volumes:
      - ./truststore.jks:/truststore.jks
      - ./config.yml:/config.yml
```

**Config.yml**

```
kafka:
  clusters:
     -
      name: cluster1
      bootstrapServers: REDACTED:9092,REDACTED:9092,REDACTED:9092,REDACTED:9092
      schemaRegistry: https://REDACTED
      properties:
        security:
          protocol: SASL_SSL
        sasl:
          jaas:
            config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="REDACTED" password="REDACTED";'
          mechanism: SCRAM-SHA-512
      ssl:
        truststore:
          location: /truststore.jks
          password: 'REDACTED'
      schemaregistryssl:
        truststorelocation: /truststore.jks
        truststorepassword: 'REDACTED'
```
I have also tried without the forward slash infront of filename. How do correctly configure ssl truststore?

**Comment by Haarolean** [comment, marked as answer]
Hi! Sorry that it's not obvious, I believe the yaml format for these properties is not present anywhere in our docs atm.

This should look like this:
```
kafka:
  clusters:
    - name: local
      ssl:
        truststore-location: /xxx/xxx
        truststore-password: 123
      schema-registry-ssl:
        keystore-location: /xxx
        keystore-password: 123
```
Feel free to raise any PRs to [our docs](https://github.com/provectus/kafka-ui-docs) if you have something to add!
