### DISCUSSION TITLE
How to Use Kafka-UI set LDAP and RBAC with Docker-Compose.yml

### DISCUSSION THREAD

**Discussion by akameclark77** [provectus/kafka-ui#4273] [Q&A]
This is my yml file:
please help login via LDAP error, thanks

```
version: '2'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "8081:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-1
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=
      - KAFKA_CLUSTERS_0_ZOOKEEPER=
#----------------------------------------------------------------------------------------------------------------------------------
      - KAFKA_CLUSTERS_1_NAME=kafka-2
      - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=
      - KAFKA_CLUSTERS_1_ZOOKEEPER=1
#----------------------------------------------------------------------------------------------------------------------------------
      - AUTH_TYPE=LDAP
      - SERVER_SERVLET_CONTEXT_PATH=/
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin
      - SPRING_LDAP_URL=ldap://ldap:8389
      - SPRING_LDAP_BASE=dc=good,dc=com

  openldap:
    container_name: openldap
    image: osixia/openldap:latest
    ports:
      - "8389:389"
      - "8636:636"
    environment:
      - LDAP_DOMAIN=good.com
      - LDAP_ADMIN_PASSWORD=admin
    volumes:
      - ~/ldap/backup:/data/backup
      - ~/ldap/data:/var/lib/openldap
      - ~/ldap/config:/etc/openldap/slapd.d
      - ~/ldap/certs:/assets/slapd/certs
    command: [--copy-service,  --loglevel, debug]

  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: phpldapadmin
    ports:
      - "8085:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_LDAP_BASEDN=dc=good,dc=com
      - PHPLDAPADMIN_LDAP_ADMIN_PASSWORD=admin
      - PHPLDAPADMIN_HTTPS="false"
    depends_on:
      - openlda
```
