### DISCUSSION TITLE
error 302 with basic-auth

### DISCUSSION THREAD

**Discussion by ledoc** [provectus/kafka-ui#4319] [Q&A]
Hi, I've installed kafka-ui with Helm
The connection works fine without authentication
but as soon as I set basic-auth authentication via ingress or port-forward, the login form is displayed but the POST request with credentials returns a 302 error :(

Here's my configuration:

Ingress in Helm's values file:
```
...
ingress:
  enabled: true
  annotations: {}
  ingressClassName: "nginx230"
  path: "/"
  pathType: "Prefix"  
  host: "kafka-ui-example.priv"
```

configmap:
```
data:

  KAFKA_CLUSTERS_0_NAME: "$KAFKA_CLUSTER_NAME"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka/kafka-cluster-kafka-bootstrap:9093"
  AUTH_TYPE: "LOGIN_FORM"
  MANAGEMENT_HEALTH_LDAP_ENABLED: "FALSE" 
  DYNAMIC_CONFIG_ENABLED: "true"
```

the secret:
```
type: Opaque
data:
 KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: $B64_TRUSTORE_PASSWORD
 KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: $B64_KEYSTORE_PASSWORD
 SPRING_SECURITY_USER_NAME: b64_user
 SPRING_SECURITY_USER_PASSWORD: b64_password
```

I don't see the problem, it must be something stupid.

thanks in advance
