### DISCUSSION TITLE
Run oauth2 locally

### DISCUSSION THREAD

**Discussion by marcosschroh** [provectus/kafka-ui#4414] [Q&A]
I am using `kafka-ui` with `docker-compose` and I want to test `oauth2` locally. The authentication server is running in my host machine but NOT inside a container.

Authentication server for oauth2: `localhost:9090`
kafka-ui: docker-compose with exposes the port `8080`

I can initiate the `oauth2` flow properly but when `kafka-ui` tries to hit the endpoint `Request to POST http://localhost:9090/openid/token/` I get `"finishConnect(..) failed: Connection refused` which makes sense because it is trying to hit itself rather than going out the container. Do you have any ideas how can I bypass this issue? I tried to use `extra_hosts: - host.docker.internal:host-gateway` but it did not work.

```yaml
version: '3.4'
services:
  kafka-ui:
    container_name: kafka-ui
    extra_hosts:
      - host.docker.internal:host-gateway
    image: provectuslabs/kafka-ui:v0.7.1
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-non-prod
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: ./ssl/keystore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: a-pass
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: b-1.mskcluster...:9094
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: '' # DISABLE COMMON NAME VERIFICATION
      SPRING_CONFIG_ADDITIONAL-LOCATION: config.yaml
    volumes:
      - ./ssl/non-prod/keystore.jks:/ssl/keystore.jks
      - ./config.yaml:/config.yaml
```

Thanks!!
