### DISCUSSION TITLE
RBAC for SSO Azure provider

### DISCUSSION THREAD

**Discussion by dimashenkov** [provectus/kafka-ui#4431] [General]
Is this the way to have Azure SSO RBAC ? I'v tried it but its not working.
https://github.com/provectus/kafka-ui/discussions/3814#discussioncomment-5936440
My looks like this in Helm chart values.yaml
```
yamlApplicationConfig:

  auth:
      type: OAUTH2
      oauth2:
        client:
          azure:
            provider: azure
            clientId: ******
            clientSecret: ******
            scope: "openid"
            clientName: "azure"
            redirect-uri: https://kafka-ui.dev.product.frankfurt.bla.cloud/login/oauth2/code/azure
            issuerUri: "https://login.microsoftonline.com/*******/v2.0"
            user-name-attribute: name
             custom-params:
               type: oauth #must be 'oauth'
               roles-field: roles # roles claim contains all granted roles for a user
    
  rbac:
    roles:
      - name: "admin"
        clusters:
          - kafka-cluster-dev
        subjects:
          - provider: oauth  # Added your Azure provider
            type: user
            value: "Sam@bla.org"  # Your email as admin        
          - provider: oauth  # Added your Azure provider
            type: user
            value: "Jhon@bla.org"  # Your email as admin
        permissions:
          - resource: clusterconfig
            actions: all
          - resource: topic
            value: ".*"
            actions: [ "view", "create", "edit", "delete", "messages_produce" ]
          - resource: consumer
            value: ".*"
            actions: all
          - resource: schema
            value: ".*"
            actions: all
          - resource: connect
            value: ".*"
            actions: all
          - resource: ksql
            actions: all
      - name: "readonly"
        clusters:
          - kafka-cluster-dev
        subjects:
          - provider: oauth
            type: domain
            value: "gostudent.org"
        permissions:
          - resource: clusterconfig
            actions: [ "view" ]
          - resource: topic
            value: ".*"
            actions: [ "view" ]
          - resource: consumer
            value: ".*"
            actions: [ "view" ]
          - resource: schema
            value: ".*"
            actions: [ "view" ]
          - resource: connect
            value: ".*"
            actions: [ "view" ]
```
