### DISCUSSION TITLE
Config file properties format

### DISCUSSION THREAD

**Discussion by SunSparc** [provectus/kafka-ui#4499] [General]
What is the correct format for properties in the config file?

For example, the documentation indicates that the "bootstrap servers" can be specified as an environment variable like this:
```
KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS = "localhost:9092"
```
And in the config file like this:
```
kafka:
  clusters:
    - name: local
      bootstrapServers: localhost:9092
```
However, the logs show the property like this:
```
bootstrap.servers = [localhost:9092]
```
Which is typically converted to YAML like this:
```
kafka:
  clusters:
    - name: local
       bootstrap:
         servers: localhost:9092
```
Specifying the bootstrap property like that causes a fatal error.

Even the [suggested](https://docs.kafka-ui.provectus.io/configuration/configuration-file) [translation tool](https://env.simplestep.ca/) produces config values that do not work.

The documentation says:
> "We strongly recommend using YAML in favor of env variables for the most part of the config."

Sadly, most of the examples only show environment variables or limited config file properties using unconventional YAML formatting.

What is the correct format for properties in the config file? And is there an example of a full config file somewhere?
