### DISCUSSION TITLE
Installing kafka and kafka-ui on docker

### DISCUSSION THREAD

**Discussion by mdelambilly** [provectus/kafka-ui#4525] [Q&A]
Hello,

I use this compose file to locally run kafka in docker:
```
services:
  kafka-broker:
    network_mode: bridge
    container_name: kafka-broker
    image: apache/kafka:latest
    ports:
      - 9092:9092
    restart: unless-stopped
```
It works just fine, client can connect to the queue put and read event.

I would like to install a kafka UI to see then event queue. I tried to add the following to the compose file:
```
  kafka-ui:
    network_mode: bridge
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka-broker
    environment:
      DYNAMIC_CONFIG_ENABLED: true
```
but I fail to make the UI connect to the broker.

Any idea ?
