### DISCUSSION TITLE
how to enable JumpCloud SSO with kafka-ui using Oauth2

### DISCUSSION THREAD

**Discussion by vagharsh** [provectus/kafka-ui#4527] [Q&A]
i have tested almost all variants of configuration in kafka-ui and i am getting invalid credentials . 
this is my current helm values.
```
yamlApplicationConfig:
  kafka:
    clusters:
      - name: dev
        bootstrapServers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  auth:
    type: OAUTH2
    oauth2:
      client:
        jumpcloud:
          clientId: XXXXXX
          clientSecret: XXXXXX
          scope:
            - email
            - openid
            - groups
          provider: jumpcloud
          client-name: jumpcloud
          issuer-uri: https://oauth.id.jumpcloud.com/
          redirect-uri: https://localhost:8080/login/oauth2/code/jumpcloud
          authorization-grant-type: authorization_code
          jwk-set-uri: https://oauth.id.jumpcloud.com/.well-known/jwks.json
          user-name-attribute: email
          custom-params:
            type: oauth
            roles-field: groups
  
  rbac:
    roles:
      - name: "admins"
        clusters:
          - dev
        subjects:
          - provider: oauth
            type: group
            value: "groups"
        permissions:
          - resource: applicationconfig
            actions: all

          - resource: clusterconfig
            actions: all

          - resource: topic
            value: ".*"
            actions: all

          - resource: consumer
            value: ".*"
            actions: all

          - resource: schema
            value: ".*"
            actions: all

          - resource: connect
            value: ".*"
            actions: all

          - resource: ksql
            actions: all

          - resource: acl
            actions: [ view, edit ]
  management:
    health:
      ldap:
        enabled: false

env:
  - name: JAVA_OPTS
    value: '-Dlogging.level.root=DEBUG'

```
