### DISCUSSION TITLE
example config.yml for jar run

### DISCUSSION THREAD

**Discussion by xiaobao623** [provectus/kafka-ui#4533] [General]
我做了一个jar run方式的相对复杂并且常用的配置示例，本地测试通过，分享一下供参考
1. 包括2个不同版本的kafka集群，kafka-v3.5使用Kraft模式（zk-less），kafka-v2.7使用zookeeper模式
2. 开启kafka-ui基本登录认证 用户名、密码方式
3. kafka-v3.5开启了 sasl plaintext认证，开启jmx，但是没有开启jmx认证，
4. kafka-v2.7没有开启sasl认证，开启jmx并且开启了jmx 认证

vim config.yml 
```
kafka:
  clusters:
    - name: kafka_v3.5_sasl
      bootstrapServers: 192.168.36.231:9092;192.168.36.232:9092;192.168.36.233:9092
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="Pass2024";
      metrics:
        port: 9997
        type: JMX

    - name: kafka_v2.7
      bootstrapServers: 192.168.36.184:9092;192.168.36.185:9092;192.168.36.186:9092
      metrics:
        port: 9992
        type: JMX
        username: kafmon
        password: Pass2023

auth:
  type: login_form
  
spring:
  security:
     user:
       name: admin
       password: pass2025
```
