### ISSUE TITLE
Image registry is missing in k8s deployment files

### ISSUE THREAD

**Issue by moritzluedtke** [provectus/kafka-ui#1215]
**Describe the bug**
When using custom private registrys the Helm chart doesn't consider the image registry input.

**Steps to Reproduce**

1. Add the following (as an example) in the `values.yml` file:
  ```
  image:
    registry: YOUR_REGISTRY
    repository: kafka-ui
    tag: 0.2.1
  ```
2. Deploy the helm chart to your cluster.
2. The deployment file is missing the registry in the image name.

**Expected behavior**
The image registry should be added to the image name in the k8s `deployment.yml`.

**Fix**
In the template file `deployment.yaml` replace the line for `containers.image` with the following:

```
image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
```
