### ISSUE TITLE
Liveness and Readiness probes failing

### ISSUE THREAD

**Issue by nandacamargo** [provectus/kafka-ui#1329]
Hello!

First of all, congrats to you all, kafka-ui is such a nice project!

We wrote a Helm Chart to deploy Kafka UI in a Kubernetes cluster, using version 0.3.0. 
We are facing the following issue when using liveness and readiness probes in the k8s deployment:
`Readiness probe failed: HTTP probe failed with statuscode: 404`

Even using different paths like `/actuator/health`, `/actuator/info` and `login` that are declared [here](https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/AbstractAuthSecurityConfig.java) the probes are failing. Also, we checked the Helm Chart [deployment](https://github.com/provectus/kafka-ui/blob/master/charts/kafka-ui/templates/deployment.yaml#L54-L73) you provided.

**Set up**
- Kafka UI - Version: 0.3.0
- Docker image: provectuslabs/kafka-ui:0.3.0
- The Helm Chart applied in the cluster has the following liveness and readiness probes:

```
ports:
   - name: view
     containerPort: 8080
     protocol: TCP
livenessProbe:
  httpGet:
    path: /actuator/health
    port: view
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
readinessProbe:
  httpGet:
    path: /actuator/health
    port: view
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
```

Removing the probes, it is possible to use Kafka UI normally in an integration environment in Kubernetes cluster, but we really need the probes before deploying in production.

Thanks a lot!
