### ISSUE TITLE
Use kafka-ui to connect multi brokers in high version

### ISSUE THREAD

**Issue by sakaman** [provectus/kafka-ui#1355]
#### Problem Description

kafka-ui client refuses to connect hosts of other brokers when connects to multi kafka brokers in confluentinc/cp-kafka:7.0.1, and there is the same problem in 6.x.x but it's ok in 5.x.x.

#### Docker-compose file

```yaml
---
version: '2'
services:

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9000:8080
    depends_on:
      - zookeeper0
      - kafka0
      - kafka01
      - kafka02
      - schemaregistry0
      - kafka-connect0
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper0:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8085
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083

  zookeeper0:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka0:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper0
    ports:
      - 9092:9092
      - 9997:9997
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0  -Dcom.sun.management.jmxremote.rmi.port=9997

  kafka01:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper0
    ports:
      - 9094:9094
      - 9991:9991
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka01:29092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      JMX_PORT: 9991
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka01  -Dcom.sun.management.jmxremote.rmi.port=9991

  kafka02:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper0
    ports:
      - 9095:9095
      - 9992:9992
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka02:29092,PLAINTEXT_HOST://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      JMX_PORT: 9992
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka02  -Dcom.sun.management.jmxremote.rmi.port=9992

  schemaregistry0:
    image: confluentinc/cp-schema-registry:7.0.1
    ports:
      - 8085:8085
    depends_on:
      - zookeeper0
      - kafka0
      - kafka01
      - kafka02
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka0:29092,PLAINTEXT://kafka01:29092,PLAINTEXT://kafka02:29092
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper0:2181
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry0
      SCHEMA_REGISTRY_LISTENERS: http://schemaregistry0:8085

      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "http"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas

  kafka-connect0:
    image: confluentinc/cp-kafka-connect:7.0.1
    ports:
      - 8083:8083
    depends_on:
      - kafka0
      - kafka01
      - kafka02
      - schemaregistry0
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka0:29092
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: _connect_configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: _connect_offset
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: _connect_status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schemaregistry0:8085
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schemaregistry0:8085
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect0
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
```

#### Exception

```txt
kafka-ui           | 2022-01-06 04:34:30,122 ERROR [kafka-admin-client-thread | adminclient-1] c.p.k.u.u.JmxClusterUtil: Cannot get JMX connector for the pool due to:
kafka-ui           | java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: kafka01; nested exception is:
kafka-ui           |    java.net.ConnectException: Connection refused]
kafka-ui           |    at java.management.rmi/javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:370)
kafka-ui           |    at java.management/javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
kafka-ui           |    at com.provectus.kafka.ui.util.JmxPoolFactory.create(JmxPoolFactory.java:31)
kafka-ui           |    at com.provectus.kafka.ui.util.JmxPoolFactory.create(JmxPoolFactory.java:17)
kafka-ui           |    at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62)
kafka-ui           |    at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1012)
kafka-ui           |    at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356)
kafka-ui           |    at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:277)
kafka-ui           |    at com.provectus.kafka.ui.util.JmxClusterUtil.getJmxMetrics(JmxClusterUtil.java:99)
kafka-ui           |    at com.provectus.kafka.ui.util.JmxClusterUtil.lambda$getJmxMetric$3(JmxClusterUtil.java:82)
kafka-ui           |    at java.base/java.util.Optional.map(Optional.java:258)
kafka-ui           |    at com.provectus.kafka.ui.util.JmxClusterUtil.getJmxMetric(JmxClusterUtil.java:82)
kafka-ui           |    at com.provectus.kafka.ui.util.JmxClusterUtil.lambda$getBrokerMetrics$0(JmxClusterUtil.java:73)
kafka-ui           |    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
kafka-ui           |    at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:340)
kafka-ui           |    at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:227)
kafka-ui           |    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)
kafka-ui           |    at reactor.core.publisher.MonoCollect$CollectSubscriber.onSubscribe(MonoCollect.java:103)
kafka-ui           |    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
kafka-ui           |    at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
kafka-ui           |    at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
kafka-ui           |    at reactor.core.publisher.Mono.subscribe(Mono.java:4399)
kafka-ui           |    at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128)
kafka-ui           |    at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
kafka-ui           |    at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:165)
kafka-ui           |    at com.provectus.kafka.ui.service.ReactiveAdminClient.lambda$describeCluster$18(ReactiveAdminClient.java:223)
kafka-ui           |    at org.apache.kafka.common.internals.KafkaFutureImpl$WhenCompleteBiConsumer.accept(KafkaFutureImpl.java:177)
kafka-ui           |    at org.apache.kafka.common.internals.KafkaFutureImpl$WhenCompleteBiConsumer.accept(KafkaFutureImpl.java:162)
kafka-ui           |    at org.apache.kafka.common.internals.KafkaFutureImpl.complete(KafkaFutureImpl.java:221)
kafka-ui           |    at org.apache.kafka.common.KafkaFuture$AllOfAdapter.maybeComplete(KafkaFuture.java:82)
kafka-ui           |    at org.apache.kafka.common.KafkaFuture$AllOfAdapter.accept(KafkaFuture.java:76)
kafka-ui           |    at org.apache.kafka.common.KafkaFuture$AllOfAdapter.accept(KafkaFuture.java:57)
kafka-ui           |    at org.apache.kafka.common.internals.KafkaFutureImpl.complete(KafkaFutureImpl.java:221)
kafka-ui           |    at org.apache.kafka.clients.admin.KafkaAdminClient$5.handleResponse(KafkaAdminClient.java:1875)
kafka-ui           |    at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.handleResponses(KafkaAdminClient.java:1189)
kafka-ui           |    at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1341)
kafka-ui           |    at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1264)
kafka-ui           |    at java.base/java.lang.Thread.run(Thread.java:830)
kafka-ui           | Caused by: javax.naming.ServiceUnavailableException: null
kafka-ui           |    at jdk.naming.rmi/com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:137)
kafka-ui           |    at java.naming/com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:207)
kafka-ui           |    at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
kafka-ui           |    at java.management.rmi/javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1839)
kafka-ui           |    at java.management.rmi/javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1813)
kafka-ui           |    at java.management.rmi/javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:302)
kafka-ui           |    ... 37 common frames omitted
kafka-ui           | Caused by: java.rmi.ConnectException: Connection refused to host: kafka01; nested exception is:
kafka-ui           |    java.net.ConnectException: Connection refused
kafka-ui           |    at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
kafka-ui           |    at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
kafka-ui           |    at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
kafka-ui           |    at java.rmi/sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
kafka-ui           |    at java.rmi/sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
kafka-ui           |    at jdk.naming.rmi/com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:133)
kafka-ui           |    ... 42 common frames omitted
kafka-ui           | Caused by: java.net.ConnectException: Connection refused
kafka-ui           |    at java.base/sun.nio.ch.Net.connect0(Native Method)
kafka-ui           |    at java.base/sun.nio.ch.Net.connect(Net.java:493)
kafka-ui           |    at java.base/sun.nio.ch.Net.connect(Net.java:482)
kafka-ui           |    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
kafka-ui           |    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339)
kafka-ui           |    at java.base/java.net.Socket.connect(Socket.java:603)
kafka-ui           |    at java.base/java.net.Socket.connect(Socket.java:552)
kafka-ui           |    at java.base/java.net.Socket.<init>(Socket.java:475)
kafka-ui           |    at java.base/java.net.Socket.<init>(Socket.java:249)
kafka-ui           |    at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40)
kafka-ui           |    at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
kafka-ui           |    ... 47 common frames omitted
```
