### ISSUE TITLE
Producing Message doesnt encode the message

### ISSUE THREAD

**Issue by TestCK** [provectus/kafka-ui#1356]
**Describe the bug**
(A clear and concise description of what the bug is.)
I have setup json schema for my topics but from UI when I produce message, messages are not encoded using the schema, hence in consumer when i try to decode it back I am getting the following error 
"ConfluentSchemaRegistryArgumentError: Message encoded with magic byte"

**Set up**
(How do you run the app? 
Which version of the app are you running? Provide either docker image version or check commit hash at the top left corner. We won't be able to help you without this information.)
Tried both the latest as well as v0.2.0

**Steps to Reproduce**

1. Have JSON schema registry setup for the topics
2. Produce message from UI
3. When the messages are consumed they are not encoded using the schema

**Expected behavior**
(A clear and concise description of what you expected to happen)
Produce message should be encoded as the per schema configured

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
(Add any other context about the problem here)

**Comment by Haarolean** [comment]
Hi, thanks for reaching out (and checking the bug with the older version :) )

We'll take a look into this.

**Comment by iliax** [comment]
Hi @TestCK. Do you provide schemaRegistry url to kafka-ui (KAFKA_CLUSTERS_0_SCHEMAREGISTRY property)?

**Comment by TestCK** [comment]
Hi @iliax , below is my docker-compose yml and i can see all my schemas in schema registry section

```

zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_TICK_TIME: '2000'

  kafka:
    image: confluentinc/cp-server:7.0.1
    hostname: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
      - 9101:9101
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # KAFKA_ADVERTISED_HOST_NAME: 'broker'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENERS: 'PLAINTEXT://:29092,PLAINTEXT_HOST://:9092'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-ui:
    image: provectuslabs/kafka-ui:0.2.0
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: https://schema-registry
      KAFKA_CLUSTERS_0_SCHEMAREGISTRYAUTH_USERNAME: tempUser
      KAFKA_CLUSTERS_0_SCHEMAREGISTRYAUTH_PASSWORD: tempPass
```
