### ISSUE TITLE
Failed to collect cluster Default info java.lang.IllegalStateException: Error while creating AdminClient for Cluster Default

### ISSUE THREAD

**Issue by gulsenkeskin** [provectus/kafka-ui#1380]
**I would like to use network_mode: bridge for kafka for being able to reach kafka through localhost:9092 from another service** 

I'm trying to use the provectus/kafka-ui but when I open the consumers menu I get the following error

![image](https://user-images.githubusercontent.com/63197899/149308168-4a68451c-b451-4347-8cde-d8a604100650.png)

**my docker-compose.yml file :**

      kafka-ui:
        container_name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
          - 8080:8080
        depends_on:
          - kafka
        environment:
          KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
          KAFKA_CLUSTERS_0_JMXPORT: 9997

      kafka:
        image: johnnypark/kafka-zookeeper
        ports:
          - "2181:2181"
          - "9092:9092"
        network_mode: bridge
        environment:
          ADVERTISED_HOST: 127.0.0.1
          NUM_PARTITIONS: 1
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

**log error:**

2022-01-13 09:16:50,014 ERROR [parallel-5] c.p.k.u.s.MetricsService: Failed to collect cluster Default info

java.lang.IllegalStateException: Error while creating AdminClient for Cluster Default

![image](https://user-images.githubusercontent.com/63197899/149308301-ab475baf-071f-4e0a-82be-31a37afc79c8.png)

**Comment by gulsenkeskin** [comment]
Failed to collect cluster Default info java.lang.IllegalStateException: Error while creating AdminClient for Cluster Default

**Comment by Haarolean** [comment]
Hi, thanks for reaching out.

In this case you could connect to kafka via docker internal host. You can find an example here: https://github.com/provectus/kafka-ui/discussions/1081

**Comment by gulsenkeskin** [comment]
Hi Thank you for your answer.
Now I'm getting this error: ERROR: The Compose file '.\docker-compose.yml' is invalid because:
services.kafka-ui.extra_hosts contains an invalid type, it should be an object, or an array

**Comment by Haarolean** [comment]
Please share your current file

**Comment by gulsenkeskin** [comment]
```services:
  kafka-ui:
    extra_hosts: host.docker.internal:host-gateway
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: kafka:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997

  kafka:
    image: johnnypark/kafka-zookeeper
    ports:
      - "2181:2181"
      - "9092:9092"
    network_mode: bridge
    environment:
      ADVERTISED_HOST: 127.0.0.1
      NUM_PARTITIONS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock```

**Comment by Haarolean** [comment]
This is indeed has to be an array while it is not.

```
  kafka-ui:
    extra_hosts:
      - host.docker.internal:host-gateway
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: kafka:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997

  kafka:
    image: johnnypark/kafka-zookeeper
    ports:
      - "2181:2181"
      - "9092:9092"
    network_mode: bridge
    environment:
      ADVERTISED_HOST: 127.0.0.1
      NUM_PARTITIONS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by gulsenkeskin** [comment]
Now I'm getting this error: 

ERROR: yaml.parser.ParserError: while parsing a block mapping
  in ".\docker-compose.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in ".\docker-compose.yml", line 18, column 3

**Comment by Haarolean** [comment]
You're missing a `version` and `services` entries.
Use [this file](https://github.com/provectus/kafka-ui/blob/master/docker/kafka-ui.yaml) as an example.

**Comment by gulsenkeskin** [comment]
i still get this error :( :
 ERROR [parallel-1] c.p.k.u.s.MetricsService: Failed to collect cluster Default info

java.lang.IllegalStateException: Error while creating AdminClient for Cluster Default

**Comment by Haarolean** [comment]
Guess you still haven't altered the advertised host as described in https://github.com/provectus/kafka-ui/discussions/1081.
Your kafka is being advertised on localhost only, which is invalid, you have to change it to your hostname's IP address.

**Comment by gulsenkeskin** [comment]
I changed the docker-compose.yml file as follows but I still get the same error
```
kafka-ui:
    extra_hosts:
      - host.docker.internal:host-gateway
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: kafka:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997

  kafka:
    image: johnnypark/kafka-zookeeper
    ports:
      - "2181:2181"
      - "9092:9092"
    network_mode: bridge
    environment:
      ADVERTISED_HOST: host.docker.internal
      ADVERTISED_PORT: 9092
      NUM_PARTITIONS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

ERROR [parallel-1] c.p.k.u.s.MetricsService: Failed to collect cluster Default info

java.lang.IllegalStateException: Error while creating AdminClient for Cluster Default
