### ISSUE TITLE
KRaft mode support (zookeeper less kafka)

### ISSUE THREAD

**Issue by teng1** [provectus/kafka-ui#1449]
### Is your proposal related to a problem?

Hi,
I have a KRaft enabled kafka 3.0.0 cluster running in K8s using a very similar setup to the following https://debezium.io/blog/2021/08/31/going-zookeeperless-with-debezium-container-image-for-apache-kafka/

I deployed the Kafka UI as a separate service, i'm able to access the cluster and view Brokers but not able to create topics and it seems like its not supported due to expecting zookeeper, would be great if support could be included for the new zookeeperless mode

### Describe the solution you'd like

Support within application.yml file for KRaft enabled clusters
Thanks!

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.

We'll take this into consideration for future releases.

Related: #1076

**Comment by pikhovkin** [comment]
@teng1 try this config
```yaml
    # ...
    environment:
        KAFKA_CLUSTERS_0_NAME: "local"
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:19092" # or "broker:19092"
        # KAFKA_CLUSTERS_0_ZOOKEEPER: "zoo1:2181" <==== comment this
    # ...
```
