### ISSUE TITLE
Avro messages are not shown correctly

### ISSUE THREAD

**Issue by jaehyeon-kim** [provectus/kafka-ui#1621]
**Describe the bug**

Avro messages are not shown correctly.

**Set up**

Use `provectuslabs/kafka-ui:0.3.3` image. Use Apicurio registry as schema registry with the version that's compatible with Confluent schema registry - `registry:8080/apis/ccompat/v6`

```
version: "2"

services:
   ...
  kafka-ui:
    image: provectuslabs/kafka-ui:0.3.3
    container_name: kafka-ui
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: registry:8080/apis/ccompat/v6
    depends_on:
      - zookeeper
      - kafka
  ...
  registry:
    image: apicurio/apicurio-registry-mem:2.2.0.Final
    container_name: registry
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka
      - postgres
```

**Steps to Reproduce**

1. Run docker compose
2. Create Debezium connector with AvroConverter

```
curl -i -X POST -H "Accept:application/json" -H  "Content-Type:application/json" \
  http://localhost:8083/connectors/ \
  -d '{
        "name": "orders",
        "config": {
          "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
          "tasks.max": "1",
          "database.hostname": "postgres",
          "database.port": "5432",
          "database.user": "user",
          "database.password": "pass",
          "database.dbname": "db",
          "database.server.name": "local",
          "schema.include": "ods",
          "table.include.list": "ods.tbl",
          "key.converter": "io.confluent.connect.avro.AvroConverter",
          "key.converter.schema.registry.url": "http://registry:8080/apis/ccompat/v6",
          "value.converter": "io.confluent.connect.avro.AvroConverter",
          "value.converter.schema.registry.url": "http://registry:8080/apis/ccompat/v6"
        }
  }'
```

**Expected behavior**

The message (both key and content) should be displayed correctly.

**Screenshots**

Records are not displayed correctly.

![image](https://user-images.githubusercontent.com/1023748/154471727-bde454e4-00ec-48c8-b855-1936dcfb4f26.png)

Schemas are rendered correctly.

![image](https://user-images.githubusercontent.com/1023748/154472586-6d4963e3-54bd-45bb-92c3-8d6254531480.png)

**Additional context**
