### ISSUE TITLE
EKS with ingress controller

### ISSUE THREAD

**Issue by David-hod** [provectus/kafka-ui#1657]
page is not loading with message to 'You need to enable JavaScript to run this app'.
We are running on EKS with ingress nginx controller. we use terraform for deployment. 
the ingress is used by many services and we want to keep only one, we dont want to create dedicated ingress for kafka-ui with an ALB behind it.
we can't allocate the root path because it is reserved for our frontend. 

we also tried using: 
SERVER_SERVLET_CONTEXT_PATH: /kafka-ui
which didnt worked. 

 how can we add kafka ui to an existinng nginx controller? did we missed something? is it a bug?

**Comment by 5hin0bi** [comment]
Hi @David-hod , thank you for opening the issue!

Is it possible you could provide us with the values.yaml file (or terraform helm package parameters) that were used in your case?

Ingress part that is responsible for the Kafka-ui service targeting might be also useful to help you with the problem.

**Comment by David-hod** [comment]
```
source "kubernetes_ingress" "nginx" {
  lifecycle {
    ignore_changes = [
      metadata[0].annotations["field.cattle.io/publicEndpoints"],
    ]
  }

  metadata {
    name      = "xxxxxx"
    namespace = kubernetes_namespace.customer.metadata[0].name

    annotations = {
      "field.cattle.io/publicEndpoints"              = "placeholder"
      "kubernetes.io/ingress.class"                  = "nginx"
      "nginx.ingress.kubernetes.io/service-upstream" = "true"
      "nginx.ingress.kubernetes.io/rewrite-target"   = "/$2"
      "nginx.ingress.kubernetes.io/proxy-body-size"  = "100m"
    }
  }

  spec {
    rule {
      host = local.fqdn

      http {
      

        dynamic "path" {
          for_each = local.dev_mode ? toset([1]) : toset([])
          content {
            path = "/kafka-connect(/|$)(.*)"
            backend {
              service_name = "kafka-connect"
              service_port = "8080"
            }
          }
        }

        dynamic "path" {
          for_each = local.dev_mode ? toset([1]) : toset([])
          content {
            path = "/kafka-ui(/|$)(.*)"
            backend {
              service_name = "kafka-ui"
              service_port = "80"
            }
          }
        }

        path {
          path = "/($)?(.*)"
          backend {
            service_name = "frontend"
            service_port = "8080"
          }
        }
      }
    }
  }
}
```

**Comment by 5hin0bi** [comment]
Hi @David-hod thank you for providing the ingress information.

Running the command with the ingress enabled:
` helm template kafka-ui/charts/kafka-ui -f kafka-ui/charts/kafka-ui/values.yaml --name-template test`

The next service and ingress were created:

```
apiVersion: v1
kind: Service
metadata:
  name: test-kafka-ui
  labels:
    helm.sh/chart: kafka-ui-0.0.3
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: test
```

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-kafka-ui
  labels:
    helm.sh/chart: kafka-ui-0.0.3
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: test-kafka-ui
                port:
                  number: 80
            pathType: Prefix
            path: /kafka-ui
```

You will definitely need to provide the `SERVER_SERVLET_CONTEXT_PATH: /kafka-ui` env var.

Comparing to your ingress, the service name passed is kafka-ui, however, the helm chart uses **RELEASE-NAME-kafka-ui** template to set the name for the service. Is it possible you could have missed it and set incorrect service name?

All other configurations seem good to go.
