### ISSUE TITLE
avro deserializer used to read Long key

### ISSUE THREAD

**Issue by ngmip** [provectus/kafka-ui#1709]
**Describe the bug**

A topic for which the key is a `long` and the value is an avro serialized object is not properly rendered : the key appears as unreadable characters.

**Set up**
version 38c4cf7
docker-compose file :
```
version: '3.7'
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:      
      KAFKA_CLUSTERS_0_NAME: EU
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker-01:9092, broker-02:9092, broker-03:9092, broker-04:9092, broker-05:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zk-01:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: schemareg-01:8081
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: kafka-connect-01:8083
```

**Steps to Reproduce**

1. navigate to topic messages page (/ui/clusters/[cluster]/topics/[topic]/messages)

**Expected behavior**

messages are listed with their key and value shown as properly deserialized

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3017632/157074742-bcb69659-5c17-43ec-ab1d-cb67c91f2496.png)

same topic from another tool (whitch has become too expensive for us hens we are trying Kafka-ui)
![image](https://user-images.githubusercontent.com/3017632/157075845-b47b9457-0a16-4433-8486-481dd29af5a5.png)

I don't know how Kafka-UI choses what deserializer it will use for the Key/Value but I bet that the bug lies there. This other tool we used so far asks the user to pick the deserializers (and later remebers them) which is why il derserializes the key and values properly I guess.
