### ISSUE TITLE
Blank page with ALB Ingress

### ISSUE THREAD

**Issue by mattia-crypto** [provectus/kafka-ui#1714]
**Describe the bug**

I have finally setup my kafka-ui and exposed it via an ingress of type Application Load Balancer in AWS.

Whenever I hit the URL of the application load balancer in my browser, I simply get a blank page. I do have JS enabled in my browser, so not sure why this occurs. 

I found this strange, so I tried to `curl`.

My output is the following:

```
❯ curl  kafka-ui-*.elb.amazonaws.com

<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="./favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="apple-touch-icon" href="./logo192.png"/><link rel="manifest" href="./manifest.json"/><title>UI for Apache Kafka</title><script type="text/javascript">window.basePath=""</script><script defer="defer" src="/static/js/main.897d3b16.js"></script><link href="/static/css/main.6b53eac5.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>% 

```

You can see the last section:  

```
<noscript>You need to enable JavaScript to run this app.</noscript>
```

Which to me seems like it is unable to load the JS code required for the frontend.

Any idea what this could be due to?

**Set up**

I use `helmfile` to deploy my applications into an EKS cluster. 

My `helmfile.yaml` kafka-ui release looks like this (excluding envs):

```
- name: kafka-ui
    chart: kafka-ui/kafka-ui
    installed: true
    namespace: kafka
    values:
      - service:
          type: ClusterIP
          port: 8080
      - ingress:
          enabled: true
          ingressClassName: alb
          annotations:
            alb.ingress.kubernetes.io/load-balancer-name: "kafka-ui"
            alb.ingress.kubernetes.io/scheme: "internet-facing"
            alb.ingress.kubernetes.io/target-type: "ip"
          tls:
            enabled: false
```

This will create the following ingress:

```
❯ k get ingress -n kafka
NAME       CLASS   HOSTS   ADDRESS                                          PORTS   AGE
kafka-ui   alb     *       kafka-ui-*.elb.amazonaws.com                   80           70m
```

The `Ingress`: 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ui
  labels:
    helm.sh/chart: kafka-ui-0.3.3
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: kafka-ui
    app.kubernetes.io/version: "0.3.3"
    app.kubernetes.io/managed-by: Helm
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: kafka-ui
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - backend:
              service:
                name: kafka-ui
                port:
                  number: 8080
            pathType: Prefix
            path: /
```

And the `Service`:
```
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  labels:
    helm.sh/chart: kafka-ui-0.3.3
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: kafka-ui
    app.kubernetes.io/version: "0.3.3"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: kafka-ui
```

Because this is an ALB, it also generates a Security Group in AWS. This security group allows all inbound on port 80 by default. 

Regarding my `envs` in the `values.yaml` file, I have only added what is required for `SCRAM` based authentication to the broker listeners. 

Are there any other configurations that are necessary for the `ingress` ? 

**Steps to Reproduce**

1. Create an EKS cluster with IGW and NGW attached
2. Deploy AWS ALB controller
3. Create a Kafka cluster with listeners accepting SCRAM authentication
4. Deploy kafka-ui as above.

**Expected behavior**

I would expect the browser to open the front end as usual. I am able to port-forward to it, and that seems to work fine.

**Screenshots**

**Additional context**
