### ISSUE TITLE
Creating a topic with default settings will alter retention.bytes

### ISSUE THREAD

**Issue by nikobearrr** [provectus/kafka-ui#1725]
**Describe the bug**
When creating a new topic the retention.bytes is set to 0 instead of -1.

**Steps to reproduce**
1. Run kafka-ui 0.3.3
2. Create a new topic
3. Select "Not Set" on "Max Size on disk GB"
4. Observe the `retention.bytes` is set to `0` instead of `-1`

**Comment by Haarolean** [comment]
@nikobearrr thanks for raising the issue! We'll take a look.

**Comment by Mgrdich** [comment]
Front Part the NOT_SET Value set is -1 , if we want to view the value as 0 during the NOT_SET case the BE should send it as such.

**Comment by Haarolean** [comment]
@nikobearrr I couldn't reproduce the issue (latest master commit). `retention.bytes` is being set to `-1`.
Please copy the request body from your browser's developer console when you create a topic (POST /api/clusters/local/topics).
<img width="694" alt="image" src="https://user-images.githubusercontent.com/1494347/158401280-c92bd4ba-e596-4f6a-8d12-0f83ac8020c9.png">

**Comment by nikobearrr** [comment]
Hi @Haarolean,

Here is a screenshot from when running 0.3.3:

![image](https://user-images.githubusercontent.com/8693064/158407594-591d9e76-4cbd-4092-9076-4b62f8e191ed.png)

To reproduce it, you can use the following compose:


```
version: "3.5"
services:
  zk1:
    image: zookeeper:3.4.12
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

  zk2:
    image: zookeeper:3.4.12
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zk3:2888:3888

  zk3:
    image: zookeeper:3.4.12
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=0.0.0.0:2888:3888

  kafka1:
    image: wurstmeister/kafka:2.12-2.1.1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  kafka2:
    image: wurstmeister/kafka:2.12-2.1.1
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  kafka3:
    image: wurstmeister/kafka:2.12-2.1.1
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  kafka-ui:
    image: provectuslabs/kafka-ui:0.3.3
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zk1:2181,zk2:2181,zk3:2181
```
