### ISSUE TITLE
Overriding ingressClassName with values.yaml

### ISSUE THREAD

**Issue by varunreddy6999** [provectus/kafka-ui#1730]
**FYI: I'm adding this chart as a dependent chart to my helm 
I'm not being able to pass ingressClassName value from values.yaml file**

**Set up**

**Steps to Reproduce**

1. In values.yaml, enable Ingress by
```
 kafka-ui:
    ingress:
  # Enable ingress resource
      enabled: true
```
2.In the same values.yaml file add ingress class name and host
 ```
 kafka-ui:
    ingress:
       # ingressClassName for the Ingress
        ingressClassName: nginx

       # The hostname for the Ingress
        host: "kafka.example.com"
```

**Expected behavior**
When we update the values.yaml file as I mentioned above, actual behaviour should be ,
first ingress should be enabled and the values _host_ and _ingressClassName_ should be overrided with values from values.yaml,
But the value ingressClassName is not being taken , but all good with host name and ingress enable values
**Screenshots**

**Additional context**

Let me know if I'm missing anything. Thanks in advance
