### ISSUE TITLE
Display broker JMX metrics

### ISSUE THREAD

**Issue by hustlibraco** [provectus/kafka-ui#1778]
My kafka have opened JMX port with file-based authtication, and kafka-ui have connected jmx port successfully. 
The kafka cluster has just been built, and I manually ran kafka-console-producer.sh to produce some test data, but the data displayed on the Dashboard is no different from not enabling JMX.

Here is my Kafka env:
```
EXTRA_ARGS="-Djava.security.auth.login.config=/opt/kafka/config/kafka_server_jaas.conf"
KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=true  -Dcom.sun.management.jmxremote.ssl=false"
JMX_PORT=9999
```

Here is kafka-ui docker-compose.yml:
```
version: '3'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./cert:/opt/cert
    environment:
      # kafka集群配置
      - KAFKA_CLUSTERS_0_NAME=ember
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=ember-apac-kafka-1.xxx.net:9092,ember-apac-kafka-2.xxx.net:9092,ember-apac-kafka-3.xxx.net:9092
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-512
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin_secret";
      - KAFKA_CLUSTERS_0_JMXPORT=9999
      - KAFKA_CLUSTERS_0_JMXSSL=false
      - KAFKA_CLUSTERS_0_JMXUSERNAME=monitorRole
      - KAFKA_CLUSTERS_0_JMXPASSWORD=monitorRole_secret
    extra_hosts:
      - "ember-apac-kafka-1.xxx.net:10.66.17.35"
      - "ember-apac-kafka-2.xxx.net:10.66.17.36"
      - "ember-apac-kafka-3.xxx.net:10.66.17.37"
      - "ember-apac-zk-1.xxx.net:10.66.17.35"
      - "ember-apac-zk-2.xxx.net:10.66.17.36"
      - "ember-apac-zk-3.xxx.net:10.66.17.37"
```

I expect to see Inbound and outbound bandwidth per broker or topic in Kafka-ui. Is it possible to do that, or I miss some config?
Very appreciate to any reply.
