### ISSUE TITLE
Kafka UI not working behind reverse proxy

### ISSUE THREAD

**Issue by tommyvca** [provectus/kafka-ui#1792]
**Describe the bug**
I am using traefik for the reverse proxy with docker, and it will return error 400 bad request.
I have little troubleshot and find that it only accept hostname "localhost" or ip, others will return error 400.

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.
Have you tried [this](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ui-traefik-proxy.yaml)?

**Comment by tommyvca** [comment]
Found that is only not work with underscore for the service url. thanks

**Comment by ryan-clancy** [comment]
@tommyvca - how did you resolve the issue? I am having the same issue with underscores in the URL that I am unable to change.

**Comment by Haarolean** [comment]
@ryan-clancy can you share more details on the subject?

**Comment by ryan-clancy** [comment]
@Haarolean I have kafka-ui running behind a reverse proxy (in K8s) and when I try to connect I get a 400 bad request. I believe it is the same issue as this with an underscore in the URL (I cannot control this URL as it is generated for me). I can port-forward and access it fine and when swapping out kafka-ui with a nginx “hello world” I see the “hello world” page so the reverse proxy is working as expected.

**Comment by Haarolean** [comment]
@ryan-clancy can you provide an example of URL which doesn't work?

**Comment by ryan-clancy** [comment]
@Haarolean An example URL would be `kafka-ui_my-namespace_8080.my-cluster.aws.domain.com`

**Comment by Haarolean** [comment]
@ryan-clancy will take a look

**Comment by Haarolean** [comment]
Couldn't reproduce with the following:
Docker-compose:
```
services:

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80

  kafka-ui:
    container_name: kafka-ui
    hostname: kafka-ui
    image: provectuslabs/kafka-ui:master
    depends_on:
      - kafka0
      - schema-registry0
      - kafka-connect0
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'  # not necessary, added for tests
```

proxy.conf:
```
server {
    listen       80;
    server_name  kafka-ui_my-namespace_8080.lan;

    location / {
#        rewrite /kafka-ui/(.*) /$1  break;
        proxy_pass   http://kafka-ui:8080;
    }
}
```

`/etc/hosts`:
`127.0.0.1 kafka-ui_my-namespace_8080.lan`

Please feel free to reopen with a reproducible scenario
