### ISSUE TITLE
Dockerfile: Support passing external application.yml properties file

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1897]

**Comment by Haarolean** [comment]
No additional actions required. 

An example setup:
```
 kafka-ui:
    image: provectuslabs/kafka-ui:master
    volumes:
      - /tmp/config.yml:/config.yml
    environment:
      SPRING_CONFIG_LOCATION: /config.yml
```
