### ISSUE TITLE
Reverse DNS kafka-ui flood

### ISSUE THREAD

**Issue by nargotik** [provectus/kafka-ui#1916]
**Describe the bug**
After setting a kafka cluster in 5 vm's and kafka-ui in docker-compose in first machine after a while router start receiving dns request flood to kafka node ip (192.168.21.21) with dns request 21.21.168.1.in-addr.arpa

**Set up**
Kafka running in a debian bullseye standalone with no docker and kafka-ui wunning in docker with sample down

```
version: '2'
services:

  kafka-ui:
    container_name: kafka-ui
    restart: always
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 192.168.21.21:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: 192.168.21.21:2181
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
```

**Steps to Reproduce**
Check dns requests made by OS and in a few days requests will be like 90M per day

**Expected behavior**
Dns flood on dns server

**Screenshots**

**Additional context**

**Comment by Haarolean** [comment]
Hi, what's the configuration option value for `advertised.listeners` for kafka itself?

**Comment by nargotik** [comment]
Hi @Haarolean 
```
advertised.listeners=INTERNAL://192.168.21.21:9092
```

To pass this problem I have maded this workaround
```
version: '3.7'
x-extra_hosts:
  &default-extra_hosts
  - "node0:192.168.21.21"

kafka-ui:
    container_name: kafka-ui
    restart: always
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: node0:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: node0:2181
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
    extra_hosts: *default-extra_hosts
```

but I havent figured the problem, just did a workaround
