### ISSUE TITLE
Avro messages with Union type are not shown correctly 

### ISSUE THREAD

**Issue by christoph110** [provectus/kafka-ui#1923]
**Describe the bug**
Avro messages are not shown correctly when using Union type.

**Set up**
Use `provectuslabs/kafka-ui:0.4.0` image. Use confluentinc schema registry `confluentinc/cp-schema-registry:7.0.1`
```
version: '3.5'
...
services:
...
  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.1
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"
    depends_on:
      - zookeeper
      - kafka
...
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.4.0
    ports:
      - "8080:8080"
    depends_on:
      - schema-registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
...
```

**Steps to Reproduce**

1. Run docker compose
2. Send Avro message using `confluent_kafka.schema_registry.avro.AvroSerializer`

**Expected behavior**
The message for an Avro schema that contains Union types should be displayed correctly.

**Screenshots**
Using this schema:
![image](https://user-images.githubusercontent.com/59751309/166694610-c0389bd7-c414-4e56-b89b-5326ab0c72fa.png)

Creates this rendered message:
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/59751309/166694824-efc2b23a-9cd3-4b1d-8275-edcbd5a751a5.png">

Expected message rendering would be the same as for the consumer using the `confluent_kafka.schema_registry.avro.AvroDeserializer` module:
```
{'a': 'hello'}
```

**Additional context**
