### ISSUE TITLE
Topics fail to list, or refresh with an empty list when one of the connected brokers is killed

### ISSUE THREAD

**Issue by raferg** [provectus/kafka-ui#2103]
**Describe the bug**

I've been testing failure handling in my local configuration, and have discovered that when i take down one of the brokers via a docker kill command, the ui cannot list any topics. It is fine listing brokers, and consumers, but it cannot list the topics. 

During my test i took down brdg-broker-one and it fails to list any topics (has a spinning icon indefinitely). In a separate test i took out brdg-broker-two and it managed to list the topics, but then refreshes the page with an empty list. 

**Set up**

docker_compose.yml:

```
networks: 
  brdgNet:
    name: brdgNet

services:
  brdg-zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: brdg-zookeeper
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    networks: 
      - brdgNet
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  brdg-broker-one:
    image: confluentinc/cp-kafka:5.5.0
    container_name: brdg-broker-one
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    networks: 
      - brdgNet
    restart: always
    ports:
      - "19092:19092"
    depends_on:
      - brdg-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: brdg-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://brdg-broker-one:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://brdg-broker-one:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE: CreateTime
      KAFKA_LOG_RETENTION_HOURS: 2232

  brdg-broker-two:
    image: confluentinc/cp-kafka:5.5.0
    container_name: brdg-broker-two
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    networks: 
      - brdgNet
    restart: always
    ports:
      - "19093:19093"
    depends_on:
      - brdg-zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: brdg-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://brdg-broker-two:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://brdg-broker-two:9093,CONNECTIONS_FROM_HOST://localhost:19093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE: CreateTime
      KAFKA_LOG_RETENTION_HOURS: 2232

  brdg-broker-three:
    image: confluentinc/cp-kafka:5.5.0
    container_name: brdg-broker-three
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    networks: 
      - brdgNet
    restart: always
    ports:
      - "19094:19094"
    depends_on:
      - brdg-zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: brdg-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://brdg-broker-three:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://brdg-broker-three:9094,CONNECTIONS_FROM_HOST://localhost:19094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE: CreateTime
      KAFKA_LOG_RETENTION_HOURS: 2232

  kafka-ui:
    image: provectuslabs/kafka-ui:master
    container_name: brdg-webui
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    ports:
      - "8080:8080"
    networks: 
      - brdgNet
    restart: always
    depends_on: 
      - brdg-broker-one
      - brdg-zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=brdg-broker-one:9092,brdg-broker-two:9093,brdg-broker-three:9094
      - KAFKA_CLUSTERS_0_ZOOKEEPER=brdg-zookeeper:2181
```

**Steps to Reproduce**

1. `docker-compose -f docker-compose.yml up -d`
2. open web browser to localhost:8080, open Topics tab, Brokers tab, and Consumer tab; observe contents
3. `docker kill brdg-broker-one` or `docker kill brdg-broker-two`
4. open web browser to localhost:8080, open Topics tab, Brokers tab, and Consumer tab; observe contents (note that Topics tab doesn't load, or loads incorrectly)
