### ISSUE TITLE
Cannot authenticate with SASL_SSL and SCRAM-SHA-512 (comma in password)

### ISSUE THREAD

**Issue by andrewm42** [provectus/kafka-ui#2116]
**Describe the bug**
I am attempting to authenticate via docker-compose with the following confguration:

```yaml
version: "3"
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 18080:8080
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: test
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9096
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeper:2181
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="ABC" password="123";'
```

However, I get the following errors when running the container:

```
kafka-ui  | 2022-06-03 21:23:18,329 ERROR [kafka-admin-client-thread | adminclient-1] o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-1] Connection to node -1 (redacted-url.zone:9096) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512
```

My kafka cluster is setup to use SASL/SCRAM. The same configuration works from the kafka CLI and from various other apps hosted on the same machine running in various different languages (go, c#, python).

**Set up**
Run the above docker-compose yaml against a cluster configured for SASL_SSL and SCRAM-SHA-512 authentication

**Steps to Reproduce**
Try the above

**Expected behavior**
I should be able to authenticate with the specified configuration.

**Additional context**
I am also open to the possibility that I am missing some environment variable in my docker-compose.

**Comment by Haarolean** [comment]
Hi, don't you have any special characters in your password, like commas?

**Comment by Haarolean** [comment]
Yeaaah, it seems like it has to be, since it's not the first time we encounter such a problem. Thanks!
#1928 (#911?)

**Comment by Haarolean** [comment]
@andrewm42 could you provide a kafka setup example to reproduce the issue? Docker-compose would be fine.

**Comment by IldarAlmakaev** [comment]
@andrewm42 @Haarolean hello 👋 
Today I tested authentication with some special characters (`abc1212!,asd`) in a password and couldn't reproduce the issue.
```
KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="enzo" password="abc1212!,asd";'
```
@andrewm42 Are you still facing the issue? Could you check on the latest version, please?

**Comment by IldarAlmakaev** [comment]
By and large, I couldn't reproduce the issue with different special characters in a password :(
Please, let us know if you encounter such an error again.

**Comment by KozyrevychYaroslav** [comment]
@Haarolean 
You have closed my issue as duplicate of this issue and asked to provide example of docker compose. So here is my docker compose file
```
version: '2.6'
services:

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8001:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: xxxx:9092,xxyy:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="username" password="password";'
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /ca-dv.ks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: password
    volumes:
      - ./ssl/ca-dv.ks:/ca-dv.ks
```
      
 
Password has characters like "#", "*", "$"
Login has "_"
Server name has "-"

**Comment by Haarolean** [comment]
@KozyrevychYaroslav thanks, but the problem is that we probly need a full example with kafka itself.
As you can see in comments above we weren't able to reproduce the issue.

**Comment by vunamphuong17** [comment]
I have the same issue when try to authenticate with SCRAM-SHA-512. My password don't have any special character.

My config:
```
        bootstrap.servers = [kafka-1:9096, kafka-2:9096]
	client.dns.lookup = use_all_dns_ips
	client.id = kafka-ui-admin-client-1677145586653
	connections.max.idle.ms = 300000
	default.api.timeout.ms = 60000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = [hidden]
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.connect.timeout.ms = null
	sasl.login.read.timeout.ms = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.login.retry.backoff.max.ms = 10000
	sasl.login.retry.backoff.ms = 100
	sasl.mechanism = SCARM-SHA-512
	sasl.oauthbearer.clock.skew.seconds = 30
	sasl.oauthbearer.expected.audience = null
	sasl.oauthbearer.expected.issuer = null
	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
	sasl.oauthbearer.jwks.endpoint.url = null
	sasl.oauthbearer.scope.claim.name = scope
	sasl.oauthbearer.sub.claim.name = sub
	sasl.oauthbearer.token.endpoint.url = null
	security.protocol = SASL_SSL
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
```

JAAS config
`KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG='org.apache.kafka.common.security.scram.ScramLoginModule required username="username" password="password";'`

**Error logs**
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/22033960/220875124-295b8e02-0ada-42f5-940e-929e97f161d9.png">

**Comment by Haarolean** [comment]
@vunamphuong17 that's unrelated, a different error message. Your sasl mechanism is "SCARM...", there's a typo.

@KozyrevychYaroslav yep, just tried with `KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin_" password="admin-secret#*$$";'` within `kafka-ui-sasl.yaml` example, works fine.

**Comment by KozyrevychYaroslav** [comment]
@Haarolean now I get new error when I try to view topics in UI. Note that I have read-only access. `Caused by: org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.
`

**Comment by Haarolean** [comment]
@KozyrevychYaroslav https://provectus.gitbook.io/kafka-ui/configuration/configuration/required-acls
Please let's keep the discussion about the aforementioned issue. 
Feel free to join us on discord if you'd need additional help.

**Comment by Haarolean** [comment]
This issue requires a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in form of docker-compose with kafka and kafka-ui both for us to take a look into this.

**Comment by andreyolv** [comment]
Any preview of docker-compose example using SASL/SCRAM-512? integrating kafka, kafka-ui, schema registry, ksqldb? It would be very useful

**Comment by Haarolean** [comment]
@andreyolv https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ui-sasl.yaml

**Comment by andreyolv** [comment]
@Haarolean This example uses PLAIN, not SCRAM-512

**Comment by gee456** [comment]
I too would love to see a working example of SCRAM-512

**Comment by alyvusal** [comment]
I've used env variables also hardcoded into values file but can not authenticate, my sample config

```yaml
          security.protocol: SASL_SSL
          sasl.mechanism: SCRAM-SHA-256
          sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="changeit";'
          ssl.truststore.type: JKS
          ssl.truststore.location: /ssl/kafka.client.truststore.jks
          ssl.truststore.password: changeit
          ssl.keystore.type: JKS
          ssl.keystore.location: /ssl/kafka.client.keystore.jks
          ssl.keystore.password: changeit
```

but kafka-console-consumer.sh and producer works with same config
