### ISSUE TITLE
custom timezone in UI

### ISSUE THREAD

**Issue by raphaelauv** [provectus/kafka-ui#2166]
### Is your proposal related to a problem?

Currently the front-end use the local user timezone to render kafka timestamp

```
Timestamp type: CREATE_TIME
```

### Describe the solution you'd like

custom in the front end the timezone and be able to select UTC 

### Additional context

apache airflow have this feature , it's really practical , example -> 
![Screenshot from 2022-06-14 19-41-58](https://user-images.githubusercontent.com/10202690/173644933-a2fd6663-5259-40f2-9ced-7dd31747c8dc.png)

**Comment by wanisfahmyDE** [comment]
as a quick workaround, one can set the timezone as a config.

docker-compose example:
```yaml
version: '2'
services:

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.5.0
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: localhost:9092
      JAVA_OPTS: >-
        -Duser.timezone=Europe/London
```
