### ISSUE TITLE
TopicAuthorizationException when connecting to a Kafka Cluster with SSL

### ISSUE THREAD

**Issue by KevDi** [provectus/kafka-ui#2168]
If i run the Docker Compose File it seems to successfully connecting to the Kafka Cluster but it is unable to get the Metrics for that Cluster. It always gives me the log output: `org.apache.kafka.common.errors.TopicAuthorizationException: Topic authorization failed.`
I also used the same Keystore and Truststore in the COnfiguration with the Offset Explorer Tool and there everything works.

**Set up**
I run Kafka UI with the following docker-compose.yml file:

```
version: "3.5"

services:
  kafka-ui:
    hostname: kafka-ui
    image: provectuslabs/kafka-ui:v0.4.0
    container_name: kafka-ui
    ports:
      - 8080:8080
    volumes:
      - ./cert:/opt/cert
    environment:
      KAFKA_CLUSTERS_0_NAME: my_kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka_node_1:9093,kafka_node_2:9093,kafka_node_3:9093
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /opt/cert/keystore.p12
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: [pass]
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /opt/cert/truststore.ts
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: [pass]
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_TYPE: JKS

```
