### ISSUE TITLE
Support multiple ksqlDB in one Kafka cluster

### ISSUE THREAD

**Issue by fersandiP** [provectus/kafka-ui#2204]
### Is your proposal related to a problem?

We decided to deploy multiple ksqlDB per use case as [recommended by ksql docs](https://docs.ksqldb.io/en/latest/operate-and-deploy/capacity-planning/#interactive-ksqldb-servers-vs-non-interactive-headless-servers) in one kafka cluster. However, when we try to integrate ksqlDB to kafka-ui, we don't see any setting to setup this configuration.

### Describe the solution you'd like

Support multiple ksqlDB in one cluster like kafka connect.

As environment variable
```sh
KAFKA_CLUSTERS_0_KSQLDBSERVER_0_ADDRESS=first
KAFKA_CLUSTERS_0_KSQLDBSERVER_0_ADDRESS=http://localhost:8088
```

or as config YAML file
```yaml
kafka:
  clusters:
    - name: local
      ksqldbServer: 
        - name: first
          address: http://localhost:8088
      kafkaConnect:
        - name: first
          address: http://localhost:8083
      jmxPort: 9997
```

### Describe alternatives you've considered

Deploy multiple kafka-ui for each ksqlDB

### Additional context

[ksqlDB docs - Deploy recommendation and best practices](https://docs.ksqldb.io/en/latest/operate-and-deploy/capacity-planning/#recommendations-and-best-practices)
