### ISSUE TITLE
Can't create topic when Basic Authentication is enable

### ISSUE THREAD

**Issue by pravin-raha** [provectus/kafka-ui#2263]
**Describe the bug**
Can't create topic when Basic Authentication is enable

**Set up**
My docker compose file
```
version: '2'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
      - auth.type='LOGIN_FORM'
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin
```

**Steps to Reproduce**

1. Enable basic authentication using above docker compose file
2. Try to create kafka topic under topic tab

**Expected behavior**
Topic should be created

**Screenshots**
![image](https://user-images.githubusercontent.com/18550421/178738317-ec3cc942-2977-4d36-a278-41e6c0003ba7.png)

![image](https://user-images.githubusercontent.com/18550421/178738675-fc4d735d-2247-4b6b-a665-58c6e6ab4aea.png)

**Additional context**

**Comment by pravin-raha** [comment]
@Haarolean You got the login form, right?
Can you try producing messages as well?

**Comment by Haarolean** [comment]
> @Haarolean You got the login form, right? Can you try producing messages as well?
> 
> Did get any error on container logs

Yes, I did. Yes, producing messages does work.
Your case seems weird, in this case either everything shouldn't work or everything should :)
Can you share the full compose file?
Also we can chat on our discord to make it quicker, if you want ofc.

**Comment by Haarolean** [comment]
Environment properties list has to be replaced with dashed list:
```
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER:zookeeper: 2181
      AUTH_TYPE: 'LOGIN_FORM'
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: admin
```
