### ISSUE TITLE
Memory leak (?)

### ISSUE THREAD

**Issue by paoloboni** [provectus/kafka-ui#230]
Hi there,

I recently started experimenting kafka-ui in k8s and I consistently noticed a potential memory leak.
The memory-used increase is slow-burning if the UI is not used, it takes less time to cause a problem when it's actively used.
I could see 1 single container getting to use >1.5Gb of memory with no activity.

The cluster is an AKS, Kubernetes version is v1.18.14.

These are the k8s manifests I'm using:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: kafka-ui
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/version: 0.0.9
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kafka-ui
      app.kubernetes.io/name: kafka-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kafka-ui
        app.kubernetes.io/name: kafka-ui
        app.kubernetes.io/version: 0.0.9
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:0.0.9
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: kafka
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-cp-kafka:9092
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: kafka-cp-zookeeper
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kafka-ui
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/version: 0.0.9
  name: kafka-ui
spec:
  ports:
    - name: web
      port: 8080
      targetPort: web
  selector:
    app.kubernetes.io/component: kafka-ui
    app.kubernetes.io/name: kafka-ui
  type: ClusterIP
```

I haven't checked the implementation so I don't have any suggestion. 
Do you think it's possible that this behaviour is caused by a memory leak in the api server?
