### ISSUE TITLE
how to config SASL Zookeeper and

### ISSUE THREAD

**Issue by JiyongShi** [provectus/kafka-ui#239]
we production cluster's zookeeper use SASL plaintxt, kafka use SASL SCRAM
how to set ENV variable to support SASL?

**Comment by JiyongShi** [comment]
we production  cluster's zookeeper use SASL plaintxt,  kafka use SASL SCRAM
how to set ENV variable to support SASL?

**Comment by germanosin** [comment]
@JiyongShi 
this should work for you
```
-e KAFKA_CLUSTERS_0_NAME=sasl-server \
-e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS={your_kafka_server}:9092 \
-e KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL \
-e KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-256 \
-e KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username="USERNAME" password="PASSWORD"; \
```

**Comment by JiyongShi** [comment]
thank you. it works well.  i also config zookeeper sasl with
      - KAFKA_CLUSTERS_0_NAME=sasl-cluster-xxx
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9092,kafka2:9092,kafka3:9092
      - KAFKA_CLUSTERS_0_JMXPORT=5555
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-256
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="password";
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_PROPERTIES_USER=zkuser
      - KAFKA_CLUSTERS_0_PROPERTIES_PASSWORD=zkpassword
      - KAFKA_CLUSTERS_0_PROPERTIES_PROTOCOL=SASL

**Comment by hustlibraco** [comment]
> @JiyongShi 
HI，follow your config, I still can not connect to zookeeper with sasl. can you give more instruction?

```
kafka-ui    | 2022-03-29 07:47:43,759 WARN  [kafka-admin-client-thread | adminclient-1-SendThread(ember-apac-zk-2.xxx.net:2181)] o.a.z.ClientCnxn: Session 0x1001571eb0f0349 for sever ember-apac-zk-2.xxx.net/10.66.17.36:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
kafka-ui    | org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x1001571eb0f0349, likely server has closed socket
kafka-ui    |   at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
kafka-ui    |   at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
kafka-ui    |   at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1280)
kafka-ui    | 2022-03-29 07:47:44,261 INFO  [kafka-admin-client-thread | adminclient-1-SendThread(ember-apac-zk-1.xxx.net:2181)] o.a.z.ClientCnxn: Opening socket connection to server ember-apac-zk-1.xxx.net/10.66.17.35:2181.
kafka-ui    | 2022-03-29 07:47:44,261 INFO  [kafka-admin-client-thread | adminclient-1-SendThread(ember-apac-zk-1.xxx.net:2181)] o.a.z.ClientCnxn: SASL config status: Will not attempt to authenticate using SASL (unknown error)
kafka-ui    | 2022-03-29 07:47:44,262 INFO  [kafka-admin-client-thread | adminclient-1-SendThread(ember-apac-zk-1.xxx.net:2181)] o.a.z.ClientCnxn: Socket connection established, initiating session, client: /172.18.0.2:58040, server: ember-apac-zk-1.xxx.net/10.66.17.35:2181
kafka-ui    | 2022-03-29 07:47:44,265 INFO  [kafka-admin-client-thread | adminclient-1-SendThread(ember-apac-zk-1.xxx.net:2181)] o.a.z.ClientCnxn: Session establishment complete on server ember-apac-zk-1.xxx.net/10.66.17.35:2181, session id = 0x1001571eb0f0349, negotiated timeout = 40000
kafka-ui    | 2022-03-29 07:47:44,978 DEBUG [parallel-1] c.p.k.u.s.ClustersMetricsScheduler: Start getting metrics for kafkaCluster: ember
kafka-ui    | 2022-03-29 07:47:44,983 DEBUG [kafka-admin-client-thread | adminclient-1] c.p.k.u.s.ZookeeperService: Start getting Zookeeper metrics for kafkaCluster: ember
kafka-ui    | 2022-03-29 07:47:44,984 WARN  [kafka-admin-client-thread | adminclient-1-SendThread(ember-apac-zk-1.xxx.net:2181)] o.a.z.ClientCnxn: Session 0x1001571eb0f0349 for sever ember-apac-zk-1.xxx.net/10.66.17.35:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
kafka-ui    | org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x1001571eb0f0349, likely server has closed socket
kafka-ui    |   at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
kafka-ui    |   at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
kafka-ui    |   at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1280)
kafka-ui    | 2022-03-29 07:47:44,984 ERROR [kafka-admin-client-thread | adminclient-1] c.p.k.u.s.ZookeeperService: A zookeeper exception has occurred
kafka-ui    | org.apache.zookeeper.KeeperException$SessionClosedRequireAuthException: KeeperErrorCode = Session closed because client failed to authenticate for /brokers/ids
kafka-ui    |   at org.apache.zookeeper.KeeperException.create(KeeperException.java:148)
kafka-ui    |   at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
kafka-ui    |   at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2366)
kafka-ui    |   at com.provectus.kafka.ui.service.ZookeeperService.isZkClientConnected(ZookeeperService.java:57)
kafka-ui    |   at com.provectus.kafka.ui.service.ZookeeperService.isZookeeperOnline(ZookeeperService.java:49)
kafka-ui    |   at com.provectus.kafka.ui.service.ZookeeperService.lambda$getZkStatus$0(ZookeeperService.java:37)
kafka-ui    |   at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:57)
kafka-ui    |   at reactor.core.publisher.Mono.subscribe(Mono.java:4399)
kafka-ui    |   at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128)
kafka-ui    |   at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
kafka-ui    |   at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:165)
kafka-ui    |   at com.provectus.kafka.ui.service.ReactiveAdminClient.lambda$describeCluster$18(ReactiveAdminClient.java:224)
kafka-ui    |   at org.apache.kafka.common.internals.KafkaFutureImpl$WhenCompleteBiConsumer.accept(KafkaFutureImpl.java:177)
kafka-ui    |   at org.apache.kafka.common.internals.KafkaFutureImpl$WhenCompleteBiConsumer.accept(KafkaFutureImpl.java:162)
kafka-ui    |   at org.apache.kafka.common.internals.KafkaFutureImpl.complete(KafkaFutureImpl.java:221)
kafka-ui    |   at org.apache.kafka.common.KafkaFuture$AllOfAdapter.maybeComplete(KafkaFuture.java:82)
kafka-ui    |   at org.apache.kafka.common.KafkaFuture$AllOfAdapter.accept(KafkaFuture.java:76)
kafka-ui    |   at org.apache.kafka.common.KafkaFuture$AllOfAdapter.accept(KafkaFuture.java:57)
kafka-ui    |   at org.apache.kafka.common.internals.KafkaFutureImpl.complete(KafkaFutureImpl.java:221)
kafka-ui    |   at org.apache.kafka.clients.admin.KafkaAdminClient$5.handleResponse(KafkaAdminClient.java:1875)
kafka-ui    |   at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.handleResponses(KafkaAdminClient.java:1189)
kafka-ui    |   at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1341)
kafka-ui    |   at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1264)
kafka-ui    |   at java.base/java.lang.Thread.run(Thread.java:830)
```
this is my compose:
```
version: '2'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=ember
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=ember-apac-kafka-1.xxx.net:9092,ember-apac-kafka-2.xxx.net:9092,ember-apac-kafka-3.xxx.net:9092
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-512
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="kafka_secret";
      - KAFKA_CLUSTERS_0_ZOOKEEPER=ember-apac-zk-1.xxx.net:2181,ember-apac-zk-2.xxx.net:2181,ember-apac-zk-3.xxx.net:2181
      - KAFKA_CLUSTERS_0_PROPERTIES_USER=admin
      - KAFKA_CLUSTERS_0_PROPERTIES_PASSWORD=zookeeper_secret
      - KAFKA_CLUSTERS_0_PROPERTIES_PROTOCOL=SASL
    extra_hosts:
      - "ember-apac-kafka-1.xxx.net:10.66.17.35"
      - "ember-apac-kafka-2.xxx.net:10.66.17.36"
      - "ember-apac-kafka-3.xxx.net:10.66.17.37"
      - "ember-apac-zk-1.xxx.net:10.66.17.35"
      - "ember-apac-zk-2.xxx.net:10.66.17.36"
      - "ember-apac-zk-3.xxx.net:10.66.17.37"
```
and this is zookeeper jaas.conf
```
Server {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    user_admin="zookeeper_secret"
    username="admin"
    password="zookeeper_secret";
};
```
