### ISSUE TITLE
"TopicAuthorizationException: Topic authorization failed" for MSK

### ISSUE THREAD

**Issue by laivu266** [provectus/kafka-ui#2456]
**Describe the bug**
I got the error as below when I config Kafka-ui via helm chart and connect to MSK. As image below, I successfully auth to MSK, but seem be to topics is not.

![image](https://user-images.githubusercontent.com/96401818/185034398-bc60f176-5e8e-45cf-8dbd-002a3668d264.png)

**Set up**

I used helm for install Kafka-UI. This is my helm value file:
```
replicaCount: 1
fullnameOverride: "kafka-ui"

existingConfigMap: ""
existingSecret: ""
envs:
  config:
    KAFKA_CLUSTERS_0_NAME: msk-g1-dev
    KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "msk-broker-url:9096"
    KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
    KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
    KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="my_admin_user" password="my_pass_word";'
```

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
