### ISSUE TITLE
Create connector in Kafka Connect do not work

### ISSUE THREAD

**Issue by ykun92** [provectus/kafka-ui#2464]
**Describe the bug**

Can not create new connector using `Create Connector` page in Kafka UI.

I have checked the inputted config is no problem , and I can use the config to add connector via REST API as following picture.

![image](https://user-images.githubusercontent.com/86184362/185307468-2c9ddd74-57d7-4c30-866d-9df39783ecf5.png)

But when I do the same things in Kafka UI, it always give me a error message `Connector with name mongo-sink already exists`.
And the error message itself is misleading since I already confirmed the `mongo-sink` is not exist. (I have tried any name have the same error message as complaining that name is exist)

![image](https://user-images.githubusercontent.com/86184362/185308076-ddaf9703-123d-4223-b6f9-c3cc4e2cad86.png)

**Set up**

Here is my setup (partical)

docker-compose.yaml
```yaml
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    env_file:
      - kafka-ui.env
```

kafka-ui.env
```
KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker-1:9092,broker-2:9092,broker-3:9092
KAFKA_CLUSTERS_0_JMXPORT=9101
KAFKA_CLUSTERS_0_KSQLDBSERVER=http://ksqldb-server:8088
KAFKA_CLUSTERS_0_NAME=Moonlight
KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schema-registry:8081
KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME=kafka-connect
KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=http://connect:8083
SERVER_FORWARDHEADERSSTRATEGY=native
SERVER_SERVLET_CONTEXT_PATH=/kafka
```

**Expected behavior**

Create connector in Kafka UI work normally.

**Screenshots**

Here is the API error response captured in Chrome when click the Submit button
![response-message](https://user-images.githubusercontent.com/86184362/185308685-841565aa-a2e6-47e0-9ee4-5c7992563739.png)

Here is the error message from kafka-connect log
![error-log](https://user-images.githubusercontent.com/86184362/185309166-b54d4c9a-ce61-420b-8515-63d6b5f475c9.png)

**Comment by Haarolean** [comment]
HI, thanks for reaching out.

Could you please provide connector's config as a text, not as a screenshot? Thanks.

**Comment by ykun92** [comment]
Thanks for response.

Here is my settings.

docker-compose.yaml
```yaml
version: "3.8"

services:
  connect:
    image: confluentinc/cp-kafka-connect-base:7.2.1
    command: start-connect.sh
    networks:
      - default
      - ***
    deploy:
      placement:
        constraints:
          - ***
    # Healthcheck script in kafka-connect v7.2.1 has a bug and make it
    # not work with swarm mode. Since in docker swarm, service name (hostname)
    # will not get registered in swarm internal DNS until healthcheck
    # is OK, but the healthcheck script itself use the
    # CONNECT_REST_ADVERTISED_HOST_NAME to check health, cause the healthcheck
    # will never pass and the container failed to start.
    # As a wordaround, disable healthcheck here to make it work in swarm.
    healthcheck:
      disable: true
    environment:
      CONNECT_BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092,broker-3:9092
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    volumes:
      - ../dockerize:/usr/bin/dockerize
      - ./start-connect.sh:/usr/bin/start-connect.sh

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - default
      - ***
    deploy:
      placement:
        constraints:
          - ***
      labels:
        - traefik.enable=true
        - traefik.http.routers.moonlight-kafka.entrypoints=websecure
        - traefik.http.routers.moonlight-kafka.rule=***
        - traefik.http.routers.moonlight-kafka.middlewares=***
        - traefik.http.routers.moonlight-kafka.tls.certresolver=letsencrypt
        - traefik.http.services.moonlight-kafka.loadbalancer.server.port=8080
    env_file:
      - kafka-ui.env
```

start-connect.sh
```sh
#!/bin/sh

# https://docs.confluent.io/kafka-connectors/self-managed/extending.html
echo "Installing all required connectors..."
confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:13.1.2
confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.5.2
confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:1.7.0

# wait broker, schema-registry online
dockerize \
-wait tcp://broker-1:9092 \
-wait tcp://broker-2:9092 \
-wait tcp://broker-3:9092 \
-wait tcp://schema-registry:8081 \
-wait-retry-interval 20s \
-timeout 120s \
/etc/confluent/docker/run
```

I run service in docker swarm, I think it also works with `docker-compose`, or you can delete the `deploy` and other unnecessary settings.
