### ISSUE TITLE
RBAC: Support LDAP

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2752]

**Comment by Haarolean** [comment]
We'd need some volunteers to test things out.

We coordinate in discord, a link to the thread -> [here](https://discord.com/channels/897805035122077716/1098621183584382976). 

Image: `docker pull public.ecr.aws/provectus/kafka-ui-custom-build:3700`
Config example: [here](https://github.com/provectus/kafka-ui/pull/3700#issuecomment-1518369213)

Please check
1. That authentication with all users you need works fine.
2. RBAC groups matching works fine.

AD a bit later, it requires more black magic.

**Comment by Haarolean** [comment]
As I found no volunteers w/ AD, it's gonna be a separate issue. Please upvote #3741 if you're interested.

**Comment by padmaachuth** [comment]
@Haarolea tested RBAC for image public.ecr.aws/provectus/kafka-ui-custom-build:3700 with LDAP configuration but not able login with this image and I dont see any errors in logs

**Comment by Haarolean** [comment]
> @Haarolean 
> 
> Tested RBAC for image public.ecr.aws/provectus/kafka-ui-custom-build:3700 with LDAP configuration but not able login with this image and I dont see any errors in logs

Most likely, your configuration is invalid. Please share your config.

**Comment by padmaachuth** [comment]
rabc.yaml file

rbac:
  roles:
    - name: "readonly"
      clusters:
        - <kafka dev>
      subjects:
        - provider: ldap
          type: group
          value: "OU=Users,OU=Accounts,OU=Resources,DC=<domain>,DC=com"
        - provider: ldap_ad
          type: user
          value: "CN  <name>"
      permissions:
        - resource: clusterconfig
          actions: [ "view" ]

        - resource: topic
          value: ".*"
          actions:
            - VIEW
            - MESSAGES_READ

        - resource: consumer
          value: ".*"
          actions: [ view ]

        - resource: schema
          value: ".*"
          actions: [ view ]

        - resource: connect
          value: ".*"
          actions: [ view ]

**Comment by Haarolean** [comment]
@padmaachuth you haven't configured LDAP auth at all, see first lines of the config example I provided

**Comment by padmaachuth** [comment]
> @padmaachuth you haven't configured LDAP auth at all, see the first lines of the config example I provided

@Haarolean deploying image in openshift passing LDAP config from ENV 

KAFKA_CLUSTERS_0_NAME: <Cluster Name>
KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: <Bootstrap servers:port>
KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: GSSAPI
KAFKA_CLUSTERS_0_SCHEMAREGISTRY: <Schema Registry URL>
KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: <Kafka Connector Name>
KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: com.sun.security.auth.module.Krb5LoginModule required useTicketCache=false principal="<principal name>@DOMAIN.COM" useKeyTab=true serviceName="kafka" keyTab="/keytabs/<Principal Name>.keytab";
KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: <Kafka Connector URL>
KAFKA_CLUSTERS_0_READONLY: false
AUTH_TYPE: LDAP
SPRING_CONFIG_ADDITIONAL-LOCATION: /roles.yml
SPRING_LDAP_URLS: <LDAP URL>
SPRING_LDAP_USER-FILTER-SEARCH-BASE: DC=Domain,DC=com
SPRING_LDAP_USER-FILTER-SEARCH-FILTER: (&(sAMAccountName={0})(objectClass=person))
SPRING_LDAP_ADMINUSER: <admin user>
SPRING_LDAP_ADMINPASSWORD:<password>  

With this LDAP config able to Login but it not listing cluster, topics,schema,connectors,etc.

**Comment by Haarolean** [comment]
@padmaachuth please raise a discussion or ask in discord community, that's unrelated to this issue

**Comment by alexisph** [comment]
RBAC with LDAP does not work for me on v0.7.0.
I have the following config:

```yaml
kafka:
  clusters:
    - name: dev
      readOnly: false
      bootstrapServers: ${KAFKA_BOOTSTRAP}:9093

auth:
  type: LDAP
spring:
  ldap:
    urls: ldap://${AD_SERVER}
    base: "sAMAccountName={0},ou=${USERS_OU},dc=${AD_SERVER}"
    admin-user: "cn=${LDAP_ADMIN_USERNAME},dc=${AD_SERVER}"
    admin-password: "${LDAP_ADMIN_PASSWORD}"
    user-filter-search-base: "dc=${AD_SERVER}"
    user-filter-search-filter: "(&(sAMAccountName={0})(objectClass=user)(|(memberof=CN=${GROUP_NAME},OU=${GROUPS_OU},DC=${AD_SERVER})))"
    group-filter-search-base: "OU=${GROUPS_OU},DC=${AD_SERVER}"
oauth2:
  ldap:
    activeDirectory: false
    activeDirectory.domain: "${AD_SERVER}"

rbac:
  roles:
    - name: "admins"
      clusters:
        - dev
      subjects:
        - provider: ldap
          type: group
          value: "${GROUP_NAME}"
      permissions:
        - resource: applicationconfig
          # value not applicable for applicationconfig
          actions:
            - view
            # - edit
        - resource: clusterconfig
          # value not applicable for clusterconfig
          actions:
            - view
            # - edit
        - resource: topic
          value: ".*"
          actions:
            - view
            # - create
            # - edit
            # - delete
            - messages_read
            - messages_produce
            - messages_delete
        - resource: consumer
          value: ".*"
          actions:
            - view
            - delete
            - reset_offsets
        - resource: schema
          value: ".*"
          actions:
            - view
            - create
            - delete
            - edit
            # - modify_global_compatibility
        - resource: connect
          value: ".*"
          actions:
            - view
            # - edit
            # - create
        - resource: ksql
          # value not applicable for ksql
          actions:
            - execute
        # - resource: acl
        #   # value not applicable for acl
        #   value: ".*"  # FIXME: it crashes if this is removed
        #   actions:
        #     - view
        #     # - edit
```

I am able to login but I cannot see any clusters:

![image](https://github.com/provectus/kafka-ui/assets/1152793/e1e79660-bdbd-4876-bffd-944a57946b5c)

I have enabled DEBUG logs and I can see this:

```log
DEBUG [boundedElastic-3] o.s.s.l.u.DefaultLdapAuthoritiesPopulator: Found roles from search [{spring.security.ldap.dn=[CN=${GROUP_NAME},OU=${GROUPS_OU},DC=${AD_SERVER}], cn=[${GROUP_NAME}]}]
DEBUG [reactor-http-epoll-1] o.s.s.w.s.a.DelegatingReactiveAuthorizationManager: Checking authorization on '/api/clusters' using org.springframework.security.authorization.AuthenticatedReactiveAuthorizationManager@XXXXX
DEBUG [reactor-http-epoll-1] o.s.s.w.s.c.WebSessionServerSecurityContextRepository: Found SecurityContext 'SecurityContextImpl [Authentication=UsernamePasswordAuthenticationToken [Principal=com.provectus.kafka.ui.config.auth.RbacLdapUser@XXXXX, Credentials=[PROTECTED], Authenticated=true, Details=null, Granted Authorities=[${GROUP_NAME}]]]' in WebSession: 'org.springframework.web.server.session.InMemoryWebSessionStore$InMemoryWebSession@XXXXX'
DEBUG [reactor-http-epoll-1] o.s.s.w.s.a.AuthorizationWebFilter: Authorization successful
DEBUG [reactor-http-epoll-1] o.s.w.r.r.m.a.RequestMappingHandlerMapping: [XXXXX] Mapped to com.provectus.kafka.ui.controller.ClustersController#getClusters(ServerWebExchange)
DEBUG [reactor-http-epoll-1] o.s.w.r.r.m.a.ResponseEntityResultHandler: [XXXXX] Using 'application/json' given [*/*] and supported [application/json]
DEBUG [reactor-http-epoll-1] o.s.w.r.r.m.a.ResponseEntityResultHandler: [XXXXX] 0..N [com.provectus.kafka.ui.model.ClusterDTO]
DEBUG [reactor-http-epoll-1] o.s.s.w.s.c.WebSessionServerSecurityContextRepository: Found SecurityContext 'SecurityContextImpl [Authentication=UsernamePasswordAuthenticationToken [Principal=com.provectus.kafka.ui.config.auth.RbacLdapUser@XXXXX, Credentials=[PROTECTED], Authenticated=true, Details=null, Granted Authorities=[${GROUP_NAME}]]]' in WebSession: 'org.springframework.web.server.session.InMemoryWebSessionStore$InMemoryWebSession@XXXXX'
DEBUG [reactor-http-epoll-1] o.s.w.s.a.HttpWebHandlerAdapter: [XXXXX] Completed 200 OK
```

If I remove the `rbac` section, I can login and I can see and do everything because there are no roles.

Let me know if I should open a separate issue.

Thanks.
