### ISSUE TITLE
All operations from UI returned 403 Forbidden after enable LOGIN_FORM 

### ISSUE THREAD

**Issue by zhanglinqiang** [provectus/kafka-ui#2762]
When enable LOGIN_FORM auth type, all operations will failed with 403 forbidden.
 After remove AUTH_TYPE,SPRING_SECURITY_USER_NAME,SPRING_SECURITY_USER_PASSWORD config,  Everything works fine.

version: both v0.4.0 and master image(2b5dd270e22c6455c6a5999131dbf3ce3b770429) from docker hub have this problem.

compse config: 
```
      - AUTH_TYPE="LOGIN_FORM"
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin123 
```

response:
```
Request URL: http://10.7.181.153:8088/api/clusters/local/topics/tas.data
Request Method: DELETE
Status Code: 403 Forbidden
```

**Comment by Haarolean** [comment]
If you're using the app's REST interface and you have basic authentication enabled, obviously you have to authenticate via API as well. 

Here's [a tip](https://github.com/provectus/kafka-ui/discussions/2459#discussioncomment-3415737) how to authenticate via REST.

Let me know if you have any further questions.

Closing, not a bug.

**Comment by Haarolean** [comment]
If that's somehow not about REST -- I just checked the following on both master/v0.4.0 tags:

```
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.4.0
    ports:
      - 8080:8080
    depends_on:
      - kafka0
      - schemaregistry0
      - kafka-connect0
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8085
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083


      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: pass
```

Works perfectly fine.
