### ISSUE TITLE
No working sasl authentication

### ISSUE THREAD

**Issue by MrKribel** [provectus/kafka-ui#2947]
A friend asked me to deploy ui kafka, I thought I could do it quickly, but I couldn't do it...
My docker-composer:

```
version: '3'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:master
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./ssl:/opt/java/openjdk/lib/security/ssl
      - /usr/local/share/ca-certificates/Yandex/YandexCA.crt:/opt/java/openjdk/lib/security/YandexCA.crt
    environment:
      - KAFKA_CLUSTERS_0_NAME=yandex
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=rc1a-38ka7m24475e6tm8.mdb.yandexcloud.net:9091
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-512
      - KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_TYPE=JKS
      - KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION=/opt/java/openjdk/lib/security/ssl
      - KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD=pass12345678
      #- KAFKA_CLUSTERS_0_PROPERTIES_CLIENT_DNS_LOOKUP=use_all_dns_ips
      #- KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_TYPE=PEM
      #- KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_CERTIFICATES=/opt/java/openjdk/lib/security/YandexCA.crt
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username=test-user password=pass12345678;
 
```
When, i have error 
»  **_Error while creating AdminClient for Cluster yandex_**

via offset explorer connects...

I create ssl.jks like this:

```
sudo keytool -importcert \
             -alias YandexCA -file /usr/local/share/ca-certificates/Yandex/YandexCA.crt \
             -keystore ssl.jks -storepass 12345 \
             --noprompt
```

Please help me solve the problem😭
