### ISSUE TITLE
Crashes on IAM auth cluster

### ISSUE THREAD

**Issue by Fran-Rg** [provectus/kafka-ui#3024]
**Describe the bug**
It will be hard to describe if it's only 1 or many bugs but the cluster ends up with a yellow dot and trying to check the topics crashes the page.
There are multiple stack traces in the logs:
```

2022-12-05 14:26:10,459 WARN  [parallel-1] o.a.k.c.u.AppInfoParser: Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.admin.client:type=app-info,id=kafka-ui-app
	at java.management/com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1865)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:960)
```
and
```
2022-12-05 14:26:10,911 INFO  [kafka-admin-client-thread | kafka-ui-app] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-app] Node -1 disconnected.
2022-12-05 14:26:10,924 ERROR [scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler: Unexpected error occurred in scheduled task
java.lang.NullPointerException: null
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at com.provectus.kafka.ui.service.StatisticsCache.replace(StatisticsCache.java:26)
```

This is the cluster config:
```
2022-12-05 14:27:40,452 INFO  [parallel-1] o.a.k.c.a.AdminClientConfig: AdminClientConfig values: 
	bootstrap.servers = [<REMOVED>:9098]
	client.dns.lookup = use_all_dns_ips
	client.id = kafka-ui-app
	connections.max.idle.ms = 300000
	default.api.timeout.ms = 60000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = class software.amazon.msk.auth.iam.IAMClientCallbackHandler
	sasl.jaas.config = [hidden]
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.window.jitter = 0.05
	sasl.login.retry.backoff.max.ms = 10000
	sasl.login.retry.backoff.ms = 100
	sasl.mechanism = AWS_MSK_IAM
	sasl.oauthbearer.clock.skew.seconds = 30
	sasl.oauthbearer.expected.audience = null
	sasl.oauthbearer.expected.issuer = null
	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
	sasl.oauthbearer.jwks.endpoint.url = null
	sasl.oauthbearer.scope.claim.name = scope
	sasl.oauthbearer.sub.claim.name = sub
	sasl.oauthbearer.token.endpoint.url = null
	security.protocol = SASL_SSL
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
```

**Set up**
The kafka ui is deployed using helm chart: kafka-ui-0.4.6
This is the values:
```
envs:
    config:
      KAFKA_CLUSTERS_0_DISABLELOGDIRSCOLLECTION: "true"
      KAFKA_CLUSTERS_0_NAME: dev-events
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS: software.amazon.msk.auth.iam.IAMClientCallbackHandler
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: software.amazon.msk.auth.iam.IAMLoginModule
        required;
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: AWS_MSK_IAM
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_READONLY: "false"
      SERVER_SERVLET_CONTEXT_PATH: /kafka-ui
    secret:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: <REMOVED>:9098
  image:
    tag: master
  resources:
    limits:
      cpu: "0.25"
      memory: 1Gi
    requests:
      cpu: "0.25"
      memory: 1Gi
  serviceAccount:
    create: false
    name: kafka-ui
```

**Steps to Reproduce**

1. Create an aws serverless cluster
2. Deploy the helm with a service account linked to an IAM role granting access to the cluster
3. Check kafka-ui

**Expected behavior**
UI cluster with a green dot.
No stacktraces

**Additional context**
I used to have a provisioned cluster that doesn't implement any auth and it had never had any issue.
The kafka-ui is on: https://github.com/provectus/kafka-ui/commit/43ccca4 (using docker.io/provectuslabs/kafka-ui:master)
