### ISSUE TITLE
 WARN  [kafka-admin-client-thread | kafka-ui-admin-client-1673511535643] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-client-1673511535643] Connection to node -1 (/127.0.0.1:9092) could not be established. Broker may not be available.

### ISSUE THREAD

**Issue by patpatpat123** [provectus/kafka-ui#3221]
Hello team,

Since this is my first ever message in this project, wanted to say kudos. This project is very cool!

I am facing an issue, where the UI keeps saying ``` WARN  [kafka-admin-client-thread | kafka-ui-admin-client-1673511535643] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-client-1673511535643] Connection to node -1 (/127.0.0.1:9092) could not be established. Broker may not be available.```

Here is my DockerFile for reference:

```
version: "3.9"

services:

  kafka:
    networks: [ "mynetwork" ]
    container_name: kafka.mynetwork
    hostname: 127.0.0.1
    image: hexhex/kafka-kraft:0.0.10
    environment:
      ADVERTISED_LISTENERS: 127.0.0.1:9092
    ports:
      - 9092:9092

  kafka-ui:
    networks: [ "mynetwork" ]
    container_name: kafka-ui.mynetwork
    hostname: kafka-ui.mynetwork
    image: provectuslabs/kafka-ui
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=127.0.0.1:9092
    depends_on:
      - kafka

networks:
  mynetwork:
      name: mynetwork

```

I have applications sending and receiving messages without issue. Therefore, I can say the Kafka itself is working.

Yet, it seems there is an issue where the Kafka UI is not finding Kafka.

May I ask what did I do wrong please?
How to fix it please?

Thank you
