### ISSUE TITLE
Topic Messages: Preview AVRO broken in v0.5.0+

### ISSUE THREAD

**Issue by th0ger** [provectus/kafka-ui#3222]
**Describe the bug** (Actual behavior)
In v0.5.0 (and not currently fix on master), the preview feature of avro messages are garbagled:

![image](https://user-images.githubusercontent.com/26322144/212092253-a9a39b40-ac29-49cc-a7ea-1de30deee726.png)

**Expected behavior**
This is a regression, used to work in v0.4.0:

![image](https://user-images.githubusercontent.com/26322144/212092293-26a19dbc-8745-4e61-be37-60e941ad7b68.png)

**Steps to Reproduce**
```yaml
version: "3.8"
services:
    networks:
      - default
    ports:
      - "139:139"
      - "446:445"
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
      - "9092:9092"
      - "9101:9101"
    environment:
      HOSTNAME: "kafka"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,CLUSTER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://kafka:9094,CLUSTER://kafka:1337
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094,CLUSTER://:1337
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:1337
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.1
    container_name: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:1337'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.4.0  # Avro preview broken in v0.5.0
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - schema-registry
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: BG
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: 'http://schema-registry:8081'
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: kafka-connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: "http://kafka-connect:8083"

networks:
  default:
    external: true
    name: kafka_overlay_network
```

**Additional context**
Since new "Value Serde" options are implemented in v0.5.0, it's quite clear that some bug was introduced.
