### ISSUE TITLE
ALB ingress with wildcard not support pathType: Prefix

### ISSUE THREAD

**Issue by Dgadavin** [provectus/kafka-ui#3253]
Good day. I faced with problem when ALB ingress controller failed to build model because wildcard `/*` in path not supported with `pathType: Prefix`. 

Could you please add a value to override `pathType` in values.yaml?

**Set up**
Chart version: 0.4.2

**Steps to Reproduce**

Create ingress with such values
```
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=900
        external-dns.alpha.kubernetes.io/hostname: "kafka-ui.example.com"
        alb.ingress.kubernetes.io/certificate-arn: <CERT-ARN>
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
        alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect",
          "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode":
          "HTTP_301"}}'
        alb.ingress.kubernetes.io/group.name: prod-int

      path: "/*"
      host: "kafka-ui.example.com"
```
And you will have such error:
```
Failed build model due to ingress: dev/kafka-ui: prefix path shouldn't contain wildcards: /*
```

**Expected behavior**
Ingress work and model build without errors. 
For this `pathType` should be `ImplementationSpecific`
