### ISSUE TITLE
Status update: kafka-ui integration with Azure Event Hubs

### ISSUE THREAD

**Issue by dvrbanic-syntio** [provectus/kafka-ui#3267]
**Describe the bug**

We tried to connect Kafka UI to Event Hubs, and we've run to the same problem described here https://github.com/provectus/kafka-ui/issues/2441.

**Expected behavior**

A functioning connection with the azure event hub

**Set up**

Kafka-UI is setup with a standard docker compose, similar to the one on https://github.com/provectus/kafka-ui/issues/2441:
```
version: '2'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=prod-event-hub
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=***.servicebus.windows.net:9093
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=PLAIN
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG='org.apache.kafka.common.security.plain.PlainLoginModule required username="$$ConnectionString" password=***;'
```

**Additional context**

Related issue: 
https://github.com/provectus/kafka-ui/issues/2441 - The issue is still present, is there any update?
