### ISSUE TITLE
Github Oauth Configuration doesnt work

### ISSUE THREAD

**Issue by cnCloXie** [provectus/kafka-ui#3284]
**Describe the bug** (Actual behavior)

The github oauth configuration doesnt work which redirect the request to `https://<kafka-ui>/oauth2/authorization/github` complaining `ERR_TOO_MANY_REDIRECTS` when refer to https://github.com/provectus/kafka-ui/wiki/OAuth-Configuration#github

**Expected behavior**

Kafka ui can use the callback url to login and the roles permission are taking effect

**Set up**

**Steps to Reproduce**

1. Runtime and configuration

ImageTag: 43fcf6dce17283adc963f8661abe5b3e0410372d
Github Oauth APP Callback Url: `https://<kafka-ui>/login/oauth2/github`
And config as below

```
  config.yml: |-
    auth:
      type: OAUTH2
      oauth2:
        client:
          github:
            provider: github
            clientId: xxx
            clientSecret: xxx
            scope:
              - read:org
            user-name-attribute: login
            custom-params:
              type: github
    kafka:
      clusters:
      - xxx
        name: dev
    management:
      health:
        ldap:
          enabled: false
    spring:
      security:
        oauth2: github

```

**Screenshots**

**Additional context**

**Comment by Haarolean** [comment]
Hey,

it seems like you have set the wrong redirect URL in your github oauth app.

I'll show an example:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/1494347/215701847-9ddce090-2334-4475-8875-4b8880cbaa94.png">

The config:
```
    auth:
      type: "OAUTH2"
      oauth2:
        client:
          github:
            provider: github
            clientId: derp
            clientSecret: derp
            redirect-uri: https://www.kafka-ui.provectus.io/login/oauth2/code/github
            scope:
              - read:org
            user-name-attribute: login
            custom-params:
              type: github
```
