### ISSUE TITLE
Google auth not working

### ISSUE THREAD

**Issue by abhinavgautam07** [provectus/kafka-ui#3293]
**Describe the bug**

I have attached a config below going by the documentation. But the Google auth didn't come. I didn't get an option to log in. It directly takes me to the main page.

**Set up**

1. App version->  64077d
2. Helm chart version, if you use one -> 0.5.0, but have edited the deployment to use the master image
3. Any IAAC configs

```
replicaCount: 1

image:
  registry: docker.io
  repository: provectuslabs/kafka-ui
  pullPolicy: IfNotPresent

yamlApplicationConfig:
   kafka:
     clusters:
       - name: production-cluster
         bootstrapServers: kafka-cluster-kafka-advertiser-0.ms-kafka.svc.cluster.local:9092
   spring:
     security:
       oauth2:
     auth:
       type: OAUTH2
       oauth2:
         client:
           google:
             provider: google
             clientId: XXXX.apps.googleusercontent.com
             clientSecret: GOCSPX-YYYY
             redirect_uri: http://kafka.urbancompany.com/login/oauth2/code/google
             user-name-attribute: email
             custom-params:
               type: google
               allowedDomain: urbancompany.com

podLabels:
  app: kafka-ui
  service-type: kafka
  service-name: ms-kafka
  team: platform
## Set field schema as HTTPS for readines and liveness probe
##
probes:
  useHttpsScheme: false

service:
  type: LoadBalancer
  port: 443
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
    service.beta.kubernetes.io/aws-load-balancer-subnets: UC-Prod-Private-Subnet- apse1a
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:<region>:99999:certificate/aaaa-bbbb-ccc-ddd
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
resources:
  requests:
    memory: 4Gi
    cpu: "4"
  limits:
    memory: 4Gi
    cpu: "4"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80


affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: nodetype
              operator: In
              values:
                - cpu-optimised
                - memoryoptimised
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - ap-southeast-1a

```

**Steps to Reproduce**

1. Apply the given config

**Expected behavior**

I should be getting an option to login.
**Screenshots**

**Additional context**
Have made a Cloudflare entry to map `kafka.urbancompany.com` to the given loadbalancer
