### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by systemctl-reload** [provectus/kafka-ui#3298]
Hi I updated  kafka-ui 0.4.0 to 0.5.0 and I have this error

`INFO  [main] o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker: Bean 'org.springframework.security.config.annotation.method.configuration.ReactiveMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.ReactiveMethodSecurityConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-02-01 17:51:22,973 WARN  [main] o.s.b.w.r.c.AnnotationConfigReactiveWebServerApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'OAuthLogoutSuccessHandler' defined in URL [jar:file:/kafka-ui-api.jar!/BOOT-INF/classes!/com/provectus/kafka/ui/config/auth/logout/OAuthLogoutSuccessHandler.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultOidcLogoutHandler' defined in class path resource [com/provectus/kafka/ui/config/auth/OAuthSecurityConfig.class]: Unsatisfied dependency expressed through method 'defaultOidcLogoutHandler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientRegistrationRepository' defined in class path resource [com/provectus/kafka/ui/config/auth/OAuthSecurityConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.client.registration.InMemoryReactiveClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception; nested exception is java.lang.IllegalArgumentException: registrations cannot be null or empty`

I'm using AUTH_TYPE: OAUTH2 param for sso

![error](https://user-images.githubusercontent.com/17292868/216063027-4a23d1ec-67e7-4ae8-b7c3-a0cda7bbd1bc.PNG)

**Comment by Dugong42** [comment]
I found the same issue in `v0.5.0` and it seems to be fixed in `master`.

Could we get a FIX release for this bug ?

For reference, my OIDC login configuration via a Keycloak instance:

```yaml
auth.type: OAUTH2
spring.security.oauth2.client:
  registration:
    keycloak:
      clientid: kafka-ui
      clientsecret: <secret>
      scope: openid
      provider: keycloak
  provider:
    keycloak:
      issuer-uri: https://<keycloak_instance>/auth/realms/<realm>
```

**Comment by dyonathakramer** [comment]
@Dugong42  @systemctl-reload 
Update: 
You need to change the way you do the config, see "breaking changes" for details
https://github.com/provectus/kafka-ui/releases/tag/v0.5.0

**Comment by Dugong42** [comment]
I moved `issuer-uri` to `auth.oauth2.client.keycloak`, since it was the only one I had defined in the `provider`.
I got it working with the following config:

```yaml
auth:
  type: OAUTH2
  oauth2:
    client:
      keycloak:
        clientId: kafka-ui-local
        clientSecret: <secret>
        scope: openid
        issuer-uri: https://<keycloak_instance>/auth/realms/<realm>
        user-name-attribute: preferred_username
        client-name: keycloak
        provider: keycloak
        custom-params:
          type: keycloak
```

This could be added to the examples in [OAuth Configuration documentation ](https://github.com/provectus/kafka-ui/wiki/OAuth-Configuration). Although I believe it would be better to add some documentation about what fields are actually required in the general case.

**Comment by Haarolean** [comment]
See breaking changes in the latest changelog
https://github.com/provectus/kafka-ui/releases/tag/v0.5.0
I plan to make the app fail with a clear message since nobody does actually read changelogs.

**Comment by lework** [comment]
How do I change the environment variables?

```yaml
    environment:
      - AUTH_TYPE=OAUTH2
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENTID=xxxx
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENTSECRET=xxxx
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTH0_ISSUER_URI=https://sso.com/oidc
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_SCOPE=openid
      - SERVER_FORWARDHEADERSSTRATEGY=native
```

**Comment by Dugong42** [comment]
If I understood correctly, you're asking how to convert your config that uses environment variables to the new 0.5.0 format.

If so, I think you just need to migrate to the new format (lookup the docs and changelog mentioned earlier) and replace child relationships as well as special characters with "_"

For instance in your case your provider name seems to be "auth0": 

```yml
auth:
  oauth2:
    client:
      auth0:
        clientId: kafka-ui
        ...
``` 

Becomes: 

```yml
environment:
  - AUTH_OAUTH2_CLIENT_KEYCLOAK_CLIENTID=kafka-ui
```
