### ISSUE TITLE
Read only mode for Kafka Connect

### ISSUE THREAD

**Issue by maver1ck** [provectus/kafka-ui#3342]
**Describe the bug** (Actual behavior)
I enable read only mode for Kafka Cluster. Under this mode I'm able to remove Kafka Connect connector.

**Expected behavior**
I should't be able to remove Kafka Connect connector in read-only mode.

**Set up**

How do you run the app? Please provide as much info as possible:
1. App version: v0.5.0 (027d9b4)
2. Helm chart version, if you use one: kafka-ui-0.5.2
3. Any IAAC configs
```
yamlApplicationConfig:
  kafka:
    clusters:
      - name: bds
        bootstrapServers: "kafka:9092"
        schemaRegistry: "http://kafka-cp-schema-registry.default.svc:8081"
        readOnly: true
        kafkaConnect:
        - name: connect
          address: "http://kafka-cp-kafka-connect.default.svc:8083"
```

**Steps to Reproduce**
1. Go to Kafka Connect connectors.
2. Click on ... next to connector.
3. Remove it

**Screenshots**

![image](https://user-images.githubusercontent.com/4006010/218564089-c2fa692f-d87f-4c4b-91ce-5f1e743afae1.png)
