### ISSUE TITLE
Authentication using SCRAM-SHA-512

### ISSUE THREAD

**Issue by KozyrevychYaroslav** [provectus/kafka-ui#3350]
Hi @provectus-it
I need to connect to kafka servers from my work. However, I get  error `kafka-ui |org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512`.
My docker compose file:
```
version: '2.6'
services:

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8001:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: xxxx:9092,xxyy:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="username" password="password";'
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /ca-dv.ks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: password
    volumes:
      - ./ssl/ca-dv.ks:/ca-dv.ks
```
 I would like to note that using the current data I can connect to the servers using the Offset Explorer UI.
