### ISSUE TITLE
Basic Authentication not working

### ISSUE THREAD

**Issue by oferwess** [provectus/kafka-ui#3426]
**Describe the bug**
I am using your Kafka-UI helm chart version 0.5.0 to deploy kafka-ui on my k8s cluster.
I am trying to configure basic authentication for kafka-ui but no success.
When enabling auth section (in the values.yaml I keep getting "invalid credetionals" error. (if I disbae it, I can access the kafka-ui without any issue).
I tried several methods:

First I've tried using a username/password authentication on cleat text inside the helm as well as encoded password

```
yamlApplicationConfig:
  kafka:
    clusters:
      - name: kafka-cluster-k8s
        bootstrapServers: "kafka-headless.kafka.svc.cluster.local:9092"
  spring:
    security:
      oauth2:
  auth:
    type: basic
    enabled: true
    basic:
      realm: Kafka-UI
      users:
        username: MyUser
        password: MyPassword
        roles:
          - admin
  management:
    enabled: true
    health:
      ldap:
        enabled: false
```
 
Then, I tried using secret which I have created in the k8s on kafka-ui namespace and this is how my values.yaml looked like:

```
yamlApplicationConfig:
  kafka:
    clusters:
      - name: kafka-cluster-k8s
        bootstrapServers: "kafka-headless.kafka.svc.cluster.local:9092"
  spring:
    security:
      oauth2:
  auth:
    type: basic
    enabled: true
    basic:
      realm: Kafka-UI
      secret:
        name: kafka-ui-secret
        usernameKey: MyUser
        passwordKey: MyPassword
        roles:
          - admin
  management:
    enabled: true
    health:
      ldap:
        enabled: false

```

I tried from several browsers and I also cleared my cache after each attempt.

**Set up**

Running on-prem k8s cluster version v1.18.2
All workers and Control planes are running on Ubuntu 18.04.6 OS
Kafka-UI helm chart version 0.5.0 

**Steps to Reproduce**

To reproduce, just copy the yamlApplicationConfig section to valuse.yaml and run the helm install command on the k8s cluster.

**Expected behavior**

login should succeed

**Comment by Haarolean** [comment]
Hi, I honestly don't know where have you got all these properties. 
The basic authentication works like this as env vars:
```
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: pass
```
so with helm it'd be:
```
yamlApplicationConfig:
  auth:
    type: login_form
  spring
    security:
      user:
       name: admin
       pass: pass
```
