### ISSUE TITLE
Request for a `global.imageRegistry` parameter

### ISSUE THREAD

**Issue by yardenshoham** [provectus/kafka-ui#3437]
**Describe the bug**
This allows anyone that uses Bitnami helm charts to have this chart as a subchart without explicitly specifying `image.registry`.

**Set up**
I have a helm chart with 5 subcharts:
- service A (respects `global.imageRegistry`)
- service B (respects `global.imageRegistry`)
- service C (respects `global.imageRegistry`)
- kafka from Bitnami (respects `global.imageRegistry`)
- kafka-ui (I have to manually set `kafka-ui.image.registry` to match `global.imageRegistry`)

**Steps to Reproduce**
Setup a helm-chart with kafka-ui as a subchart.

**Expected behavior**
In my ideal setup my `values.yaml` looks like:
```yaml
global:
  imageRegistry: container-registry.my-domain.com
```

But because of the way things are now, I have to write it like this:
```yaml
global:
  imageRegistry: container-registry.my-domain.com

kafka-ui:
  image:
    registry: container-registry.my-domain.com
```

I'm willing to contribute the code to make this happen if the idea is accepted.
