### ISSUE TITLE
Inner protobuf reference not resolved

### ISSUE THREAD

**Issue by arun-avudainayagam** [provectus/kafka-ui#3482]
Hi,
I am running kafka-ui as a docker compose setup.
I am using the latest image,

```
REPOSITORY                  TAG       IMAGE ID       CREATED       SIZE
provectuslabs/kafka-ui      master    24e98722942f   2 hours ago   261MB
```

```
---
version: '2'
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:master
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: dev
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: stream.com:9092
      KAFKA_CLUSTERS_0_READONLY: true
      kafka.clusters.0.serde.0.name: ProtobufFile
      kafka.clusters.0.serde.0.topicKeysPattern: "stream_topic"
      kafka.clusters.0.serde.0.topicValuesPattern:: "stream_topic"
      kafka.clusters.0.serde.0.properties.protobufFiles.0: /proto/envelope.proto
      kafka.clusters.0.serde.0.properties.protobufFiles.1: /proto/common.proto
      kafka.clusters.0.serde.0.properties.protobufFiles.2: /proto/order.proto
      kafka.clusters.0.serde.0.properties.protobufFiles.3: /proto/orderDefinition.proto
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.stream_topic: "Envelope"
    volumes:
      - /Users/kafka/proto:/proto
```

When I execute docker-compose up, I get this error,
```
kafka-ui  | Caused by: com.google.protobuf.Descriptors$DescriptorValidationException: Order.orderDefinition: "OrderDefinition" is not defined.
kafka-ui  | 	at com.google.protobuf.Descriptors$DescriptorPool.lookupSymbol(Descriptors.java:2562)
kafka-ui  | 	at com.google.protobuf.Descriptors$FieldDescriptor.crossLink(Descriptors.java:1559)
kafka-ui  | 	at com.google.protobuf.Descriptors$FieldDescriptor.access$1400(Descriptors.java:1057)
kafka-ui  | 	at com.google.protobuf.Descriptors$Descriptor.crossLink(Descriptors.java:1000)
kafka-ui  | 	at com.google.protobuf.Descriptors$Descriptor.access$1200(Descriptors.java:648)
kafka-ui  | 	at com.google.protobuf.Descriptors$FileDescriptor.crossLink(Descriptors.java:600)
kafka-ui  | 	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:321)
kafka-ui  | 	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:289)
kafka-ui  | 	at io.confluent.kafka.schemaregistry.protobuf.dynamic.DynamicSchema.init(DynamicSchema.java:290)
kafka-ui  | 	at io.confluent.kafka.schemaregistry.protobuf.dynamic.DynamicSchema.<init>(DynamicSchema.java:224)
kafka-ui  | 	at io.confluent.kafka.schemaregistry.protobuf.dynamic.DynamicSchema.<init>(DynamicSchema.java:55)
kafka-ui  | 	at io.confluent.kafka.schemaregistry.protobuf.dynamic.DynamicSchema$Builder.build(DynamicSchema.java:385)
kafka-ui  | 	at io.confluent.kafka.schemaregistry.protobuf.ProtobufSchema.toDynamicSchema(ProtobufSchema.java:1318)
```

My order.proto is referencing orderDefinition.proto, like this,

```
import "common.proto";
import "orderDefinition.proto";
```

Can you please help?

**Comment by arun-avudainayagam** [comment]
Hi,

Just an update, specifying it as a protobufFilesDir works,

```
---
version: '2'
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:master
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: dev
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: stream.com:9092
      KAFKA_CLUSTERS_0_READONLY: true
      kafka.clusters.0.serde.0.name: ProtobufFile
      kafka.clusters.0.serde.0.properties.protobufFilesDir: /proto
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.stream_topic: "Envelope"
    volumes:
      - /Users/kafka/proto:/proto
```

Can someone please tell me how to change the above environment tags as yaml themselves?
