### ISSUE TITLE
SchemaRegistry/Protobuf: topic deserialization doesn't work

### ISSUE THREAD

**Issue by demimurg** [provectus/kafka-ui#3483]
**Describe the bug** (Actual behavior)
Despite the fact that the protobuf schema is created for topic (\<topic\>-value pattern), deserialization in browse window doesn't work

**Expected behavior**
Messages in topic showed in human readable format according to schema registry

**Set up**
Docker Image v0.0.6 (also tried v0.5.2, master, latest)

**Steps to Reproduce**
1. Run kafka, schema-registry and kafkaui
```yaml
version: "3"
volumes:
    kafka_data:
        driver: local
services:
    kafka:
        image: bitnami/kafka:latest
        ports:
            - "9092:9092"
        volumes:
            - "kafka_data:/bitnami/kafka"
        environment:
            # all parameters required for kraft
            - KAFKA_ENABLE_KRAFT=yes
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
             # you should add "127.0.0.1 kafka" to /etc/hosts to connect outside from docker
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
            - ALLOW_PLAINTEXT_LISTENER=yes
    schema-registry:
        image: confluentinc/cp-schema-registry:latest
        ports:
            - "8081:8081"
        depends_on:
            - kafka
        environment:
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
    kafkaui:
        image: provectuslabs/kafka-ui:v0.6.0
        ports:
            - "8080:8080"
        depends_on:
            - kafka
            - schema-registry
        environment:
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
            KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
```
2. Add protobuf schema for test topic in schema registry
3. Send protobuf messages from your client to kafka topic (i used go app)
4. Look at test topic messages with `Value Serde = SchemaRegistry` selected

**Screenshots**
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/40828320/224482138-41ef0365-09a9-4647-b45c-3890efb6e060.png">
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/40828320/224482326-6d3c2984-53b9-4828-8f8b-6d9da205941b.png">

**Additional context**
Make it work only with [Protobuf Serde](https://github.com/provectus/kafka-ui/blob/master/documentation/guides/Serialization.md) without SchemaRegistry
