### ISSUE TITLE
Cognito OAuth invalid logout redirect URI

### ISSUE THREAD

**Issue by VikramAhuja** [provectus/kafka-ui#3528]
Hi,

I have setup kafka-ui with Cognito for Oauth. Login seems to be working fine but on logout redirect url seems to be invalid.

it should be `https://kafka-ui.xxxxx.com/logout` but instead it is `http://kafka-ui.xxxxx.com/logout`

I have highlighted same in the following screenshot
![kafka-ui-https-to-http](https://user-images.githubusercontent.com/1784431/226630523-da0e05b5-98ce-4cb5-b479-8389b83fa7b7.JPG)

configuration for cognito Oauth looks like

```
auth:
  type: OAUTH2
  oauth2:
    client:
      cognito:
        clientId: <client-id>
        clientSecret: <client-secret>
        scope: openid
        client-name: kafka-ui
        provider: cognito
        redirect-uri: <redirect-uri>
        authorization-grant-type: authorization_code
        issuer-uri: https://cognito-idp.eu-west-2.amazonaws.com/<pool-id>
        jwk-set-uri: https://cognito-idp.eu-west-2.amazonaws.com/<pool-id>/.well-known/jwks.json
        user-name-attribute: username
        custom-params:
          type: cognito
          logoutUrl: https://<domain>.auth.eu-west-2.amazoncognito.com/logout
```

In AWS Cognito I have configured `https://kafka-ui.xxxxx.com/logout` as one of allowed logout urls. Since it is coming as `http` there is error on the UI. Even though error says missing redirect_uri but here error is because of mismatch of redirect_uri. It works fine with localhost.

Can someone tell me why is this happening? Is there any configuration missing here?
