### ISSUE TITLE
RBAC with GitHub Enterprise Server

### ISSUE THREAD

**Issue by sti-yvi** [provectus/kafka-ui#3542]
Hello,

I am trying to use Kafka UI with OAuth and RBAC in an isolated environment (no Internet access).

I configured OAuth for GitHub Enterprise Server 3.6.8 like this:
```yaml
auth:
  type: OAUTH2
  oauth2:
    client:
      github:
        provider: github
        clientId: xxx
        clientSecret: xxx
        scope:
          - read:org
        user-name-attribute: login
        custom-params:
          type: github
        authorization-uri: https://xxx/login/oauth/authorize
        token-uri: https://xxx/login/oauth/access_token
        user-info-uri: https://xxx/api/v3/user
```
It works fine: I can login to Kafka UI by using GitHub Enterprise.

However, I cannot use RBAC, because Kafka UI is trying to connect to `api.github.com`. It looks like some parts are hardcoded in GithubAuthorityExtractor.java:
https://github.com/provectus/kafka-ui/blob/5c723d9b4491019bc6de01e3746b5b86d70f0560/kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/GithubAuthorityExtractor.java#L28
Also, like this one: `.uri("/user/orgs")`

It would be great to use `UserInfoUri` for RBAC with GitHub provider.
