### ISSUE TITLE
Can not Connect Eventhub with Kafka UI

### ISSUE THREAD

**Issue by hueiyuan** [provectus/kafka-ui#3587]
## Description
Based on the newest release version, kafka ui can support connect Azure Eventhub with kafka protocol. When we try to connect it follow below docker-compose yaml example, and always show below error message:
* docker-compose.yaml example
```yaml
version: '3'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:master
    container_name: kafka-ui
    ports:
      - "18080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=xxxxxxxx
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=xxxxxx.servicebus.windows.net:9093
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=PLAIN
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username='$ConnectionString' password='Endpoint=sb://xxxxxxx.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxxxxxxxxxxxx';
```

* Error Message
```
kafka-ui  | 2023-03-29 14:46:24,913 WARN  [kafka-admin-client-thread | kafka-ui-admin-1680101182-1] o.a.k.c.n.Selector: [AdminClient clientId=kafka-ui-admin-1680101182-1] Unexpected error from hdinsighteventhubs.servicebus.windows.net/20.51.14.101 (channelId=-1); closing connection
kafka-ui  | java.lang.RuntimeException: non-nullable field authBytes was serialized as null
kafka-ui  | 	at org.apache.kafka.common.message.SaslAuthenticateResponseData.read(SaslAuthenticateResponseData.java:137)
kafka-ui  | 	at org.apache.kafka.common.message.SaslAuthenticateResponseData.<init>(SaslAuthenticateResponseData.java:86)
kafka-ui  | 	at org.apache.kafka.common.requests.SaslAuthenticateResponse.parse(SaslAuthenticateResponse.java:81)
kafka-ui  | 	at org.apache.kafka.common.requests.AbstractResponse.parseResponse(AbstractResponse.java:187)
kafka-ui  | 	at org.apache.kafka.common.requests.AbstractResponse.parseResponse(AbstractResponse.java:109)
kafka-ui  | 	at org.apache.kafka.clients.NetworkClient.parseResponse(NetworkClient.java:729)
kafka-ui  | 	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.receiveKafkaResponse(SaslClientAuthenticator.java:576)
kafka-ui  | 	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.receiveToken(SaslClientAuthenticator.java:508)
kafka-ui  | 	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:302)
kafka-ui  | 	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:181)
kafka-ui  | 	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
kafka-ui  | 	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
kafka-ui  | 	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:560)
kafka-ui  | 	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1415)
kafka-ui  | 	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1346)
kafka-ui  | 	at java.base/java.lang.Thread.run(Thread.java:833)
kafka-ui  | 2023-03-29 14:46:24,915 INFO  [kafka-admin-client-thread | kafka-ui-admin-1680101182-1] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-1680101182-1] Node -1 disconnected.
kafka-ui  | 2023-03-29 14:46:24,915 WARN  [kafka-admin-client-thread | kafka-ui-admin-1680101182-1] o.a.k.c.NetworkClient:[AdminClient clientId=kafka-ui-admin-1680100319-1] Connection to node -1 (xxxx.servicebus.windows.net/20.83.192.11:9093) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.
```

If you have any ideas or related solution can share, I will be appreciated it. Thank you.
