### ISSUE TITLE
ingress doesn't return static resources

### ISSUE THREAD

**Issue by survivant** [provectus/kafka-ui#364]
I wanted to add Ingress for kafka-ui but it's not working  (but working fine with the nodePort.  What is missing to get it to work with Ingress ?

http://10.1.34.6/kafka-ui

![image](https://user-images.githubusercontent.com/191879/114077721-1a50d500-9876-11eb-87ae-ade95eeabb6e.png)

here my config
````
kafka-ui:
  enabled: true
  service:
    type: NodePort
    nodePort: 32002

  envs:
    config:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-cp-kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: kafka-cp-zookeeper:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://kafka-cp-schema-registry:8081
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-cp-kafka-connect:8083

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    enabled: true
    hosts:
    - host: ""
      paths:
      - /kafka-ui(/|$)(.*)
````

here the ingress generated
````
...
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: kafka-ui
            port:
              number: 80
        path: /kafka-ui(/|$)(.*)
        pathType: ImplementationSpecific
````

I can compare it with granafa
http://10.1.34.6/grafana   redirect to  http://10.1.34.6/grafana/login

````
....
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: monitoring-stack-grafana
            port:
              number: 80
        path: /grafana(/|$)(.*)
        pathType: Prefix

````

is it a resource mapping that is missing in Spring boot to handle that ?

**Comment by RustamGimadiev** [comment]
Hi @survivant, thanks for opening this issue, we able to reproduce that behavior of the ingress and has looking for a solution, unfortunately, we cannot provide any workaround

**Comment by survivant** [comment]
@RustamGimadiev thanks for the feedback.  the workaround that I use, if a nodePort for now.

**Comment by andormarkus** [comment]
Hi @RustamGimadiev 

We are using AWS EKS, our ingress controller is `aws-load-balancer-controller` which[ does not support](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1268) `rewrite-target` like `nginx.ingress` does.

We are doing [path based fanout](https://docs.giantswarm.io/advanced/ingress/configuration/#path-based-fanout) like `foobaa.com/airflow` `foobaa.com/kafka`  `foobaa.com/spark`, however once I set ingress path to non-root path I can not reach the UI anymore.

Non-working configuration:
```yaml
ingress:
  enabled: true
  hosts:
    - host:
      paths:
        - /kafkaui/*
```

Working configuration:
```yaml
ingress:
  enabled: true
  hosts:
    - host:
      paths:
        - /*
```

Can you add capability of running on a non-root path either by default or by setting the base path in the configuration?

Thank you!
