### ISSUE TITLE
Broker version doesn't change without kafka ui restart

### ISSUE THREAD

**Issue by timchenko-a** [provectus/kafka-ui#3749]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Kafka UI doesn't automatically update broker version information is case of broker is updated. It requires kafka ui restart.

### Expected behavior

Broker is updated -> kafka ui automatically detects new version.

### Your installation details

1. Kafka UI version: ef0dacb v0.6.1
2. No, I run just like a plain jar on EC2, systemd managed.
3. The next command is used to run kafka-ui:
`java -Xmx512M -Xms512M -Dspring.config.additional-location=/opt/config.yaml --add-opens java.rmi/javax.rmi.ssl=ALL-UNNAMED -jar /opt/kafka-ui.jar`
/opt/config.yaml content(only 1 cluster here, we have more, but config is pretty much the same everywhere):
```
---
kafka:
  clusters:
    - name: CLUSTER_NAME
      bootstrapServers: SERVER_1_URL:9093,SERVER_2_URL:9093,SERVER_3_URL:9093
      readonly: true
      properties:
        security:
          protocol: SASL_PLAINTEXT
        sasl:
          mechanism: SCRAM-SHA-256
          jaas:
            config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="USERNAME" password="PASSWORD";'
      schemaRegistry: http://SCHEMA_REGISTRY_URL:8081
```

### Steps to reproduce

Setup kafka cluster, non-latest version;
Add it to kafka UI. It will detect cluster's version correctly;
Upgrade kafka cluster;
Check broker version in kafka UI, it will stay the same;
Restart kafka UI, now new broker version will be detected.

### Additional context

Want to understand it it's a bug, or an expected behaviour :)
