### ISSUE TITLE
 kafka-ui restart occasionally

### ISSUE THREAD

**Issue by cataglyphis** [provectus/kafka-ui#3782]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

1. kafka ui service restart occasionally

### Your installation details

1. kafka-ui: 0.6.2
2. k8s: 1.25.6
3. helm chart: 0.6.2
4. kafka-ui config

```
envs:
  config:
    AUTH_TYPE: LDAP
    KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka.dev.svc:9092
    KAFKA_CLUSTERS_0_NAME: dev
    KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka.qa.svc:9092
    KAFKA_CLUSTERS_1_NAME: qa
    KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: kafka.pre.svc:9092
    KAFKA_CLUSTERS_2_NAME: pre
    KAFKA_CLUSTERS_3_BOOTSTRAPSERVERS: kafka-external.qa.svc:9092
    KAFKA_CLUSTERS_3_NAME: external-qa
    KAFKA_CLUSTERS_4_BOOTSTRAPSERVERS: kafka.ops.svc:9092
    KAFKA_CLUSTERS_4_NAME: ops
    SPRING_LDAP_ADMINPASSWORD: xxx
    SPRING_LDAP_ADMINUSER: xxx
    SPRING_LDAP_DN_PATTERN: xxx
    SPRING_LDAP_URLS: xxx
    SPRING_LDAP_USERFILTER_SEARCHBASE: xxx
    SPRING_LDAP_USERFILTER_SEARCHFILTER: xxx
image:
  tag: v0.6.2
ingress:
  enabled: true
  host: xxx
  ingressClassName: nginx
  path: /
  tls:
    enabled: true
resources:
  requests:
    cpu: 250m
    memory: 500Mi
  limits:
    cpu: 250m
    memory: 1Gi
```

### Steps to reproduce

1. can not reproduce, this issue occurs occasionally

### Screenshots

![kafka-ui-cpu](https://user-images.githubusercontent.com/9249983/236377090-8d290a46-0fad-429e-b957-66663906ea4c.png)

### Logs

![kafka-ui-log](https://user-images.githubusercontent.com/9249983/236377490-ab14d2d6-da53-4454-a43f-88ee7ecb2c08.png)
