### ISSUE TITLE
SR: Expand schema versioning pattern to support Apicurio

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#3841]
I tested successfully an integration with Apicurio Registry using the Confluent compatibility API endpoint.

This is the `values.yaml` file used for my deployment using the Helm Chart:

```yaml
yamlApplicationConfig:
  kafka:
    clusters:
      - name: my-cluster
        bootstrapServers: my-kafka-kafka-bootstrap.amq-streams-demo.svc:9092
        schemaRegistry: http://service-registry-service:8080/apis/ccompat/v6
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
```

I found that it is working smoothly, only one detail about the schemas versioning. Confluent API only use integers (e.g: `1`, `2`, ...), however Apicurio Registry can use other versioning (e.g: `1.0`, `1.1` ...). If your schemas in Apicurio Registry use that versioning mechanism, then Kafka-UI fails with an exception not well managed.

HTH

_Originally posted by @rmarting in https://github.com/provectus/kafka-ui/issues/1786#issuecomment-1552857453_
