### ISSUE TITLE
RBAC: Filters not applied using LDAP role access

### ISSUE THREAD

**Issue by MxFbk** [provectus/kafka-ui#3920]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Hi all, 

after successful access with LDAP auth mechanism and corresponding role config, as explained into [previous discussion](https://github.com/provectus/kafka-ui/discussions/3909), I tried to config a custom role with just few permissions on TOPICS and CONSUMERS, but no luck.

All topics are visible and not filtered and I succeeded in creation/deletion of topics even if specified just "view" permission.

No LOG useful even at debug level.

### Expected behavior

Topics/Consumers filtering .

### Your installation details

APP version 0.7.0

CONFIG:

compose.yml

```
 kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8083:8080"
    restart: always
    user: "0"
    environment:
      LOGGING_LEVEL_ROOT: debug
      LOGGING_LEVEL_COM_PROVECTUS: debug
      TZ: Europe/Rome
      KAFKA_ADMIN-CLIENT-TIMEOUT: 60000
      #######
      AUTH_TYPE: LDAP
      SPRING_LDAP_URLS: ldap://ldap_server:389
      SPRING_LDAP_BASE: CN=***********,OU=company,OU=tech_users,DC=g,DC=b,DC=s
      SPRING_LDAP_ADMIN-USER: CN=***********,OU=company,OU=tech_users,DC=g,DC=b,DC=s
      SPRING_LDAP_ADMINP-ASSWORD: **************************
      SPRING_LDAP_USER-FILTER-SEARCH-BASE: OU=obp,OU=users,DC=g,DC=b,DC=s
      #SPRING_LDAP_USER-FILTER-SEARCH-FILTER: "(&(sAMAccountName={0})(memberOf=CN=FBK_AWX_PRE,OU=company,OU=tech_users,DC=g,DC=b,DC=s)(memberOf=CN=FBK_AWX_PRO,OU=company,OU=tech_users,DC=g,DC=b,DC=s))"
      SPRING_LDAP_USER-FILTER-SEARCH-FILTER: "(sAMAccountName={0})"
      SPRING_LDAP_GROUP-FILTER-SEARCH-BASE: OU=company,OU=tech_users,DC=g,DC=b,DC=s
      SPRING_CONFIG_ADDITIONAL-LOCATION: /roles.yml
      #      AUTH_TYPE: "LOGIN_FORM"
      #      SPRING_SECURITY_USER_NAME: team
      #      SPRING_SECURITY_USER_PASSWORD: **************************
      #######
      KAFKA_CLUSTERS_0_NAME: fbk_kafka_tst
      ... ... ... ...
      #######
      KAFKA_CLUSTERS_1_NAME: fbk_kafka_pre
      ... ... ... ...
      #######
      JAVA_OPTS: ... ... ...
    volumes:
      - type: bind
        source: /opt/kafkaui/logs
        target: /opt/kafkaui/logs
      - type: bind
        source: /opt/kafkaui/config
        target: /opt/kafkaui/config
      - /etc/localtime:/etc/localtime:ro
      - /opt/kafkaui/roles.yml:/roles.yml
```

roles.yml

```
rbac:
  roles:
    - name: "FBK_AWX_PRO"
      clusters:
        - fbk_kafka_tst
        - fbk_kafka_pre
      subjects:
        - provider: ldap
          type: group
          value: "FBK_AWX_PRO"
      permissions:
        - resource: topic
          value: "fake.*"
          actions:
            - view
            - massages_read

        - resource: consumer
          value: "fake.*"
          actions:
            - view
```

### Steps to reproduce

ENABLING roles through "roles.yml" I can log in but see everithing without filters.

### Screenshots

I can see 144 pages of topics and the last doesn't match regex "fake.*".

![topics_not_filered_20230609](https://github.com/provectus/kafka-ui/assets/135245439/e350bf40-9f0d-49e6-a2f6-a17f43e84514)

No matching topics would be visible if regex filter was applied correctly as show here:

![topics_not_filered_2_20230609](https://github.com/provectus/kafka-ui/assets/135245439/2f7d858f-4fce-42e7-a2b2-423311f72f9e)

Same issue on consumers filter:

![consumers_not_filtered_20230609](https://github.com/provectus/kafka-ui/assets/135245439/46d680ab-98ad-463a-8333-010dd547d47c)

### Logs

I wasn't able to found any useful trace on logs, even using DEBUG level.

**Comment by Haarolean** [comment]
@MxFbk do you get a 403 if you try to open the topic which shouldn't be accessible from the list?

**Comment by MxFbk** [comment]
Hi @Haarolean,

I'm trying to look for topic: **fbk.sme.update-bank-instruction-items-domain-status**.
I can see it, click on it and read messages.

I don't know if something wrong on my config.

From browser inspection all calls are 200 OK.

![tpoic_should_be_filtered_20230612](https://github.com/provectus/kafka-ui/assets/135245439/7b9d4f8c-848d-4d27-8f96-2de7baeedf66)

**Comment by Haarolean** [comment]
@MxFbk Please provide the output of `/api/authorization` endpoint

**Comment by MxFbk** [comment]
Hi @Haarolean,

thanks for suggestion.
Here are the api call output as requested:

`{"rbacEnabled":false,"userInfo":{"username":"GBS07272","permissions":[]}}`

I can add what I can see on my config and container.

ROLES CONFIG:
```
[root@fbkppawx /opt/kafkaui]$ cat roles.yml
rbac:
  roles:
    - name: "FBK_AWX_PRO"
      clusters:
        - fbk_kafka_tst
        - fbk_kafka_pre
      subjects:
        - provider: ldap
          type: group
          value: "FBK_AWX_PRO"
      permissions:
        - resource: topic
          value: "fake.*"
          actions:
            - view
            - massages_read

        - resource: consumer
          value: "fake.*"
          actions:
            - view
```

CONTAINER CONFIG => roles.yml mount into the container
```
[root@fbkppawx /opt/kafkaui]$ cat kafkaui.yml | grep roles
      #SPRING_CONFIG_ADDITIONAL-LOCATION: /roles.yml
      - /opt/kafkaui/roles.yml:/roles.yml
```

CONTAINER FS CHECK => roles.yml is in place
```
[root@fbkppawx /opt/kafkaui]$ docker ps -a | grep kafka
9f058d503e25   provectuslabs/kafka-ui:latest   "/bin/sh -c 'java --…"   11 days ago    Up 11 days    0.0.0.0:8083->8080/tcp            kafka-ui
[root@fbkppawx /opt/kafkaui]$ docker exec -ti 9f058d503e25 /bin/sh -c 'ls -ltr / | grep *.yml'
-rw-r--r--    1 root     root           433 Jun  9 11:32 roles.yml
```

What I've missed or wrongly configured?

Thanks a lot

Massimiliano
