### ISSUE TITLE
Wizard: SASL_SSL generates wrong case of 'useKeytab'

### ISSUE THREAD

**Issue by pombuppa** [provectus/kafka-ui#3930]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Create new cluster with SASL_SSL with kerberos will generate wrong sasl.jaas.config

```
  - bootstrapServers: xxx:9092,xxx:9092,xxx:9092
    name: test-cluster
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: GSSAPI
      sasl.jaas.config: com.sun.security.auth.module.Krb5LoginModule required useKeytab="true"
        keyTab="/etc/kafkaui/uploads/kfuat_BDH_CES.client.keytab-1686539412" storeKey="true"
        principal="priciple@KAFKA.SECURE";
      sasl.kerberos.service.name: bigfoot
    readOnly: true
    ssl:
      truststoreLocation: /etc/kafkaui/uploads/my.client.truststore.jks-1686539188
      truststorePassword: xxxxx
```
      
This will cause the following error
```
Caused by: javax.security.auth.login.LoginException: Configuration Error - useKeyTab should be set to true to use the keytab
```

### Expected behavior

sasl.jaas.config must include useKeyTab (with uppercase T) and without double quote between boolean value.

### Your installation details

Commit: fdd9ad9

### Steps to reproduce

Create new cluster with SASL_SSL with kerberos and keytab file.
