### ISSUE TITLE
add service.type LoadBalancer

### ISSUE THREAD

**Issue by eldengates** [provectus/kafka-ui#3950]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Upon reviewing the current chart(0.7.0), I noticed that it lacks support for the service type LoadBalancer when utilizing a defined load balancer IP. It would be incredibly beneficial if we could incorporate a feature that addresses this limitation. Having the ability to specify a load balancer IP for LoadBalancer services would greatly enhance our deployment options and enable us to fine-tune our networking configuration effortlessly

### Describe the feature you're interested in

I am expecting to render something like
```
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-ext
spec:
  loadBalancerIP: 172.25.39.235
  ports:
  - name: tcp-ext
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: kafka-ui
  type: LoadBalancer
```

### Version you're running

fdd9ad9
