### ISSUE TITLE
Still getting `blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.` error

### ISSUE THREAD

**Issue by eka43** [provectus/kafka-ui#4017]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Hi, I tried to set SSO but I am still getting the errors below in inspect-network section in the browser.

```
Access to script at '(url) &client_id=(client id)&scope=openid%20profile%20email%20groups&state=(code)
&redirect_uri=(url)' (redirected from '(url)/assets/index-43f1ddca.js') 
from origin '(url)' has been blocked by CORS policy
: No 'Access-Control-Allow-Origin' header is present on the requested resource.

(url) GET (keycloak url)/auth?response_type=code&client_id=(client id)&scope=openid%20profile%20email%20groups&state=(code)&redirect_uri=(uri) net::ERR_FAILED 303
```
and I got the invalid credential error.
<img width="770" alt="Screenshot 2023-07-06 at 2 36 23 PM" src="https://github.com/provectus/kafka-ui/assets/28684240/f64439e3-5447-40b7-abd6-f43699e1706b">[](url)
Once I deployed the app, I can access to the application initially(with the CORS error), but when I logged out and log in again, this error(Invalid credential error) happens.

### Your installation details

This is my config file with keycloak

```
# kafka-ui/charts/kafka-ui/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: kafka-ui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/version: v0.7.1
    helm.sh/chart: kafka-ui-0.7.1
data:
  config.yml: |-
    auth:
      type: OAUTH2
      oauth2:
        client:
          keycloak:
            clientId: (client id)
            clientSecret: (Client password)
            scope: openid,profile,email,groups
            issuer-uri: (issuer- uri)
            authorization-grant-type: authorization_code
            client-name: (keycloak realm name)
            user-name-attribute: preferred_username
            provider: keycloak
            custom-params:
              type: oauth
              roles-field: groups
    management:
      health:
        ldap:
          enabled: false              
    rbac:
      roles:
        - name: "readonly"
          clusters:
            - a
            - b
            - c               
          subjects:
            - provider: oauth
              type: role
              value: "role1"                                     
          permissions:
            - resource: clusterconfig
              actions: [ "view" ]
            - resource: topic
              value: ".*"
              actions: 
                - VIEW
                - MESSAGES_READ
            - resource: consumer
              value: ".*"
              actions: [ view ]
            - resource: schema
              value: ".*"
              actions: [ view ]
            - resource: connect
              value: ".*"
              actions: [ view ]
            - resource: acl
              value: ".*"
              actions: [ view ]      
        - name: "admin"
          clusters:
            - a
            - b
            - c            
          subjects:
            - provider: oauth
              type: role
              value: "role2"
          permissions:
            - resource: applicationconfig
              actions: all
            - resource: clusterconfig
              actions: all
            - resource: topic
              value: ".*"
              actions: all
            - resource: consumer
              value: ".*"
              actions: all
            - resource: schema
              value: ".*"
              actions: all
            - resource: connect
              value: ".*"
              actions: all
            - resource: ksql           
              actions: [ execute ]
            - resource: acl
              value: ".*"            
              actions: [ view, edit ]
```

Deployment
```
# kafka-ui/charts/kafka-ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: kafka-ui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/version: v0.7.1
    helm.sh/chart: kafka-ui-0.7.1
    first_owner: e2.kang
    second_owner: t.ding     
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kafka-ui
      app.kubernetes.io/name: kafka-ui      
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kafka-ui
        app.kubernetes.io/name: kafka-ui
    spec:
      serviceAccountName: kafka-ui
      serviceAccount: kafka-ui      
      containers:
        - name: kafka-ui
          image: 'docker.io/provectuslabs/kafka-ui:v0.7.1'
          imagePullPolicy: IfNotPresent
          env:
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
            - name: SPRING_CONFIG_ADDITIONAL-LOCATION
              value: /kafka-ui/config.yml                                              
            - name: KAFKA_CLUSTERS_0_NAME
              value: {{ .Values.kafkaUiClusterName0 }}
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: {{ .Values.kafkaUiBootstrapservers0 }}
            - name: KAFKA_CLUSTERS_0_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secret-0
                  key: username              
            - name: KAFKA_CLUSTERS_0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secret-0
                  key: password
            - name: KAFKA_UI_KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: kafka-ui-secret
                  key: clientId                  
            - name: KAFKA_UI_KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-ui-secret
                  key: clientSecret              
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
              value: SCRAM-SHA-512
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
              value: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_CLUSTERS_0_USERNAME}" password="${KAFKA_CLUSTERS_0_PASSWORD}";'
          {{- if .Values.kafkaUiClusterName1 }} 
            - name: KAFKA_CLUSTERS_1_NAME
              value: {{ .Values.kafkaUiClusterName1 }}
            - name: KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS
              value: {{ .Values.kafkaUiBootstrapservers1 }}           
            - name: KAFKA_CLUSTERS_1_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secret-1
                  key: username              
            - name: KAFKA_CLUSTERS_1_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secret-1
                  key: password                   
            - name: KAFKA_CLUSTERS_1_PROPERTIES_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: KAFKA_CLUSTERS_1_PROPERTIES_SASL_MECHANISM
              value: SCRAM-SHA-512
            - name: KAFKA_CLUSTERS_1_PROPERTIES_SASL_JAAS_CONFIG
              value: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_CLUSTERS_1_USERNAME}" password="${KAFKA_CLUSTERS_1_PASSWORD}";'
          {{- end}}
          {{- if .Values.kafkaUiClusterName2 }} 
            - name: KAFKA_CLUSTERS_2_NAME
              value: {{ .Values.kafkaUiClusterName2 }}
            - name: KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS
              value: {{ .Values.kafkaUiBootstrapservers2 }}            
            - name: KAFKA_CLUSTERS_2_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secret-2
                  key: username              
            - name: KAFKA_CLUSTERS_2_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secret-2
                  key: password                   
            - name: KAFKA_CLUSTERS_2_PROPERTIES_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: KAFKA_CLUSTERS_2_PROPERTIES_SASL_MECHANISM
              value: SCRAM-SHA-512
            - name: KAFKA_CLUSTERS_2_PROPERTIES_SASL_JAAS_CONFIG
              value: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_CLUSTERS_2_USERNAME}" password="${KAFKA_CLUSTERS_2_PASSWORD}";'
          {{- end}}                                                                           
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
              ephemeral-storage: 20Gi
            requests:
              cpu: 200m
              memory: 256Mi
              ephemeral-storage: 15Gi              
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: kafka-ui-yaml-conf
              mountPath: /kafka-ui/
      volumes:
        - name: kafka-ui-yaml-conf
          configMap: 
            name: kafka-ui
            defaultMode: 420    
```

### Steps to reproduce

Deploy the application with those helm charts.
Set the keycloak outside.

**Comment by mikhail-putilov** [comment]
That behavior is most probably connected to context path.
Try setting up `SERVER_SERVLET_CONTEXT_PATH`, I had similar issue and it was not resolved until Kafka UI started under some context path. 

FYI My working setup has a disabled auth `auth.type: disabled` right now with `SERVER_SERVLET_CONTEXT_PATH`.

values.yaml is:
```yaml
fullnameOverride: kafka-ui
yamlApplicationConfigConfigMap: # feed our config map as an additional config
  name: kafka-ui-additional
  keyName: config.yaml
envs:
  config:
    # This part of YAML will go into readiness/liveness probes, and in a configmap
    # Without it, it won't work behind reverse proxy
    SERVER_SERVLET_CONTEXT_PATH: /kafka-ui
```
And `kafka-ui-additional` config map contains file with name `config.yaml`:
```yaml
kafka:
  clusters:
    - name: yaml
      bootstrapServers: ...
auth:
  type: disabled
management:
  health:
    ldap:
      enabled: false
server:
  forward-headers-strategy: native
```
