### ISSUE TITLE
Authentication is not working when the number of pods is more than 1

### ISSUE THREAD

**Issue by eka43** [provectus/kafka-ui#4055]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Hi all, last time I opened this [issue](https://github.com/provectus/kafka-ui/issues/4017) but I did not get any response.

I debugged the issue for awhile, and found that the number of pods is related to this bug.

When I set the `replicaCount:2` or   `autoscaling: enabled: true`, then the authentication did not work and show
Invalid Credential error.

Only `replicaCount:1` works.

This happens in[ Basic Authentication](https://docs.kafka-ui.provectus.io/configuration/authentication/basic-authentication) and [Oauth2](https://docs.kafka-ui.provectus.io/configuration/authentication/oauth2) - Generic configuration(Keycloak).

### Expected behavior

I should login to kafka-ui regardless of the number of pods

### Your installation details

1. App version: 
[56fa824](https://github.com/provectus/kafka-ui/commit/56fa824)
v0.7.1

2. Helm chart: 
```
apiVersion: v2
name: kafka-ui
description: A Helm chart for kafka-UI
type: application
version: 0.7.2
appVersion: v0.7.1
icon: https://github.com/provectus/kafka-ui/raw/master/documentation/images/kafka-ui-logo.png
dependencies:
 - name: kafka-ui
   version: 0.7.2
   repository: https://provectus.github.io/kafka-ui-charts
   ```

3. Application config
```
  yamlApplicationConfig:
    auth:
      type: OAUTH2
      oauth2:
        client:
          keycloak:
            clientId: ${KAFKA_UI_KEYCLOAK_CLIENT_ID}
            clientSecret: ${KAFKA_UI_KEYCLOAK_PASSWORD}
            scope: openid,profile,email,groups
            issuer-uri: (url)
            authorization-grant-type: authorization_code
            client-name: (realm name)
            user-name-attribute: email
            provider: keycloak
            custom-params:
              type: oauth
              roles-field: groups 
```

### Steps to reproduce

Set the `replicaCount:2` or   `autoscaling: enabled: true` in values.yaml with authentication(login form, SSO)
https://github.com/provectus/kafka-ui-charts/blob/main/charts/kafka-ui/values.yaml

### Screenshots

<img width="770" alt="Screenshot 2023-07-06 at 2 36 23 PM" src="https://github.com/provectus/kafka-ui/assets/28684240/f7178ee3-f4a2-45a3-abc2-9a0fbba50858">

### Additional context

HA(High available) architecture is required.

**Comment by eka43** [comment]
Can you please put `keycloak.cors=true` in `application.properties`
Reference: https://stackoverflow.com/questions/41137766/keycloak-cors-filter-spring-boot

**Comment by papirosko** [comment]
same problem with okta authorisation and 2 replicas:
```
    auth:
      type: OAUTH2
      oauth2:
        client:
          okta:
            clientId: ${AUTH_OKTA_CLIENTID}
            clientSecret: ${AUTH_OKTA_CLIENTSECRET}
            scope: [ 'openid', 'profile', 'email', 'groups' ] # default for okta + groups for rbac
            client-name: Okta
            provider: okta
```


changing to
```
spec:
  replicas: 1
```
solves the problem
