### ISSUE TITLE
BE: ACL: Read-only mode requires non-expected permissions

### ISSUE THREAD

**Issue by timchenko-a** [provectus/kafka-ui#4080]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Kafka-ui in read-only mode seems to require some additional edit ACLs.

### Expected behavior

No logs of Denied Operation in kafka-authorizer.log logs when required ACLs for read-only more have been set.

### Your installation details

First of all: from kafka-ui side everything works fine, it's fully functional and there are no issues in logs. But on kafka side I can see lots of errors in kafka-authorizer.log file

App version: 56fa824 v0.7.1
No helm chart, installing using jar
Example cluster configuration from kafka-ui config file:
```
kafka:
  clusters:
    - name: cluster-1
      bootstrapServers: host-1:9093,host-2:9093,host-3:9093
      readonly: true
      properties:
        security:
          protocol: SASL_PLAINTEXT
        sasl:
          mechanism: SCRAM-SHA-256
          jaas:
            config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka-ui" password="...";'
      schemaRegistry: http://schema-registry:8081
      kafkaConnect:
        - name: connect-source-1
          address: http://connect-source-1:8083
        - name: connect-source-2
          address: http://connect-source-2:8083
        - name: connect-source-3
          address: http://connect-source-3:8083
        - name: connect-sink-1
          address: http://connect-sink-1:8083
        - name: connect-sink-2
          address: http://connect-sink-2:8083
        - name: connect-sink-3
          address: http://connect-sink-3:8084
        - name: connect-sink-4
          address: http://connect-sink-4:8083
```

ACLs for kafka-ui user, based on [doc](https://docs.kafka-ui.provectus.io/configuration/permissions/required-acls):
```
  kafka-ui = {
    cluster = {
      "kafka-cluster" = [
        { operation = "Describe" },
        { operation = "DescribeConfigs" },
      ]
    }

    group = {
      "*" = [
        { operation = "Describe" }
      ]
    }

    topic = {
      "*" = [
        { operation = "Read" },
        { operation = "DescribeConfigs" },
      ]
    }
  }
```

Related logs from kafka-ui side:
```
journalctl -u kafka-ui -n 100 | grep -i cluster-1
Aug 02 08:52:31 kafka-ui java[317520]: 2023-08-02 08:52:31,114 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: cluster-1
Aug 02 08:52:55 kafka-ui java[317520]: 2023-08-02 08:52:55,327 DEBUG [parallel-2] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: cluster-1
Aug 02 08:53:02 kafka-ui java[317520]: 2023-08-02 08:53:02,216 DEBUG [parallel-2] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: cluster-1
Aug 02 08:53:25 kafka-ui java[317520]: 2023-08-02 08:53:25,327 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: cluster-1
Aug 02 08:53:31 kafka-ui java[317520]: 2023-08-02 08:53:31,247 DEBUG [parallel-2] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: cluster-1
Aug 02 08:53:55 kafka-ui java[317520]: 2023-08-02 08:53:55,327 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: cluster-1
Aug 02 08:54:02 kafka-ui java[317520]: 2023-08-02 08:54:02,172 DEBUG [parallel-2] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: cluster-1
Aug 02 08:54:25 kafka-ui java[317520]: 2023-08-02 08:54:25,327 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: cluster-1
Aug 02 08:54:32 kafka-ui java[317520]: 2023-08-02 08:54:32,371 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: cluster-1
```

Kafka error logs:
```
tail -n 50 kafka-authorizer.log
{"short_message":"Principal = User:kafka-ui is Denied Operation = IdempotentWrite from host = kafka-ui-ip on resource = Cluster:LITERAL:kafka-cluster","full_message":"Principal = User:kafka-ui is Denied Operation = IdempotentWrite from host = kafka-ui-ip on resource = Cluster:LITERAL:kafka-cluster","timestamp":1.690965595329E9,"level":6,"facility":"logstash-gelf","LoggerName":"kafka.authorizer.logger","SourceSimpleClassName":"SimpleAclAuthorizer$BaseAuthorizer","SourceClassName":"kafka.security.auth.SimpleAclAuthorizer$BaseAuthorizer","Time":"2023-08-02 08:39:55,329","Severity":"INFO","SourceLineNumber":66,"Thread":"data-plane-kafka-request-handler-23","SourceMethodName":"logAuditMessage"}
{"short_message":"Principal = User:kafka-ui is Denied Operation = AlterConfigs from host = kafka-ui-ip on resource = Cluster:LITERAL:kafka-cluster","full_message":"Principal = User:kafka-ui is Denied Operation = AlterConfigs from host = kafka-ui-ip on resource = Cluster:LITERAL:kafka-cluster","timestamp":1.690965595329E9,"level":6,"facility":"logstash-gelf","LoggerName":"kafka.authorizer.logger","SourceSimpleClassName":"SimpleAclAuthorizer$BaseAuthorizer","SourceClassName":"kafka.security.auth.SimpleAclAuthorizer$BaseAuthorizer","Time":"2023-08-02 08:39:55,329","Severity":"INFO","SourceLineNumber":66,"Thread":"data-plane-kafka-request-handler-23","SourceMethodName":"logAuditMessage"}
{"short_message":"Principal = User:kafka-ui is Denied Operation = Alter from host = kafka-ui-ip on resource = Cluster:LITERAL:kafka-cluster","full_message":"Principal = User:kafka-ui is Denied Operation = Alter from host = kafka-ui-ip on resource = Cluster:LITERAL:kafka-cluster","timestamp":1.690965595329E9,"level":6,"facility":"logstash-gelf","LoggerName":"kafka.authorizer.logger","SourceSimpleClassName":"SimpleAclAuthorizer$BaseAuthorizer","SourceClassName":"kafka.security.auth.SimpleAclAuthorizer$BaseAuthorizer","Time":"2023-08-02 08:39:55,329","Severity":"INFO","SourceLineNumber":66,"Thread":"data-plane-kafka-request-handler-23","SourceMethodName":"logAuditMessage"}
{"short_message":"Principal = User:kafka-ui is Denied Operation = Create from host = kafka-ui-ip on resource = Cluster:LITERAL:kafka-cluster","full_message":"Principal = User:kafka-ui is Denied Operation = Create from host = kafka-ui-ip on resource = Cluster:LITERAL:kafka-cluster","timestamp":1.690965595329E9,"level":6,"facility":"logstash-gelf","LoggerName":"kafka.authorizer.logger","SourceSimpleClassName":"SimpleAclAuthorizer$BaseAuthorizer","SourceClassName":"kafka.security.auth.SimpleAclAuthorizer$BaseAuthorizer","Time":"2023-08-02 08:39:55,329","Severity":"INFO","SourceLineNumber":66,"Thread":"data-plane-kafka-request-handler-23","SourceMethodName":"logAuditMessage"}
{"short_message":"Principal = User:kafka-ui is Denied Operation = ClusterAction from host = kafka-ui-ip on resource = Cluster:LITERAL:kafka-cluster","full_message":"Principal = User:kafka-ui is Denied Operation = ClusterAction from host = kafka-ui-ip on resource = Cluster:LITERAL:kafka-cluster","timestamp":1.690965595329E9,"level":6,"facility":"logstash-gelf","LoggerName":"kafka.authorizer.logger","SourceSimpleClassName":"SimpleAclAuthorizer$BaseAuthorizer","SourceClassName":"kafka.security.auth.SimpleAclAuthorizer$BaseAuthorizer","Time":"2023-08-02 08:39:55,329","Severity":"INFO","SourceLineNumber":66,"Thread":"data-plane-kafka-request-handler-23","SourceMethodName":"logAuditMessage"}

```

### Steps to reproduce

Not quite sure, we have this error across all our clusters which are based on 7.3.3 and 6.2.7 confluent platform. But can try to describe if needed.
