### ISSUE TITLE
Not all brokers are shown in the brokers page

### ISSUE THREAD

**Issue by papirosko** [provectus/kafka-ui#4089]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

I am running 2 bitnami kafka containers: 

```
version: '3.8'

x-kafka-common: &kafka-common
  image: 'bitnami/kafka:latest'
  ports:
    - "9092"
  networks:
    - kafka


x-kafka-env-common: &kafka-env-common
  ALLOW_PLAINTEXT_LISTENER: 'yes'
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093
  KAFKA_KRAFT_CLUSTER_ID: abcdefghijklmnopqrstuv
  KAFKA_CFG_PROCESS_ROLES: controller,broker
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093

services:

  kafka-0:
    <<: *kafka-common
    environment:
      <<: *kafka-env-common
      KAFKA_CFG_NODE_ID: 0
    volumes:
      - kafka_0_data:/bitnami/kafka

  kafka-1:
    <<: *kafka-common
    environment:
      <<: *kafka-env-common
      KAFKA_CFG_NODE_ID: 1
    volumes:
      - kafka_1_data:/bitnami/kafka


  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    volumes:
      - ./kafka-ui/config.yml:/etc/kafkaui/dynamic_config.yaml
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka-0
      - kafka-1
    networks:
      - kafka
    ports:
      - '8080:8080' 

```

with this configuration:
```
auth:
  type: LOGIN_FORM

spring:
  security:
    user:
      name: admin
      password: admin

kafka:
  clusters:
    - bootstrapServers: kafka-0:9092,kafka-1:9092
      name: kafka
```

on the http://localhost:8080/ui/clusters/kafka/brokers page I can see only 1 broker out of 2. Both brokers are online 

### Expected behavior

Brokers page should show all brokers even some of them are in the failed state.

### Your installation details

[56fa824](https://github.com/provectus/kafka-ui/commit/56fa824)
v0.7.1

### Steps to reproduce

just use the docker-compose above

### Screenshots

<img width="728" alt="image" src="https://github.com/provectus/kafka-ui/assets/1061424/fb92aee9-bad2-43c4-897f-243420c3fa70">

### Logs

this is the response from the http://localhost:8080/api/clusters/kafka/brokers

```[
    {
        "id": 0,
        "host": "99e3cc4fec98",
        "port": 9092,
        "bytesInPerSec": null,
        "bytesOutPerSec": null,
        "partitionsLeader": null,
        "partitions": null,
        "inSyncPartitions": null,
        "partitionsSkew": null,
        "leadersSkew": null
    },
    {
        "id": 1,
        "host": "5c2093551961",
        "port": 9092,
        "bytesInPerSec": null,
        "bytesOutPerSec": null,
        "partitionsLeader": 1,
        "partitions": 1,
        "inSyncPartitions": 1,
        "partitionsSkew": null,
        "leadersSkew": null
    }
]```

### Additional context

no
