### ISSUE TITLE
Add separate section for Schema Registry and Kafka Connect in both config and UI

### ISSUE THREAD

**Issue by patrickpang** [provectus/kafka-ui#4120]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Deployments of Schema Registry and Kafka Connect can be separate from Kafka clusters. For example, we can have a centralized schema registry deployment with reference to many Kafka clusters, and we can have multiple Kafka Connect clusters connecting to multiple Kafka clusters.

Currently both config and UI put Schema Registry and Kafka Connect under Kafka clusters. We would need to duplicate these configs in each cluster if we are sharing them across Kafka clusters:

```yaml

kafka:
  clusters:
    - name: kafka-cluster-1
      bootstrapServers: xxx

      schemaRegistry: centralized-schema-registry
      schemaRegistryAuth:
        username: xxx
        password: xxx

      kafkaConnect:
        - name: kafka-connect-cluster-1
          address: xxx
        - name: kafka-connect-cluster-2
          address: xxx

    - name: kafka-cluster-2
      bootstrapServers: xxx

      schemaRegistry: centralized-schema-registry
      schemaRegistryAuth:
        username: xxx
        password: xxx

      kafkaConnect:
        - name: kafka-connect-cluster-1
          address: xxx
        - name: kafka-connect-cluster-2
          address: xxx
```

### Describe the feature you're interested in

It would be good if we can have a separate section of schema registry, and kafka connect.

In config it can look like:

```yaml

kafka:
  clusters:
    - name: kafka-cluster-1
      bootstrapServers: xxx
    - name: kafka-cluster-2
      bootstrapServers: xxx

  kafkaConnect:
    - name: kafka-connect-cluster-1
      address: xxx
    - name: kafka-connect-cluster-2
      address: xxx
  
  schemaRegistry: 
    - name: centralized-schema-registry
      auth:
          username: xxx
          password: xxx
```

In UI it can look like:

![image](https://github.com/provectus/kafka-ui/assets/944420/607c814e-0410-49bb-8d54-396087141969)

### Version you're running

56fa824

### Additional context

For backwards compatibility and other use cases, we can still keep the original config, and add this as an extra.
