### ISSUE TITLE
FE: RBC: Messages tab erroneously available

### ISSUE THREAD

**Issue by fallen-up** [provectus/kafka-ui#4125]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Frontend makes the tab "messages" available for topics that you don't have access to.

For example: only "notifications.*" are allowed, but the processing is wrong and the tab is available on the site for all topics that contain the "notifications" not at the beginning of the title.
At the same time the backend works normally and does not allow reading, you can see 403 errors in the developer tab.

### Expected behavior

The messages tab should be available only for allowed topics.

### Your installation details

version: 0.7.1 (latest)

### Steps to reproduce

```
      permissions:
        - resource: topic
          value: ".*"
          actions: [ "view" ]
        - resource: topic
          value: "notifications.*"
          actions: [ "view" , "messages_read" ]
```

### Screenshots

![image](https://github.com/provectus/kafka-ui/assets/11389898/649fc05c-e6af-4665-81a0-67939792732a)
![image](https://github.com/provectus/kafka-ui/assets/11389898/cd3d659b-e65e-49a9-b228-1b364e66caee)
