### ISSUE TITLE
Serde Issue with Custom Schema Registry Naming

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#4173]
### Discussed in https://github.com/provectus/kafka-ui/discussions/4109

<div type='discussions-op-text'>

<sup>Originally posted by **PabloLec** August 11, 2023</sup>
Hello,

I have a problem with Serde, most likely related to the names of my Schema Registry. 
My schema registry is well configured in the Kafka UI, it shows up correctly on the left side bar, and it's also visible under "Value Serde" on the topic screen.

However, it doesn't seem to be working; I get a tooltip saying "Fallback serde was used", but there's no error in the console.

Unfortunately, my topics aren't using the TopicRecordNameStrategy, and it's not feasible to modify them.

In practice, for instance, I have the topic "contract" and its corresponding subject "avrocontractevent". The naming format is thus "avro[TOPIC]event". For your information, my schemas are correct and are being used by applications.

My configuration is as follows:
```
  kafka:
    clusters:
      -
        name: local
        bootstrapServers: kafka-broker:9092
        schemaRegistry: http://kafka-schema-registry:8081
        schemaNameTemplate: "avro%sevent"
```

I tried using `schemaNameTemplate`, but to no avail. Do you see any issues with this configuration, or have any leads to explore?

Thank you for your assistance.

PS: I'm using docker image `provectuslabs/kafka-ui:latest`</div>
