### ISSUE TITLE
LDAP audit logs

### ISSUE THREAD

**Issue by netscrol2016** [provectus/kafka-ui#4174]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Describe the feature you're interested in

It is necessary to see who performed what actions with topics and when they entered the system.

### Describe alternatives you've considered

I looked all issue the problems and documentation, but did not find anything suitable

### Version you're running

latest

**Comment by Haarolean** [comment]
#2998
```
      KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED: 'true'
      KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED: 'true'
      KAFKA_CLUSTERS_0_AUDIT_level: 'ALTER_ONLY'
```
There are two levels of audit: ALL and ALTER_ONLY, the second one is the default one.

**Comment by Haarolean** [comment]
I believe it works with LDAP authentication as well, tested it recently myself. Let me know if there's something else I can help with.

**Comment by netscrol2016** [comment]
Thank you for such a fast reply. But where are audit logs written? Where to see them? I use this configuration to run
```
version: "3.9"
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=172.16.6.55:9092
      - SPRING_LDAP_URLS=ldap://172.16.6.248:389
      - SPRING_LDAP_BASE=dc=in,dc=4u,dc=com
      - SPRING_LDAP_ADMIN_USER=uid=kafka-ldap,cn=users,cn=accounts,dc=in,dc=4u,dc=com
      - SPRING_LDAP_ADMIN_PASSWORD=dmGpN
      - SPRING_LDAP_USER_FILTER_SEARCH_BASE=cn=users,cn=accounts,dc=in,dc=4u,dc=com
      - SPRING_LDAP_USER_FILTER_SEARCH_FILTER=(&(uid={0})(memberOf=cn=kafka-access,cn=groups,cn=accounts,dc=in,dc=4u,dc=com))
      - SPRING_LDAP_GROUP_FILTER_SEARCH_BASE=cn=groups,cn=accounts,dc=in,dc=4u,dc=com
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED=true
      - KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED=true
      - KAFKA_CLUSTERS_0_AUDIT_level=ALL
```
