### ISSUE TITLE
SunCertPathBuilderException when viewing topic detailed view running docker-compose

### ISSUE THREAD

**Issue by mvassli** [provectus/kafka-ui#4192]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

When i start kafka-ui through docker-compose i have problems viewing topic details. When i go to my cluster -> topics and click the topic name, the page is visible for two seconds before i am redirected to http://localhost:8080/404

In log i see error `Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

If i start kafka-ui with docker run and manually add the cluster instead, i do not have any problems view topic details/messages at all.
`docker run -it -p 8080:8080 -e DYNAMIC_CONFIG_ENABLED=true provectuslabs/kafka-ui`

I have also tried adding  DYNAMIC_CONFIG_ENABLED to docker-compose and validated the SASL_SSL settings in the GUI. When clicking "Validate" i am told the cluster config is valid.  

Viewing topics schema in schema registry is also working as expected. 

Note that i have added `network_mode: host` to my docker-compose because i was having DNS issues and were unable to resolve the bootstrap servers. All bootstrap servers and schema registry are self-hosted in company network with private dns. 

### Your installation details

Version [v0.7.](https://github.com/provectus/kafka-ui/commit/56fa824)

```
---
version: '2'
services:

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    network_mode: host
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: kreditt-bi
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: REDACTED:9092,REDACTED:9092,hda-REDACTED:9092,hda-REDACTED:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: https://REDACTED
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="REDACTED" password="REDACTED";'
      KAFKA_CLUSTERS_0_SSL_TRUSTSTORE_LOCATION: /truststore.jks
      KAFKA_CLUSTERS_0_SSL_TRUSTSTORE_PASSWORD: 'REDACTED'
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_TYPE: JKS
      KAFKA_CLUSTERS_0_SCHEMAREGISTRYSSL_TRUSTSTORELOCATION: /truststore.jks
      KAFKA_CLUSTERS_0_SCHEMAREGISTRYSSL_TRUSTSTOREPASSWORD:  'REDACTED'
    volumes:
      - ./truststore.jks:/truststore.jks

```

### Steps to reproduce

1. `docker-compose -f docker-compose.yml up`
2. Open localhost:8080
3. Click "topics" under my cluster
4. Click the topic name

Topic detailed view is visible for 2-5 seconds before i am redirected to 404 error page. 

### Logs

[logs.txt](https://github.com/provectus/kafka-ui/files/12520917/logs.txt)

### Additional context

docker on rhel 8 distro

**Comment by Haarolean** [comment]
Hi, please provide the full stacktrace

**Comment by mvassli** [comment]
The logs are attached

**Comment by mvassli** [comment]
> Hi, please provide the full stacktrace

The complete logs are attached

**Comment by Haarolean** [comment]
Okay, I see.
That's related to the schema registry, and there should be no difference between running it via plain docker or via docker-compose. 

1) Can you verify that you're running the same version both ways? 
2) Is your SR certificate a self-signed one?

**Comment by mvassli** [comment]
> Okay, I see. That's related to the schema registry, and there should be no difference between running it via plain docker or via docker-compose.
> 
> 1. Can you verify that you're running the same version both ways?
> 2. Is your SR certificate a self-signed one?

1. Yes, it is the same
2. Yes, it is self-signed

**Comment by Haarolean** [comment]
@mvassli that looks suspicious. Can you share the version hash from the upper left corner for both your instances?

**Comment by mvassli** [comment]
> @mvassli that looks suspicious. Can you share the version hash from the upper left corner for both your instances?

@Haarolean 
I followed your [instructions](https://github.com/provectus/kafka-ui/discussions/4193) on adding truststore to config.yaml. I don't know why, but moving my config to a separate file resolved the problem with SunCertPathException. I can't see any obvious reasons why it should make a difference..

docker-compose.
```
---
version: '2'
services:

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    network_mode: host
    ports:
      - 8080:8080
    environment:
      SPRING_CONFIG_ADDITIONAL-LOCATION: /config.yml
    volumes:
      - ./truststore.jks:/truststore.jks
      - ./config.yml:/config.yml
```
config.yml
```
kafka:
  clusters:
     -
      name: REDACTED
      bootstrapServers: REDACTED:9092,REDACTED:9092,REDACTED:9092,REDACTED:9092
      schemaRegistry: https://REDACTED
      properties:
        security:
          protocol: SASL_SSL
        sasl:
          jaas:
            config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="REDACTED" password="REDACTED";'
          mechanism: SCRAM-SHA-512
      ssl:
        truststore-location: /truststore.jks
        truststore-password: REDACTED
      schema-registry-ssl:
        truststore-location: /truststore.jks
        truststore-password: REDACTED
```
