### ISSUE TITLE
OAUTH2 supported by keycloak broke out of the blue with no config changes

### ISSUE THREAD

**Issue by cpapad** [provectus/kafka-ui#4194]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

We are using `kafka-ui` `v0.7.1` for some time now deployed in kubernetes with no problems whatsoever. 
Out of the blue OAUTH2 stopped working and the login ended with the following error.
The peculiar that this is not consistent it resolved after a day or so and reoccured after a week or so and have not been able to reproduce it. 
We have captured through chrome the network between a working and a broken instance and the flow and payloads are identical.

### Expected behavior

Login flow to be completed with no errors.

### Your installation details

1. v0.7.1 [56fa824](https://github.com/provectus/kafka-ui/commit/56fa824)
2. 0.7.2
3.

``` yaml
      volumeMounts:
        - mountPath: /etc/kafka/stores
          name: kafka-ui
          readOnly: true
      volumes:
        - name: kafka-ui
          secret:
            secretName: kafka-ui-vault-secret-binaries
      resources:
        limits:
          cpu: 600m
          memory: 1024Mi
        requests:
          cpu: 300m
          memory: 800Mi
      yamlApplicationConfig:
        auth:
          type: OAUTH2
          oauth2:
            client:
              auth0:
                clientId: kafka-ui-admin
                provider: auth0
                scope: openid,email,profile
                authorization_grant_type: authorization_code
                user-name-attribute: preferred_username
                redirect-uri: https://****/login/oauth2/code/auth0
                jwk-set-uri: https://****/auth/realms/master/protocol/openid-connect/certs
                authorization-uri: https://****/auth/realms/master/protocol/openid-connect/auth
                token-uri: https://****/auth/realms/master/protocol/openid-connect/token
                user-info-uri: https://****/auth/realms/master/protocol/openid-connect/userinfo
                custom-params:
                  type: auth0
                  logoutUrl: https://****/logout
      envs:
        config:
          KAFKA_CLUSTERS_0_READONLY: "false"
          KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-stg-shared-workable-staging.aivencloud.com:24451
          KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
          KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /etc/kafka/stores/client.truststore.jks
          KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /etc/kafka/stores/client.keystore.p12
          KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_TYPE: PKCS12

```

### Steps to reproduce

This occurs by itself and have not found a way to reproduce it in some cases it happens and in others it does not with the exact same configuration

### Screenshots

![Screenshot 2023-09-05 at 5 48 44 PM](https://github.com/provectus/kafka-ui/assets/37328944/d849e9b5-5d91-4ee3-b4a3-d10e08e931a6)

### Logs

Nothing specific was logged even when we increased log verbosity
