### ISSUE TITLE
Serde issue with custom schema registry naming

### ISSUE THREAD

**Issue by PabloLec** [provectus/kafka-ui#4279]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

This issue follows up on this discussion: https://github.com/provectus/kafka-ui/discussions/4109. I am opening it to potentially make tracking easier. My problem still persists on the master branch.

Here’s a summary of my problem originating from the discussion:

To recap my problem:

- The naming convention for my subjects is "avro[TOPIC]event".
- My schemas are correct, and the Schema Registry appears to be properly loaded and utilized in the UI.
- However, I encounter an issue where Serde fails, displaying the message "Fallback serde was used."
- This leads me to believe that my naming convention isn't recognized, or there might be an error in my configuration settings.
- I haven’t been able to obtain any specific logs when encountering Serde errors using the UI.

Below is my current configuration. Although it likely contains unnecessary fields, I’ve included them to cover all debugging possibilities I am aware of:

```
kafka:
  clusters:
    -
      name: local
      bootstrapServers: kafkabroker:9092
      schemaRegistry: http://kafka-schema-registry:8081
      schemaRegistryKeySchemaNameTemplate: "avro%sevent"
      schemaRegistrySchemaNameTemplate: "avro%sevent"
      serde:
        - 
          name: SchemaRegistry
          keySchemaNameTemplate: "avro%sevent"
          schemaNameTemplate: "avro%sevent"

```

### Your installation details

Docker image master, commit 53a6553

### Steps to reproduce

Use a custom schema naming convention such as : `avro%sevent`
