### ISSUE TITLE
Add SASL_SSL setup in UI and in docs for config file

### ISSUE THREAD

**Issue by andr1an** [provectus/kafka-ui#4299]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Hello! I haven't found a guide on how to configure my JAR-based installation to connect to Kafka cluster that is using mTLS together with SASL PLAINTEXT auth. It's not described in the docs how to specify the keystore path and the password in the YAML config file, examples are available only for SSL without SASL, or SASL without SSL, or for Docker-based installation.

### Describe the feature you're interested in

It would be handful if it would be possible to set up SASL_SSL connection in the UI, or a config file example would be provided.

### Describe alternatives you've considered

I've got my configuration working by manually editing my config file:

```yaml
kafka:
  clusters:
  - bootstrapServers: kafka-01:9092,kafka-02:9092,kafka-03:9092
    name: kafka-test
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required
        username="root" password="pass";
      ssl.keystore.password: test-password-999
      ssl.keystore.location: /etc/kafkaui/uploads/kafka-test-trust.jks-1697717352
    readOnly: false
    ssl:
      truststoreLocation: /etc/kafkaui/uploads/kafka-test-trust.jks-1697714496
      truststorePassword: test-password-999
```

### Version you're running

56fa824 (v0.7.1)
