### ISSUE TITLE
Truststore configs seem to be ignored for Schema Regsitry TLS connection

### ISSUE THREAD

**Issue by riedelmax** [provectus/kafka-ui#4305]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Hey Everyone,

I am trying to establish a connection to an HTTPS Schema Registry url. However, I get SSLHandshakeException.

config:
```
yamlApplicationConfig:
  kafka:
    clusters:
      - name: name
        bootstrapServers: bootstrap.url
        defaultKeySerde: SchemaRegistry
        defaultValueSerde: SchemaRegistry
        schemaRegistry: https://schemaregistry.url
        properties:
          security.protocol: SSL
          ssl.truststore.location: /ssl/kafka-user-secret/ca.crt
          ssl.truststore.type: PEM
          ssl.keystore.location: /ssl/kafka-user-secret/user.crt
          ssl.keystore.type: PEM
```
The brokers are mTLS secured, Schema Registry just uses TLS on server side without client authentication. The presented server certificates are signed by the same CA and this certificate is present in /ssl/kafka-user-secret/ca.crt. I already verified the certificate in two ways:

The broker connection is working and it is using the same truststore. Kafka UI shows topics and everything cluster related.
I used the same ca.crt to connect to the HTTPS Schema Registry url via curl. This also works fine.
The exception is The connection observed an error io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

During startup the AdminClientConfig values are printed to the log. They don't look suspicious:
```
ssl.cipher.suites = null
ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
ssl.endpoint.identification.algorithm = https
ssl.engine.factory.class = null
ssl.key.password = null
ssl.keymanager.algorithm = SunX509
ssl.keystore.certificate.chain = null
ssl.keystore.key = null
ssl.keystore.location = /ssl/kafka-user-secret/user.crt
ssl.keystore.password = null
ssl.keystore.type = PEM
ssl.protocol = TLSv1.3
ssl.provider = null
ssl.secure.random.implementation = null
ssl.trustmanager.algorithm = PKIX
ssl.truststore.certificates = null
ssl.truststore.location = /ssl/kafka-user-secret/ca.crt
ssl.truststore.password = null
ssl.truststore.type = PEM
```
In the documentation it is stated that Kafka UI use the same truststore for Schema Registry, Broker and Connect. Am I missing something?

### Expected behavior

As stated in the documentation I would expect that Kafka UI uses the same truststore for the Schema Registry Connection as for the Cluster connection. 

### Your installation details

1.  App version: https://github.com/provectus/kafka-ui/commit/56fa824
2. Helm chart version: 0.7.5
```
# Name of the secret holding the KafkaUsers keystore, password and CA certificate
playgroundKafkaUserSecret: &playgroundKafkaUserSecret playground.infra.kafka-ui

replicaCount: 1

image:
  registry: registry-url
  repository: provectuslabs/kafka-ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "kafka-ui"

serviceAccount:
  create: true

existingConfigMap: ""
yamlApplicationConfig:
  kafka:
    clusters:
      - name: playground
        bootstrapServers: bootstrap-url
        defaultKeySerde: SchemaRegistry
        defaultValueSerde: SchemaRegistry
        schemaRegistry: https://schema-regsitry.url
        properties:
          security.protocol: SSL
          ssl.truststore.location: /ssl/kafka-user-secret-playground/ca.crt
          ssl.truststore.type: PEM
          ssl.keystore.location: /ssl/kafka-user-secret-playground/user.crt
          ssl.keystore.type: PEM

probes:
  useHttpsScheme: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi

autoscaling:
  enabled: false

volumeMounts:
  - name: kafka-user-secret-playground
    mountPath: /ssl/kafka-user-secret-playground
    readOnly: true

volumes:
  - name: kafka-user-secret-playground
    secret:
      secretName: *playgroundKafkaUserSecret

```

### Steps to reproduce

n/a

### Logs

 WARN [reactor-http-epoll-4] r.n.h.c.HttpClientConnect: [c16ed88f, L:/172.18.2.118:47778 ! R:registry-url] The connection observed an error
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425)
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1277)
at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1264)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1209)
at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1559)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1405)
at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1246)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1295)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
... 18 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: ...
... 32 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
...
... 37 common frames omitted
