### ISSUE TITLE
Audit log doesn't work

### ISSUE THREAD

**Issue by WarszawskiDev** [provectus/kafka-ui#4309]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

I have Apache Kafka UI cluster section configured same like described in this documentation page: https://docs.kafka-ui.provectus.io/configuration/audit-log

`kafka:
  clusters:
    - name: local
      BOOTSTRAPSERVERS: kafka1:19092
      audit:
        topic-audit-enabled: true
        console-audit-enabled: true
        topic: "__kui-audit-log" # default name
        audit-topic-properties: # any kafka topic properties in format of a map
          - retention.ms: 43200000
        audit-topics-partitions: 1 # how many partitions, default is 1
        level: ALL # either ALL or ALTER_ONLY (default). ALL will log all read operations.`

I also have rdap with azure oauth2 configured based on roles - if it's important
Applications starts normally but there is no even any information about audit logs in console (also with log level trace)

docker-compose file:

`kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 2222:8080
    depends_on:
      - kafka1
    volumes:
      - /kui-config.yml:/kui-config.yml
    environment:
      SPRING_CONFIG_ADDITIONAL-LOCATION: /kui-config.yml`

### Expected behavior

Audi log should log information about topic/message access

### Your installation details

1. 0.7.1
2. -
3. Available in description
4. -

### Steps to reproduce

Run application with audi log enabled like described here: https://docs.kafka-ui.provectus.io/configuration/audit-log

**Comment by andyhuynh3** [comment]
I was able to get audit logging working with the [`master`](https://hub.docker.com/layers/provectuslabs/kafka-ui/master/images/sha256-633606ca07677d1c4b9405c5df1b6f0087aa75b36528a17eed142d06f65d0881?context=explore) tag and with the properties as camelCase rather than kebab-case. So for example, something like

```yaml
kafka:
  clusters:
    - name: local
      BOOTSTRAPSERVERS: kafka1:19092
      audit:
        topicAuditEnabled: true
        consoleAuditEnabled: true
        topic: "__kui-audit-log" # default name
        auditTopicProperties: # any kafka topic properties in format of a map
          - retention.ms: 43200000
        auditTopicsPartitions: 1 # how many partitions, default is 1
        level: ALL # either ALL or ALTER_ONLY (default). ALL will log all read operations.
```
