### ISSUE TITLE
Error 302 on basic-auth POST request

### ISSUE THREAD

**Issue by ledoc** [provectus/kafka-ui#4320]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Hi, I've installed kafka-ui with Helm

kafka-ui works fine without authentication.

But as soon as I set basic-auth authentication and access to kafka-ui via ingress or port-forward, the login form is displayed but  when I enter my credentials and confirm with the button, the form shows me invalid user / password, but when I go to the developer console I see that the request is in error with the **code 302 not found**

### Expected behavior

When I submit my basic-auth credentials kzfka-ui handle well the POST request and kafka-ui opens.

### Your installation details

**Helm versions:**
- version: 0.7.5
- appVersion: v0.7.1

Here's my configuration:

**Context**
Load Balancer Nginx Plus in front of kubernetes clusters with upstream on nodeport of ingress controller

**Kubernetes**: 1.21 with nutanix karbon

**Ingress Controller**
[Nginx Ingress controller inc](https://www.nginx.com/products/nginx-ingress-controller/) version 2.3

Ingress in Helm's values file:
```
...
ingress:
  enabled: true
  annotations: {}
  ingressClassName: "nginx230"
  path: "/"
  pathType: "Prefix"  
  host: "kafka-ui-example.priv"
```

configmap:
```
data:

  KAFKA_CLUSTERS_0_NAME: "$KAFKA_CLUSTER_NAME"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka/kafka-cluster-kafka-bootstrap:9093"
  AUTH_TYPE: "LOGIN_FORM"
  MANAGEMENT_HEALTH_LDAP_ENABLED: "FALSE" 
  DYNAMIC_CONFIG_ENABLED: "true"
```

the secret:
```
type: Opaque
data:
 KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: $B64_TRUSTORE_PASSWORD
 KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: $B64_KEYSTORE_PASSWORD
 SPRING_SECURITY_USER_NAME: b64_user
 SPRING_SECURITY_USER_PASSWORD: b64_password
```

### Steps to reproduce

Apply the configuration describe in my installation details

**Comment by ledoc** [comment]
Hello,
Does anyone have an idea for correcting this behavior? It bothers me a lot to get stuck on something as simple as this.

**Comment by p-eye** [comment]
@ledoc hi, it looks like the secret values are not passed to configmap.
did you test a static value like this?
```
data:
  KAFKA_CLUSTERS_0_NAME: "$KAFKA_CLUSTER_NAME"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka/kafka-cluster-kafka-bootstrap:9093"
  AUTH_TYPE: "LOGIN_FORM"
  SPRING_SECURITY_USER_NAME: "admin"
  SPRING_SECURITY_USER_PASSWORD: "pass"
```

if it not works, it problems with ingress config. 
if it works, how about trying to read value from secret and pass it?
