### ISSUE TITLE
RBAC: Inconsistent Topic Creation Permissions

### ISSUE THREAD

**Issue by abix5** [provectus/kafka-ui#4328]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

The current configuration for topic permissions is not working as expected. According to the configuration, topics should only be allowed to be created with names starting with "test-", but I am able to create topics with any name.

### Expected behavior

According to the configuration, topics should only be allowed to be created with names starting with "test-".

### Your installation details

```yaml
- resource: topic
  value: "test-.*"
  actions: 
    - VIEW
    - CREATE
    - EDIT
    - DELETE
    - MESSAGES_READ
    - MESSAGES_PRODUCE

- resource: topic
  value: "^(?!test-).*"
  actions: 
    - VIEW
    - MESSAGES_READ
    - MESSAGES_PRODUCE
```

or

```yaml
- resource: topic
  value: "test-.*"
  actions: 
    - VIEW
    - CREATE
    - EDIT
    - DELETE
    - MESSAGES_READ
    - MESSAGES_PRODUCE

- resource: topic
  value: ".*"
  actions: 
    - VIEW
    - MESSAGES_READ
    - MESSAGES_PRODUCE
```

### Steps to reproduce

- Create a topic with a name that does not start with "test-".
- Verify that the topic is successfully created.

**Comment by xpeoh** [comment]
I'm also seeing this issue.

```
        - name: "developer"
          clusters:
            - Dev
          subjects:
            - provider: ldap
              type: group
              value: "Kafka-dev"
          permissions:
            - resource: topic
              value: "dev.*"
              actions: [ view, create, edit, delete, messages_read, messages_produce, messages_delete ]
```

With this rbac the user can still create a topic with any name. However, they are not allowed to view it so after creating it they are redirected to the 403-page because the interface tries to send you to that topic after creation.
