### ISSUE TITLE
Cluster name is not url-escaped when accessing the `/ui/clusters/<cluster_name>` endpoint

### ISSUE THREAD

**Issue by cavokz** [provectus/kafka-ui#4345]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

I created a cluster with name `a/b` but when I click on ex. `Brokers` under its name on the left pane I get an empty page on the right.

### Expected behavior

I expect I can access the brokers page as for any other cluster.

### Your installation details

I run it as part of a docker compose, this is the relevant section:
```
  ui:
    container_name: ui
    image: provectuslabs/kafka-ui:master
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'

```

### Steps to reproduce

* Start the docker image
* Configure a valid cluster, put a `/` in its name
* Wait until the cluster is accessed and shown on the left pane
* Try to access any page under its name group, es. `Broker`

### Screenshots

![Screenshot 2023-12-05 at 18 47 52](https://github.com/provectus/kafka-ui/assets/586179/4df02362-ce52-489d-b48f-aa2d9bb4365d)
