### ISSUE TITLE
Green tick sign with an active controller is placed next to the wrong controller

### ISSUE THREAD

**Issue by KrzysztofDzioba** [provectus/kafka-ui#4363]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Hi. I created 3 kafka brokers. In "Brokers" section, I can see "Active Controller" with a value 2. However, in the list of brokers below, I can see a green 'tick' mark next to broker ID 3. When I move a curson on this tick, I can read "Active Controller".

I checked the logs on each broker. I can read there following:
broker1: _DEBUG [Controller id=1] Broker 2 has been elected as the controller, so stopping the election process._
broker2: _INFO [Controller id=2] 2 successfully elected as the controller._
broker3: _DEBUG [Controller id=3] Broker 2 has been elected as the controller, so stopping the election process._

So the active one is **2**. **That means that tick mark next to broker id 3 is wrong.** (Or it's me that I can't get something here)

All best,
Chris

### Expected behavior

Green tick mark should be next to broker id 2

### Your installation details

tested on: [56fa824](https://github.com/provectus/kafka-ui/commit/56fa824)
v0.7.1

### Steps to reproduce

Use following docker file:

```
---
version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181
  
  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2

    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 49092:49092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://localhost:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    depends_on:
     - zookeeper-1
     - zookeeper-2
     - kafka-1
     - kafka-2
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-2:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-1:2181
```

### Screenshots

![image](https://github.com/provectus/kafka-ui/assets/23156969/b47ba42a-04ed-4cdf-950f-f01036ad2f80)

### Logs

![image](https://github.com/provectus/kafka-ui/assets/23156969/62ebb188-b50d-4746-ac5a-e5d506ac5175)

![image](https://github.com/provectus/kafka-ui/assets/23156969/7d5f2c8f-73a6-456f-9fc0-d21813d942c9)

![image](https://github.com/provectus/kafka-ui/assets/23156969/c83714fd-1979-4b2a-8322-381f3195af96)
