### ISSUE TITLE
Usage of ProtobufRawDecoder unclear

### ISSUE THREAD

**Issue by PreNoob** [provectus/kafka-ui#4382]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

I want to use the ProtobufRawDecoder as mentioned in the docs [here](https://docs.kafka-ui.provectus.io/configuration/serialization-serde#protobufrawdecoder).

I configured it like so:

```yaml
  kafka:
    clusters:
      - name: some-name
        bootstrapservers: some-bootstrapservers
        properties:
          ....
        serde:
          - name: ProtobufRawDecoder
``` 

Resulting in the following error
```
Caused by: com.provectus.kafka.ui.exception.ValidationException: 'className' property not set for custom serde ProtobufRawDecoderRow
```

After that I've checked the code for the protobuf raw serde and the name [here](https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/java/com/provectus/kafka/ui/serdes/builtin/ProtobufRawSerde.java#L16C13-L16C30) is `ProtobufDecodeRaw`.

```yaml
  kafka:
    clusters:
      - name: some-name
        bootstrapservers: some-bootstrapservers
        properties:
          ....
        serde:
          - name: ProtobufDecodeRaw
``` 
results in a similar error
```
Caused by: com.provectus.kafka.ui.exception.ValidationException: 'className' property not set for custom serde ProtobufDecodeRaw
```

Adding `className: com.provectus.kafka.ui.serdes.builtin.ProtobufRawSerde` resulted in the following error:
```
Caused by: com.provectus.kafka.ui.exception.ValidationException: 'filePath' property not set for custom serde ProtobufDecodeRaw
```

### Expected behavior

I would like to have proper documentation on how to setup/use the `ProtobufRawDecoder`.

### Your installation details

- App version: 56fa824
- Helm chart version: 0.7.5

### Steps to reproduce

Deployed the helm chart with the above mentioned configuration.
