### ISSUE TITLE
Issue with Non-Sequential Kafka Cluster Configuration Indexing in Docker Compose Environment

### ISSUE THREAD

**Issue by dkswnkk** [provectus/kafka-ui#4391]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)
I've encountered an issue while configuring multiple Kafka clusters in a Docker Compose environment for Kafka UI. It seems that the application requires the Kafka cluster environment variables (like KAFKA_CLUSTERS_N_NAME and KAFKA_CLUSTERS_N_BOOTSTRAPSERVERS) to be sequentially indexed without skipping any numbers. Specifically, if the sequence jumps (for example, from KAFKA_CLUSTERS_1_NAME directly to KAFKA_CLUSTERS_3_NAME without a KAFKA_CLUSTERS_2_NAME), Kafka UI does not recognize the configuration properly, leading to unexpected behavior or errors. Is this the intended behavior?

## Expected Behavior
I expected Kafka UI to either handle non-sequential indexes gracefully by ignoring missing indexes.

## Actual Behavior
Kafka UI seems to either crash or fail to display Kafka clusters correctly when the cluster configuration indexes are not sequential.

### Your installation details

```yml
version: '3'
name: newrror
services:
  kafka-ui:
    restart: always
    container_name: kafka-ui-project
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: DV-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ~
      KAFKA_CLUSTERS_1_NAME: ST-kafka
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: ~
      KAFKA_CLUSTERS_3_NAME: PR-kafka
      KAFKA_CLUSTERS_3_BOOTSTRAPSERVERS: ~
```

After this setup, if you run `docker-compose up -d` and try to access `http://localhost:8080/`, you will not be able to connect, and the container will crash shortly thereafter.

### Steps to reproduce

1. Set up a Docker Compose file with Kafka UI service.

2. Configure the environment variables for multiple Kafka clusters, intentionally skipping the index number (e.g., define KAFKA_CLUSTERS_0_NAME, KAFKA_CLUSTERS_1_NAME, and then directly KAFKA_CLUSTERS_3_NAME).

3. Launch the Docker Compose environment.

4. Observe that Kafka UI either shows errors or does not display the clusters as expected.
