### ISSUE TITLE
Validation error while producing message using external schema 

### ISSUE THREAD

**Issue by 0x6b61747a65** [provectus/kafka-ui#4451]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

While trying to produce message from UI using external schema registry getting error: `Content strict mode: unknown keyword: "schema".` No additional information is available because there is no verbose output on that issue, nor in error, nor in app logs.

### Your installation details

- App version: [83b5a60](https://github.com/provectus/kafka-ui/commit/83b5a60)
- Chart version: `0.7.5`
- Config:
```yaml
data:
  config.yml: |-
    kafka:
      clusters:
      - bootstrapServers: kafka-01.example.com:9091,kafka-02.example.com:9091,kafka-03.example.com:9091
        ksqldbserver: https://ksql.example.com
        name: kafka
        properties:
          sasl:
            jaas:
              config: org.apache.kafka.common.security.scram.ScramLoginModule required
                username="username" password="password";
            mechanism: SCRAM-SHA-512
          security:
            protocol: SASL_SSL
        schema-registry-ssl:
          truststore-location: /ssl/kafka.truststore.jks
          truststore-password: password
        schemaRegistry: https://schema-registry.example.com
        ssl:
          truststore-location: /ssl/kafka.truststore.jks
          truststore-password: password
```

### Steps to reproduce

Connect kafka-ui to an external schema registry such as [akhq](https://akhq.io). Go to "Topics" -> "Produce message". Produce message using schema from schema registry

### Additional context

We are using [akhq](https://akhq.io) as an external schema registry.
