### ISSUE TITLE
Content NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by vicziani** [provectus/kafka-ui#4467]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

I'am using the Apicurio Schema Registry. After I create a JSON schema and try to send a message, I get the following error message:

`Content NOT SUPPORTED: keyword "id", use "$id" for schema ID`

JSON Schema:

```json
{
  "$id": "https://training.com/EmployeeHasBeenCreatedEvent.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "EmployeeHasBeenCreatedEvent",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64",
      "description": "The employee's id."
    },
    "name": {
      "type": "string",
      "minLength": 1,
      "description": "The employee's name."
    }
  }
}
```

Reading messages based on the schema works well.

![image](https://github.com/provectus/kafka-ui/assets/1205411/60d166ac-fc3f-48d4-a85e-54059269ed73)

![image](https://github.com/provectus/kafka-ui/assets/1205411/b0530dba-5673-4b1f-b725-1f077f89614a)

Generates mock JSON based on schema:

![image](https://github.com/provectus/kafka-ui/assets/1205411/d6078c69-f323-41d7-a418-fbcbd4bd6179)

### Expected behavior

Send the message.

### Your installation details

83b5a60 v0.7.2

```yaml
  schema-registry:
    image: apicurio/apicurio-registry-mem:2.6.1.Final
    ports: 
      - "8081:8080"
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    depends_on:
      - kafka
    ports:
      - 8082:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schema-registry:8080/apis/ccompat/v7
      - DYNAMIC_CONFIG_ENABLED='true'
```

### Steps to reproduce

1. Create schema
2. Create topic
3. Send message

### Logs

Nothing appears in the log.
