### ISSUE TITLE
The connection address you set is invalid

### ISSUE THREAD

**Issue by wubie052** [provectus/kafka-ui#4474]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

After I set the cluster address in the webUI, the program did not connect to the specified cluster as expected, but connected to localhost.

### Expected behavior

in webUI:
![image](https://github.com/user-attachments/assets/84552e9c-ec9f-432f-856f-685f5dc48cc9)
in Docker container:
connector to `172.18.0.3:9093`

### Your installation details

```yml
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: "TRUE"
```

### Steps to reproduce

Run the `docker-compose up -d` command and try to set the specific IP address in the webUI.

### Screenshots

set:
![image](https://github.com/user-attachments/assets/84552e9c-ec9f-432f-856f-685f5dc48cc9)
in Docker container:
![image](https://github.com/user-attachments/assets/cb2418d1-f9a2-4a25-a4c4-68c924d4af5d)

### Logs

2024-08-19 11:27:27 2024-08-19 03:27:27,803 DEBUG [parallel-6] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: localhostTest
2024-08-19 11:27:27 2024-08-19 03:27:27,804 DEBUG [parallel-8] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: localhostTest
2024-08-19 11:27:27 2024-08-19 03:27:27,804 INFO  [parallel-8] o.a.k.c.a.AdminClientConfig: AdminClientConfig values: 
2024-08-19 11:27:27     auto.include.jmx.reporter = true
2024-08-19 11:27:27     bootstrap.servers = [172.18.0.3:9093]
2024-08-19 11:27:27     client.dns.lookup = use_all_dns_ips
2024-08-19 11:27:27     client.id = kafka-ui-admin-1724038047-12
2024-08-19 11:27:27     connections.max.idle.ms = 300000
2024-08-19 11:27:27     default.api.timeout.ms = 60000
2024-08-19 11:27:27     metadata.max.age.ms = 300000
2024-08-19 11:27:27     metric.reporters = []
2024-08-19 11:27:27     metrics.num.samples = 2
2024-08-19 11:27:27     metrics.recording.level = INFO
2024-08-19 11:27:27     metrics.sample.window.ms = 30000
2024-08-19 11:27:27     receive.buffer.bytes = 65536
2024-08-19 11:27:27     reconnect.backoff.max.ms = 1000
2024-08-19 11:27:27     reconnect.backoff.ms = 50
2024-08-19 11:27:27     request.timeout.ms = 30000
2024-08-19 11:27:27     retries = 2147483647
2024-08-19 11:27:27     retry.backoff.ms = 100
2024-08-19 11:27:27     sasl.client.callback.handler.class = null
2024-08-19 11:27:27     sasl.jaas.config = null
2024-08-19 11:27:27     sasl.kerberos.kinit.cmd = /usr/bin/kinit
2024-08-19 11:27:27     sasl.kerberos.min.time.before.relogin = 60000
2024-08-19 11:27:27     sasl.kerberos.service.name = null
2024-08-19 11:27:27     sasl.kerberos.ticket.renew.jitter = 0.05
2024-08-19 11:27:27     sasl.kerberos.ticket.renew.window.factor = 0.8
2024-08-19 11:27:27     sasl.login.callback.handler.class = null
2024-08-19 11:27:27     sasl.login.class = null
2024-08-19 11:27:27     sasl.login.connect.timeout.ms = null
2024-08-19 11:27:27     sasl.login.read.timeout.ms = null
2024-08-19 11:27:27     sasl.login.refresh.buffer.seconds = 300
2024-08-19 11:27:27     sasl.login.refresh.min.period.seconds = 60
2024-08-19 11:27:27     sasl.login.refresh.window.factor = 0.8
2024-08-19 11:27:27     sasl.login.refresh.window.jitter = 0.05
2024-08-19 11:27:27     sasl.login.retry.backoff.max.ms = 10000
2024-08-19 11:27:27     sasl.login.retry.backoff.ms = 100
2024-08-19 11:27:27     sasl.mechanism = GSSAPI
2024-08-19 11:27:27     sasl.oauthbearer.clock.skew.seconds = 30
2024-08-19 11:27:27     sasl.oauthbearer.expected.audience = null
2024-08-19 11:27:27     sasl.oauthbearer.expected.issuer = null
2024-08-19 11:27:27     sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
2024-08-19 11:27:27     sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
2024-08-19 11:27:27     sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
2024-08-19 11:27:27     sasl.oauthbearer.jwks.endpoint.url = null
2024-08-19 11:27:27     sasl.oauthbearer.scope.claim.name = scope
2024-08-19 11:27:27     sasl.oauthbearer.sub.claim.name = sub
2024-08-19 11:27:27     sasl.oauthbearer.token.endpoint.url = null
2024-08-19 11:27:27     security.protocol = PLAINTEXT
2024-08-19 11:27:27     security.providers = null
2024-08-19 11:27:27     send.buffer.bytes = 131072
2024-08-19 11:27:27     socket.connection.setup.timeout.max.ms = 30000
2024-08-19 11:27:27     socket.connection.setup.timeout.ms = 10000
2024-08-19 11:27:27     ssl.cipher.suites = null
2024-08-19 11:27:27     ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
2024-08-19 11:27:27     ssl.endpoint.identification.algorithm = https
2024-08-19 11:27:27     ssl.engine.factory.class = null
2024-08-19 11:27:27     ssl.key.password = null
2024-08-19 11:27:27     ssl.keymanager.algorithm = SunX509
2024-08-19 11:27:27     ssl.keystore.certificate.chain = null
2024-08-19 11:27:27     ssl.keystore.key = null
2024-08-19 11:27:27     ssl.keystore.location = null
2024-08-19 11:27:27     ssl.keystore.password = null
2024-08-19 11:27:27     ssl.keystore.type = JKS
2024-08-19 11:27:27     ssl.protocol = TLSv1.3
2024-08-19 11:27:27     ssl.provider = null
2024-08-19 11:27:27     ssl.secure.random.implementation = null
2024-08-19 11:27:27     ssl.trustmanager.algorithm = PKIX
2024-08-19 11:27:27     ssl.truststore.certificates = null
2024-08-19 11:27:27     ssl.truststore.location = null
2024-08-19 11:27:27     ssl.truststore.password = null
2024-08-19 11:27:27     ssl.truststore.type = JKS
2024-08-19 11:27:27 
2024-08-19 11:27:27 2024-08-19 03:27:27,806 INFO  [parallel-8] o.a.k.c.u.AppInfoParser: Kafka version: 3.5.0
2024-08-19 11:27:27 2024-08-19 03:27:27,806 INFO  [parallel-8] o.a.k.c.u.AppInfoParser: Kafka commitId: c97b88d5db4de28d
2024-08-19 11:27:27 2024-08-19 03:27:27,806 INFO  [parallel-8] o.a.k.c.u.AppInfoParser: Kafka startTimeMs: 1724038047806
2024-08-19 11:27:27 2024-08-19 03:27:27,809 INFO  [kafka-admin-client-thread | kafka-ui-admin-1724038047-12] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-1724038047-12] Node 1 disconnected.
2024-08-19 11:27:27 2024-08-19 03:27:27,809 WARN  [kafka-admin-client-thread | kafka-ui-admin-1724038047-12] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-1724038047-12] Connection to node 1 (localhost/127.0.0.1:9093) could not be established. Broker may not be available.
2024-08-19 11:27:27 2024-08-19 03:27:27,907 INFO  [kafka-admin-client-thread | kafka-ui-admin-1724038047-12] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-1724038047-12] Node 1 disconnected.

**Comment by NZenitram** [comment]
If you don't have metrics enabled this will fail every time.

**Comment by vishwasraj** [comment]
Try below config dockerfile

the config allows kafka-ui to access the kafka cluster within docker using this addr: kafka:9092 and you can access the kafka cluster outside of docker using localhost:9094

```
version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=Local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```
