### ISSUE TITLE
RBAC: Allow "all" operator in the clusters' list

### ISSUE THREAD

**Issue by nicklev** [provectus/kafka-ui#4490]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Describe the feature you're interested in

Hello,

I want to assign view or admin permissions automatically to new Kafka clusters. For that reason, it would be great if there was an "all" or "*" operator under clusters' list.

For example, see the following configuration sample:

```
rbac:
  roles:
    - name: "readonly"
      clusters:
        - all (or *)
      subjects:
        - provider: ldap
          type: group
          value: "XXX"
      permissions:
        - resource: XXX
          actions: [ "view" ]
```

### Version you're running

83b5a60
