### ISSUE TITLE
I propose to modify the notation method when the LAG of Consumer Group is 0.

### ISSUE THREAD

**Issue by K-Diger** [provectus/kafka-ui#4503]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

In the "Consumers" tab, there were cases where the LAG value for consumers was N/A.

However, when queried using the `describe` CLI command, LAG was displayed as 0.

I believe that N/A can also be accepted as "Not Available", **so I would like to modify it to display 0.**

### Expected behavior

In the "Consumers" tab, if the consumer's LAG is 0, it is displayed as 0 instead of N/A.

### Your installation details

- v0.7.2 (by DockerHub)

- with docker compose

```
name: kafka-ui
services:
  kakfa-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kakfa-ui
    ports:
      - '80:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka_cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:29092,localhost:29092,localhost:29092
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED=true
      - KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED=true
```

### Steps to reproduce

You can just consume a message to the topic without anything special or start the consumer without any message.
