### ISSUE TITLE
Error when trying to log in via oauth2

### ISSUE THREAD

**Issue by SyntaxJuggler** [provectus/kafka-ui#4513]
### Issue submitter TODO list

- [x] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [x] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [x] I've tried running `master`-labeled docker image and the issue still persists there
- [x] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

I want to log into the Kafka UI using users from my own identity server using oauth2/oidc. I was directed to the login page and after login I get Invalid credentials. I don't really understand how the callback uri works here and what to specify since I don't use any existing vendors, I didn't find anything related to this in the documentation.

```
  spring:
    security:
      oauth2:
        client:
          registration:
            oauth:
              client-id: "$"
              client-secret: "$"
              scope: "openid,profile,email"
              client-name: "name"
              provider: oauth
              redirect-uri: "https://*/login/oauth2/code/name"
              authorization-grant-type: authorization_code
          provider:
            learnhub:
              authorization-uri: "https://*/oidc/auth"
              token-uri: "https://*/oidc/token"
              user-info-uri: "https://*/oidc/me"
              jwk-set-uri: "https://*/oidc/jwks"
              user-name-attribute: "sub"
  auth:
    type: oauth2
```

### Expected behavior

Successful login using oauth2

### Your installation details

Using helm chart kafka-ui/kafka-ui in kubernetes

### Steps to reproduce

```
  spring:
    security:
      oauth2:
        client:
          registration:
            oauth:
              client-id: "$"
              client-secret: "$"
              scope: "openid,profile,email"
              client-name: "name"
              provider: oauth
              redirect-uri: "https://*/login/oauth2/code/name"
              authorization-grant-type: authorization_code
          provider:
            learnhub:
              authorization-uri: "https://*/oidc/auth"
              token-uri: "https://*/oidc/token"
              user-info-uri: "https://*/oidc/me"
              jwk-set-uri: "https://*/oidc/jwks"
              user-name-attribute: "sub"
  auth:
    type: oauth2
```
