### ISSUE TITLE
Avro deser with schema-registry do not work

### ISSUE THREAD

**Issue by raphaelauv** [provectus/kafka-ui#458]
Avro deser with schema-registry do not work

my setup 

```yaml
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9025:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-broker:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=schema-registry:8081
      - KAFKA_CLUSTERS_0_SCHEMANAMETEMPLATE="%s-value"
```

![Screenshot from 2021-05-15 17-46-24](https://user-images.githubusercontent.com/10202690/118370049-2aab4c80-b5a6-11eb-8289-41dc929edbb6.png)

it work with the control-center of confluent
![Screenshot from 2021-05-15 17-52-35](https://user-images.githubusercontent.com/10202690/118370093-62b28f80-b5a6-11eb-893e-a060a5d22dab.png)
