### ISSUE TITLE
Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi

### ISSUE THREAD

**Issue by survivant** [provectus/kafka-ui#474]
When I start this docker-compose, I obtain JMX error.

docker-compose up -V

````
---
version: '3.3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.1.0
    hostname: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - 9997:9997
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=broker -Dcom.sun.management.jmxremote.rmi.port=9997

  schema-registry:
    image: confluentinc/cp-schema-registry:6.1.0
    hostname: schema-registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.15.0
    hostname: ksqldb-server
    depends_on:
      - broker
      - schema-registry
    ports:
      - "8088:8088"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksqldb"
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksqldb/log4j.properties"
      KSQL_BOOTSTRAP_SERVERS: "broker:9092"
      KSQL_HOST_NAME: ksqldb-server
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.15.0
    depends_on:
      - broker
      - ksqldb-server
    entrypoint: /bin/sh
    environment:
      KSQL_CONFIG_DIR: "/etc/ksqldb"
    tty: true


  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "broker:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka-ui

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "broker:9092"
              schema-registry:
                url: "http://schema-registry:8085"
    ports:
      - 8888:8080
    links:
      - broker
      - schema-registry
    depends_on:
      - kafka-ui
````

````
kafka-ui           | 11:58:35.110 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.112 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.112 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.114 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.114 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.116 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.117 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.121 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.122 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.127 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.127 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.129 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.130 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.131 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.132 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.133 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.134 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.136 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.136 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.142 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.142 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.146 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.146 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.151 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.151 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.154 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.154 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.158 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot connect to KafkaJmxServer with url service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.158 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | 11:58:35.158 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.cluster.util.JmxClusterUtil - Cannot get JmxConnection from pool, service:jmx:rmi:///jndi/rmi://broker:9997/jmxrmi
kafka-ui           | java.lang.NullPointerException: null
kafka-ui           |    at org.apache.commons.pool2.impl.GenericKeyedObjectPool.returnObject(GenericKeyedObjectPool.java:470) ~[commons-pool2-2.2.jar!/:2.2]
kafka-ui           |    at com.provectus.kafka.ui.cluster.util.JmxClusterUtil.getJmxMetrics(JmxClusterUtil.java:47) ~[classes!/:?]
kafka-ui           |    at com.provectus.kafka.ui.kafka.KafkaService.lambda$getJmxMetric$51(KafkaService.java:400) ~[classes!/:?]
kafka-ui           |    at java.util.Optional.map(Optional.java:258) ~[?:?]
kafka-ui           |    at com.provectus.kafka.ui.kafka.KafkaService.getJmxMetric(KafkaService.java:400) ~[classes!/:?]
kafka-ui           |    at com.provectus.kafka.ui.kafka.KafkaService.lambda$fillBrokerMetrics$53(KafkaService.java:411) ~[classes!/:?]
kafka-ui           |    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
kafka-ui           |    at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:405) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
kafka-ui           |    at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:649) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
kafka-ui           |    at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:249) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
kafka-ui           |    at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
kafka-ui           |    at com.provectus.kafka.ui.cluster.util.ClusterUtil.lambda$toMono$0(ClusterUtil.java:40) ~[classes!/:?]
kafka-ui           |    at org.apache.kafka.common.internals.KafkaFutureImpl$WhenCompleteBiConsumer.accept(KafkaFutureImpl.java:177) [kafka-clients-2.4.0.jar!/:?]
kafka-ui           |    at org.apache.kafka.common.internals.KafkaFutureImpl$WhenCompleteBiConsumer.accept(KafkaFutureImpl.java:162) [kafka-clients-2.4.0.jar!/:?]
kafka-ui           |    at org.apache.kafka.common.internals.KafkaFutureImpl.complete(KafkaFutureImpl.java:221) [kafka-clients-2.4.0.jar!/:?]
kafka-ui           |    at org.apache.kafka.clients.admin.KafkaAdminClient$5.handleResponse(KafkaAdminClient.java:1642) [kafka-clients-2.4.0.jar!/:?]
kafka-ui           |    at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.handleResponses(KafkaAdminClient.java:1076) [kafka-clients-2.4.0.jar!/:?]
kafka-ui           |    at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1204) [kafka-clients-2.4.0.jar!/:?]
kafka-ui           |    at java.lang.Thread.run(Thread.java:830) [?:?]

````

**Comment by germanosin** [comment]
Hi, @survivant thank you for creating this issue, we'll check and return to you with possible solution.

**Comment by survivant** [comment]
there is a way to just disable jmx integration ?

**Comment by MarselAhmetov** [comment]
Hi! Sorry for long delay. Please check this docker-compose with actual version of Kafka-UI. 
You can disable jmx integration if you will not specify jmx.
Please write a comment if the bug is relevant.

**Comment by survivant** [comment]
where is the docker-compose you are talking about ?

**Comment by survivant** [comment]
I did this  : docker-compose up -V --remove-orphans

````
kafka-ui           | 14:41:34.069 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.util.JmxClusterUtil - Cannot get JMX connector for the pool due to:
kafka-ui           | java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: broker; nested exception is:
kafka-ui           |    java.net.ConnectException: Connection refused]
kafka-ui           |    at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:370) ~[?:?]
kafka-ui           |    at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
kafka-ui           |    at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
kafka-ui           |    at com.provectus.kafka.ui.util.JmxPoolFactory.create(JmxPoolFactory.java:17) ~[classes!/:?]
kafka-ui           |    at com.provectus.kafka.ui.util.JmxPoolFactory.create(JmxPoolFactory.java:12) ~[classes!/:?]
kafka-ui           |    at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.2.jar!/:2.2]
kafka-ui           |    at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1012) ~[commons-pool2-2.2.jar!/:2.2]
````

if I use this instead, I don't have the error

````
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
````
