### ISSUE TITLE
Error creating new topic

### ISSUE THREAD

**Issue by anjeyy** [provectus/kafka-ui#671]
**Describe the bug** 
Running with `docker-compose`, local cluster is up after a few seconds. 
So i was about to create a new _topic_ via UI `Add a topic`.
- Next i clicked `Add Custom Parameter`
- Clicked `Custom Parameter` to have a look, but i did not select anything
- Clicked the big red `-` button on the right to remove the _parameter row_
- Clicked the button at the buttom to finish creating a new topic
- Error came in with _code_ `500` and _message_ `message.downconversion.enabled` has to be either true or false

Just out of curiosity, i tried another creation with the same pattern, this time another error was show
```shell
Schema docker-compose
500 Unknown topic config name:
```

**Set up**
Running via `docker-compose`, configuration listed below.

```yml
version: "2"
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: kafka-zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181

    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka-core
        depends_on:
            - zookeeper
        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    kafka-ui:
        image: provectuslabs/kafka-ui
        container_name: kafka-ui
        ports:
            - "8080:8080"
        restart: always
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
            - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181

```

**Steps to Reproduce**

Please see athe top section **Describe the bug**.

**Expected behavior**
I was expecting to be creating a new topic for a local cluster.

**Note:** After leaving out the `Add Custom Parameter` section, creating topics is working fine.
