### ISSUE TITLE
Wierd characters while seeing messages

### ISSUE THREAD

**Issue by suyashdeshpande** [provectus/kafka-ui#686]
I installed it via helm in my k8s cluster. I was able to see the messages but they were not deserializing properly and hence were showing weird characters.
<img width="1416" alt="Screenshot 2021-07-16 at 10 05 23 PM" src="https://user-images.githubusercontent.com/28438230/125980335-33fd7e9f-e0a9-47e6-818e-30aaa2baa187.png">

**Comment by IldarAlmakaev** [comment]
What version of the app do you use? If you use the app with the **latest** tag, then could you please check it with **master** tag?
I think it should have been already released, but not as **latest**

**Comment by suyashdeshpande** [comment]
The issue is that it is not able to read Avro messages. I had to use a string value convertor to print them in readable format

**Comment by Haarolean** [comment]
@suyashdeshpande could you please try `master` image label if you're on `latest` as @IldarAlmakaev suggested?

**Comment by germanosin** [comment]
Hi, @erizzo. This looks strange. Could you please provide us more information on your cluster config, schema registry address, security and your UI for Apache Kafka config

**Comment by erizzo** [comment]
It's a simple configuration, everything running in local Docker Desktop, no security (yet).

```yaml
version: '2'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:29092,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_SCHEMA_REGISTRY_URL=schemaregistry:8081
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
   
  schemaregistry:
    image: confluentinc/cp-schema-registry:6.2.0
    container_name: schema-registry
    restart: always
    depends_on:
      - zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    ports:
      - 8081:8081

  kafka-ui:
    image: provectuslabs/kafka-ui:master
    container_name: kafka-ui
    restart: "no"
    ports:
      - "9001:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=schemaregistry:8081
    depends_on:
      - "kafka"
```

I know it can reach the schema registry because in the UI I can select the Schema Registry "tab" and see my schema there. And our application is publishing Avro messages using that registry.
