### ISSUE TITLE
Role based access control

### ISSUE THREAD

**Issue by germanosin** [provectus/kafka-ui#753]
Implemented. Documentation is [here](https://github.com/provectus/kafka-ui/wiki/RBAC-(role-based-access-control)) / @Haarolean  
---

The main idea of this feature is to provide access control for authenticated users based on roles.
Backend should support reading role bindings from git, s3, http, local yaml config
like
``` yaml
roleBindings:
   roleName:
     users: 
       - userName
```
and role access control file, like
```yaml
roles:
    roleName:
    permissions:
          - resource: consumerGroups
            includes: ["/.*/"]
            excludes: []
            allowedActions: ["listTopics"]
```
List of resources and actions should be defined and described in separate document.
Using this bindings and ACL lists, backend should check all actions from authenticated users and provide this list to frontend.
Frontend should use this data to show/hide certain action buttons, menus

**Comment by thealmightygrant** [comment]
Hey y'all, this is a really cool feature and I love this project. Do you think that this feature could pull Kafka permissions from [Kafka's ACLs](https://kafka.apache.org/documentation/#security_authz)? I believe that this information is accessible from the [Admin API](https://kafka.apache.org/26/javadoc/org/apache/kafka/clients/admin/Admin.html#describeAcls-org.apache.kafka.common.acl.AclBindingFilter-). The kafka-ui application could be authed to Kafka as a service account, and the UI could provide the actual filtering down of permissions via the Admin API.

**Comment by Haarolean** [comment]
Frontend:
- disabled menu actions instead of hidden + explanation

**Comment by allwritesri** [comment]
hello @Haarolean just wanted to know when could this be GA. thank you

**Comment by Haarolean** [comment]
> hello @Haarolean just wanted to know when could this be GA. thank you

soon :)

**Comment by Haarolean** [comment]
Backend done, pending frontend

**Comment by Haarolean** [comment]
The feature is implemented. Documentation is [here](https://github.com/provectus/kafka-ui/wiki/RBAC-(role-based-access-control))

**Comment by sookeke** [comment]
> The feature is implemented. Documentation is [here](https://github.com/provectus/kafka-ui/wiki/RBAC-(role-based-access-control))

Love this @Haarolean

**Comment by abhinavgautam07** [comment]
How to setup RBAC when using in kubernetes.

**Comment by Haarolean** [comment]
> How to setup RBAC when using in kubernetes.

the same way you do with docker-compose. Or you can use our [helm charts](https://provectus.github.io/kafka-ui/index.html)

**Comment by abhinavgautam07** [comment]
`replicaCount: 1

image:
  registry: docker.io
  repository: provectuslabs/kafka-ui
  pullPolicy: IfNotPresent

yamlApplicationConfig:
   kafka:
     clusters:
       - name: development-cluster
         bootstrapServers: kafka-cluster-kafka-advertiser-bootstrap.ms-kafka.svc.cluster.local:9092
   spring:
     security:
       oauth2:
   auth:
     type: OAUTH2
     oauth2:
       client:
         google:
           provider: google
           clientId: xxxxxx.apps.googleusercontent.com
           clientSecret: GOCSPX-xxxx
           redirect_uri: https://kafka-dev.urbancompany.com/login/oauth2/code/google
           user-name-attribute: email
           custom-params:
             type: google
             allowedDomain: urbancompany.com

podLabels:
  app: kafka-ui
  service-type: kafka
  service-name: ms-kafka
  team: platform


## Set field schema as HTTPS for readines and liveness probe
##
probes:
  useHttpsScheme: false

service:
  type: ClusterIP
  port: 80

# Ingress configuration
ingress:
  # Enable ingress resource
  enabled: true

  # Annotations for the Ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

  # ingressClassName for the Ingress
  ingressClassName: nginx

  # The path for the Ingress
  path: "/"

  # The hostname for the Ingress
  host: "kafka-dev.urbancompany.com"


resources:
  {}
  # limits:
  #   cpu: 200m
  #   memory: 512Mi
  # requests:
  #   cpu: 200m
  #   memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80


affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: nodetype
              operator: In
              values:
                - cpu-optimised
                - memoryoptimised
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - ap-southeast-1a


rbac:
  roles:
    - name: "readonly"
      clusters:
        - development-cluster
      subjects:
        - provider: oauth_google
          type: user
          value: "abhinavgautam@urbancompany.com"
      permissions:
        - resource: clusterconfig
          actions: [ "view" ]

        - resource: topic
          value: ".*"
          actions:
            - VIEW
        - resource: consumer
          value: ".*"
          actions: [ view ]

`

then i did `helm install kafka-ui kafka-ui/kafka-ui --values values.yaml`
The content of values.yaml is above.

**Comment by Haarolean** [comment]
@andreyolv there are examples of how to do that config-wise, the rest is just passing the config into k8s/helm.
https://provectus.gitbook.io/kafka-ui/configuration/rbac-role-based-access-control

**Comment by andreyolv** [comment]
@Haarolean my question is exactly this, how to pass the settings to k8s/helm, there is no example

**Comment by p-eye** [comment]
@andreyolv you can write like this
`
yamlApplicationConfig:
  rbac:
    roles:
      - name: "myname"
        clusters:
          - mycluster
        subjects:
        #...
`

**Comment by Haarolean** [comment]
@andreyolv 
https://github.com/provectus/kafka-ui/tree/master/charts/kafka-ui
`existingConfigMap` or `envs.config` (I don't personally recommend this one), or `yamlApplicationConfigConfigMap` or `yamlApplicationConfig`.
We'll update the main wiki with the chart info soon, I have a lot on the plate documentation-wise rn.

**Comment by abhinavgautam07** [comment]
@andreyolv, I am attaching a demo config that worked for me.
```
yamlApplicationConfig:
   kafka:
     clusters:
       - name: production-cluster
         bootstrapServers: kafka-cluster-kafka-advertiser-0.ms-kafka.svc.cluster.local:9092 
   auth:
     type: OAUTH2
     oauth2:
       client:
         google:
           provider: google
           clientId: XXXX.apps.googleusercontent.com
           clientSecret: GOCSPX-YYYY
           redirect_uri: https://kafka.urbancompany.com/login/oauth2/code/google
           user-name-attribute: email
           custom-params:
             type: google
             allowedDomain: urbancompany.com
   rbac:
     roles:
       - name: "admin"
         clusters:
           - production-cluster
         subjects:
           - provider: oauth_google
             type: user
             value: "abc@urbancompany.com"
           - provider: oauth_google
             type: user
             value: "def@urbancompany.com"
           - provider: oauth_google
             type: user
             value: "hdjfdf@urbancompany.com"
         permissions:
           - resource: clusterconfig
             actions: all

           - resource: topic
             value: ".*"
             actions: [ "view","create","edit","delete","messages_produce" ]

           - resource: consumer
             value: ".*"
             actions: all

           - resource: schema
             value: ".*"
             actions: all

           - resource: connect
             value: ".*"
             actions: all

           - resource: ksql
             actions: all
       - name: "readonly"
         clusters:
           - production-cluster
         subjects:
           - provider: oauth_google
             type: domain
             value: "urbancompany.com"
         permissions:
           - resource: clusterconfig
             actions: [ "view" ]

           - resource: topic
             value: ".*"
             actions: [ "view" ]

           - resource: consumer
             value: ".*"
             actions: [ view ]

           - resource: schema
             value: ".*"
             actions: [ view ]

           - resource: connect
             value: ".*"
             actions: [ view ]
``` 

PS: you can find rest of the commands and config on [artifactHub](helm install my-kafka-ui kafka-ui/kafka-ui --version 0.5.2).
also, a lot of thanks to @Haarolean, my issues are currently resolved, if any other issue comes up in the future, will connect on discord.
