### ISSUE TITLE
[helm] restart application when configmap or secret change

### ISSUE THREAD

**Issue by FedeBev** [provectus/kafka-ui#772]
### Is your proposal related to a problem?

In my opinion would be great if the deployment was automatically restarted when the configmap or secret changes.

### Describe the solution you'd like

Something like this should be enough
```yaml
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
```

Let me know what are your thoughts, I can deal with a PR
