### ISSUE TITLE
Hide key magic bytes

### ISSUE THREAD

**Issue by Schiavi91** [provectus/kafka-ui#899]
### Is your proposal related to a problem?

I see the magic bytes when the key is deserialized by AVRO and I would like to hide them.
I saw the pull request following issue #515 but I noticed that the magic bytes are still displayed in the key, is this a desired behavior? Is it possible to hide them?

### Describe the solution you'd like

Add a setting to hide magic bytes.

### Describe alternatives you've considered

Remove magic bytes.

**Comment by germanosin** [comment]
@Schiavi91. Thx for creating this issue. Could you please share your UI for Apache Kafka config, topic name, and schema names for value/key.

**Comment by Schiavi91** [comment]
I used docker-compose with this configuration:
```
kafka-ui:
    image: provectuslabs/kafka-ui:master
    hostname: kafka-ui
    container_name: kafka-ui
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "broker:29092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "http://schema-registry:8081"
    networks:
      - my-net
```
The topic name is "my-topic"
The schema name of the key is "my-topic-key"
The schema name of the value is "my-topic-value"
