### ISSUE TITLE
SCRAM Authentication always Fails

### ISSUE THREAD

**Issue by dendi-finaccel** [provectus/kafka-ui#911]
Hi @provectus-it 
Greetings!

Im trying to connect kafka cluster using SCRAM authentication. However I keep getting this error:

```
kafka-ui    | 12:31:53.415 [main] INFO  org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler - Initializing ExecutorService 'taskScheduler'
kafka-ui    | 12:31:53.531 [parallel-1] DEBUG com.provectus.kafka.ui.service.MetricsUpdateService - Start getting metrics for kafkaCluster: TEST-CLUSTER
kafka-ui    | 12:31:53.640 [main] INFO  org.springframework.boot.web.embedded.netty.NettyWebServer - Netty started on port(s): 8080
kafka-ui    | 12:31:53.646 [main] INFO  com.provectus.kafka.ui.KafkaUiApplication - Started KafkaUiApplication in 2.703 seconds (JVM running for 3.74)
kafka-ui    | 12:31:54.534 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.service.KafkaService - Failed to collect cluster TEST-CLUSTER info
kafka-ui    | org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512
```

My docker-compose.yml file:
```
version: '2'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=TEST-CLUSTER
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=b-3.central-kafka-01.XXXXXX.XX.kafka.ap-southeast-1.amazonaws.com:9096
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-512
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username='my-username' password='my-plain-password';
      - KAFKA_CLUSTERS_0_PROPERTIES_PROTOCOL=SASL
      - KAFKA_CLUSTERS_0_ZOOKEEPER=z-3.central-kafka-01.XXXXXXX.XX.kafka.ap-southeast-1.amazonaws.com:2181
```

Can you please take a look at what was am I missing?

Thank you
![image](https://user-images.githubusercontent.com/88323499/134909655-f5fc7aed-d667-49df-97db-2ac61cfbcc49.png)

**Comment by germanosin** [comment]
Hi, @dendi-finaccel. Thanks for creating this issue. We are trying to reproduce it.

**Comment by germanosin** [comment]
I tried to reproduce it with this docker-compose:

```
---
version: '2'
services:

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="password";'
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  zookeeper-add-kafka-users:
    image: confluentinc/cp-zookeeper:5.2.4
    depends_on:
      - zookeeper
    command: "bash -c 'echo Waiting for Zookeeper to be ready... && \
                          cub zk-ready zookeeper:2181 120 && \
                          kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-512=[iterations=4096,password=password]' --entity-type users --entity-name admin && \
                          kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-512=[iterations=4096,password=password]' --entity-type users --entity-name client '"

  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    volumes:
      - ./jaas:/etc/kafka/jaas
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: SASL_PLAINTEXT://kafka:9092,PLAINTEXT://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka:9092,PLAINTEXT://kafka:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas/kafka_scram_server.conf"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512,PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAINTEXT
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
```

And it works fine for me

Possible problems from your side are:

* Format of jaas config
```
KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="password";'
```
* User is not created in zookeeper

Could you please check this?
